### ISSUE TITLE
Clicking "send" button sometimes does nothing

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1004]
Sometimes (quite often) when I tap to send my message nothing happens.

Steps to reproduce:
1. Send many messages

Expected: messages always send when I tap send button
Actual: a second try is often needed

I'm not sure if it's the clickable area being too small or if the click is happening and then doing nothing, but I think it's the latter.

**Comment by holmesworcester** [comment]
@siepra can you still see this in your release? if not let's assume it was fixed by the inverted flatlist fix #891 / #918

**Comment by siepra** [comment]
Unfortunately it still happens

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1053

**Comment by kingalg** [comment]
v 0.8.4

I didn't experience this issue. Checked with the team and Emi, Wiktor and Damian don't have this problem and Bartek remember that he had this issue but didn't saw it from some time. I consider this issue to be resolved but I and Bartek are going to have an eye on this just in case.
