### ISSUE TITLE
Often stuck on startup screen

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1015]
Steps to reproduce on Android:

1. Start the app
2. Go to home screen
3. Swipe up to get task switcher
4. Swipe up on the Quiet app "screen" to remove it 
5. Reopen Quiet

Expected: user sees the channel list
Actual: user sees startup screen with "backend started" checked and "tor connected" unchecked, and app hangs on this screen

If we can write a unit test for this case somehow that would be great! When closing this issue if we have any thoughts about how to test this, include them here.

**Comment by holmesworcester** [comment]
@vinkabuki @Dinek007 any thoughts on what's happening here? this seems similar to the issue dinek just fixed on wake from sleep on desktop. https://github.com/TryQuiet/quiet/issues/984

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1002

**Comment by kingalg** [comment]
v 0.8.4

This may still happen but not from the reasons that were addressed in this issue. "Stuck on sturtap screen" is something that may happen from many reasons also in future releases. In this version I did not encounter this problem at all.
