### ISSUE TITLE
User can go "back" to connecting screen, and get stuck

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1016]
Steps to reproduce:

1. Start Quiet Android
2. When you land on the channel list, go back

Expected: nothing happens or user goes back to homescreen.
Actual: user goes back to connection screen and then can do nothing. Needs to close the app activity in their task manager.

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1002

**Comment by kingalg** [comment]
v 0.8.4

Fixed.
