### ISSUE TITLE
User should be able to send a message with mathematical notation (latex)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1025]
**UPDATED REQUIREMENTS**   

1. The message `$$\sum_{i=0}^n i = \frac{n(n+1)}{2}$$` should render in Quiet as it does in [this mathjax demo](https://www.cs.odu.edu/~zeil/cs390/latest/Public/texmath/demo.html).
2. The message `Hello! Does in-line LaTeX work? $$\sum_{i=0}^n i = \frac{n(n+1)}{2}$$` should render the same as in [this mathjax demo](https://www.cs.odu.edu/~zeil/cs390/latest/Public/texmath/demo.html) **or** in [this math.stackexchange.com question form](https://math.stackexchange.com/questions/ask). *Alternately, if combining text and latex math in a message is difficult:* a message that combines both should render as just text with no latex rendering or parsing at all. That is, we should only render latex that we can render correctly. For example in this case we could require that messages start and end with $$ to render latex formulas.
4. We should not worry about multi-line messages at all yet.

Both of these renderings of in-line latex mixed with text in the example in #2 are acceptable:
![image](https://user-images.githubusercontent.com/213678/210865352-f95dd1a2-0d89-4267-88e7-30ca72d02edd.png)
![image](https://user-images.githubusercontent.com/213678/210865426-a0e81df5-a72a-4a3e-a0be-6672f4ffdf6b.png)

--- 

**Background** 

A community of computer scientists and security researchers is interested in using Quiet. One feature their organizer would love is the ability to type math into a message, using Latex. I would like to deliver this feature to him quickly in order to demonstrate our excitement for his use case.

We should try to find the simplest/shortest path to adding Latex support. Ultimately we will want to add multi-line messages and markdown support, which he also wants. But for now we can just add this feature to show it off.

Math.stackexchange.com was his main reference for a site that does this well. They use MathJax. MathJax can export SVG, so rendering should not create security issues. (GitLab uses another library called KaTeX but that doesn't support SVG output, so I'm nervous about using it.) There might be performance issues on mobile with rendering SVG, but we use SVG already for our placeholder avatars, so we probably already pay that penalty. 

See:
1. https://docs.mathjax.org/en/latest/output/svg.html
2.https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference
3. https://www.npmjs.com/package/react-native-mathjax-svg

Ideas for implementation:
1. Generate an SVG on the client side when someone includes math in a message and attach it like any other  image with the latex markup in the text part of the message.
2. Render inline latex $...$ in a message, as in the example here: https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference and perhaps use https://www.npmjs.com/package/react-native-mathjax-svg on mobile
3. The above but put the latex on its own line, always.
3. Don't render them on mobile at all for now. Just show the unrendered latex on mobile.

**Comment by kowalski** [comment]
https://www.npmjs.com/package/react-native-latex this looks helpful

**Comment by kowalski** [comment]
I mean if we want to render on mobile too

**Comment by kowalski** [comment]
> https://www.npmjs.com/package/react-native-latex this looks helpful

Scratch that. I checked inside and I see it makes a call to external api for conversion. Obviously not something we want to do in Quiet.

**Comment by EmiM** [comment]
https://github.com/fast-reflexes/better-react-mathjax This looks quite promising for desktop, mathjax can be loaded locally so it doesn't have to make external requests. However it doesn't support `$$ $$` syntax afaik.

https://github.com/harunurhan/react-latex-next This supports old react unfortunately

https://www.npmjs.com/package/react-native-mathjax-html-to-svg This one we'll probably use on mobile.

**Comment by EmiM** [comment]
Mobile: https://github.com/TryQuiet/quiet/pull/1157

**Comment by EmiM** [comment]
Desktop: https://github.com/TryQuiet/quiet/pull/1161

* Scroll needs fixing - switching channels to the ones containing svg and sending message that renders svg breaks setting initial scroll position (it's not on the bottom). It's probably a timing issue - scrollbar position is set before all svg elements are attached to the DOM.
* Some formulas don't render sometimes - to be checked

**Comment by kingalg** [comment]
v. 1.0.0-alpha.16

Mathematical notations looks correct (on desktop and mobile). I wasn't able to crash the app (I could crash it at the beginning with first versions in November/December so it's definitely better now).

I've added below checks to my checklist:

1) Latex should work - can be tested with below message: Hello! Does in-line LaTeX work? $\sum_{i=0}^n i = \frac{n(n+1)}{2}$.
--
2) Latex - in notification and on preview latex is not working (thats ok).
3) Try different combinations of $.
