### ISSUE TITLE
Get iOS app working again

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1026]
We made a bunch of changes on the Android side and now we need to get iOS working again. Running in the background and notifications are not a requirement.

**Comment by siepra** [comment]
Don't anyone else want to work in this issue? I can give all the hints that comes to my mind, but I certainly don't have any knowledge nor experience with working on native ios layer at this level of complexity

**Comment by siepra** [comment]
One of related PRs (the rest of them has been merged earlier) https://github.com/TryQuiet/quiet/pull/1105

**Comment by kingalg** [comment]
IOS app is working and is stable for at least few weeks already. In latest releases I don't see anything that would be braking the app when the user uses very basic actions. We have iOS back and working again. Latest checked version 1.1.0 (239).
