### ISSUE TITLE
Image only displays after restart, even though download is complete

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1036]
In testing Quiet for a demo, I noticed that an image remained permanently in "spinner/placeholder" state even after the logs showed it had downloaded 100%. 

The scenario was:

1. Start a community with two users
2. Send several messages and a GIF
3. Join with a third device

Expected: image appears once it is downloaded (once logs show file 100% downloaded)

Actual: file is 100% downloaded but image does not appear. 

We should make sure the tests to catch this kind of bug are good!

**Comment by siepra** [comment]
Probably a duplicate of https://github.com/TryQuiet/quiet/issues/947

**Comment by Dinek007** [comment]
yes, it is duplicate of #947

**Comment by kingalg** [comment]
Duplicate with already resolved issue #947
