### ISSUE TITLE
Update js-ipfs when problem with ipfs-core-types is fixed

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#104]
There's a problem with wrongly built ipfs-core-types package published on npm (@0.8.4).

There's an open issue for that https://github.com/ipfs/js-ipfs/issues/3976

In order to make the CI work, I've added temporary workaround which removes broken files from that package on postinstall

**Comment by holmesworcester** [comment]
they've pushed a fix. can we verify and make this change?

**Comment by siepra** [comment]
Guys from ipfs provided @next tag for ipfs-core-types package - it means it's not yet included in official release of ipfs. Although we were able to force specific ipfs-core-types version and get rid of the patch (using npm-force-resolutions).
This is better yet still temporarily solution. We still need to observe the next releases of ipfs and update it as soon as the proper fix is included

**Comment by siepra** [comment]
Related PR
https://github.com/ZbayApp/monorepo/pull/341

**Comment by siepra** [comment]
Related issue https://github.com/ZbayApp/monorepo/issues/436
