### ISSUE TITLE
Create a PR for nodejs-mobile-react-native

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1048]
We have some copy/pasted code from nodejs-mobile-react-native that we created in the process of getting foreground services working in Android.

We should create a PR for nodejs-mobile-react-native so that that the upstream project can evaluate it and see if they want to include it.

**Comment by siepra** [comment]
Hm... the title of the task is pretty misleading. Also it will be a great bunch of work as we cannot simply do any diff between our code and the upstream project

**Comment by holmesworcester** [comment]
Closing for the reason stated above
