### ISSUE TITLE
User can send messages on "fetching  new messages" spinner, but won't see them.

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1054]
Steps to reproduce:

1. Join a community where fetching messages will take some time. 
2. When messages field appears on screen with "fetching new messages" spinner, send some messages.

Expected: messages appear as sent, once sent. 

Actual: message just disappears from view, leading user to think that something is broken and it has been lost, even though it has actually been added to orbitdb and sent.

Options: we could disable the text entry field until we are ready to display messages, but the best UX would be for the user to be able to send messages before messages have loaded (as they can now) but for messages to appear immediately as sent instead of disappearing. 

We could place the spinner at the bottom of the screen as if it was in the message list and make the font size smaller, so that when the user sends messages the messages just push it up as if it were a previous message.  Then it can disappear when some messages have been loaded. 

[Screen recording 2022-11-21 6.16.37 AM.webm](https://user-images.githubusercontent.com/213678/203043536-78f425fa-b508-4b96-a6b0-7ee35072d627.webm)

**Comment by holmesworcester** [comment]
So this is done? @Dinek007 is this ticket ready for QA?

**Comment by kingalg** [comment]
v 1.0.0-alpha.20

User can't type anything when "fetching new messages" spinner is active (which is correct).
