### ISSUE TITLE
Sending message should scroll to bottom of message list

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1064]
Right now when you scroll up and send a message it doesn't scroll to the bottom of the message list. It should. 

Update: I think this is not quite so simple and needs a design.

**Comment by jgaylor** [comment]
Quick research (on desktop):
* Slack doesn't scroll down in this case
* Mattermost does, and it's instant
* Signal does, and it's instant
* Telegram does, it's a little smoother, but still really quick

Not sure what needs to be designed, so maybe you can share the specific issues.

**Comment by jgaylor** [comment]
I'm also not sure it should scroll. I may be responding to something I'm looking at, and it would be jarring to move down. 🤷
