### ISSUE TITLE
Leaving screen with success message for user registration crashes the app

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1078]
v 0.8.4 mobile

Steps to recreate:
1. Join community on mobile and create new user.
2. Once success message for creating new user appears close the the app.
3. Open Quiet.
What should happen - user should see the same popup with success message or optionally they should be redirected to the channel list.
What happens - user see screen as below with inactive button "Done" and there is no possibility to move anywhere from this point.  
Update - there is a way to go pass this screen. If there is any notification from other users in the community and new user click on the notification correct message and channel appears. 

![Screenshot_20221205_152400](https://user-images.githubusercontent.com/68909168/205663676-7abf3ebe-f404-4531-9460-adfbd6ade1dd.jpg)

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1082

**Comment by kingalg** [comment]
v 0.8.5

Fixed.
