### ISSUE TITLE
Enable strict TypeScript

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1084]
Let's finish our transition to TypeScript

definitely do state-manager and backend. maybe wait for other bits.

Blocked by iOS bug

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/1098

**Comment by holmesworcester** [comment]
Let's assume that this is no longer blocked.

**Comment by holmesworcester** [comment]
duplicate
