### ISSUE TITLE
User can send a multi-line message (desktop)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1087]
Opening and trailing blank lines should be filtered out. Shift+enter creates a new line.

Message length should be bounded. Use Signal's limit. 

Kind of requires #1091

**Comment by holmesworcester** [comment]
@pdurbin should it be ctrl+enter too? which apps do this? (for me ctrl+enter is sort of the opposite where it means "send now!" in my email apps)

**Comment by pdurbin** [comment]
Whoops, if I wrote ctrl-enter, I meant shift-enter. To enter multiple lines, yes. I'm glad there's already an issue for this!

**Comment by holmesworcester** [comment]
@josephlacey this might be a good starter issue, though we should get to it soon.

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.3
Systems - all 

It's working.
