### ISSUE TITLE
Quiet stuck on community registration on Windows when user sleeps mid-registration

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1099]
v 0.14.5
System - Windows
(for other systems I wasn't able to get this result)

Steps to recreate:
1. Install fresh Quiet
2. Type new community name and instantly put your computer to sleep
3. Open computer again
What should happen - user should be able to create community and register username.
What happens - user is stuck on creating community screen.

**Comment by vinkabuki** [comment]
websocket connection is closed and frontend doesn't receive network data.

**Comment by holmesworcester** [comment]
are there any other situations that can cause this to happen? 

is this only happening on windows?

**Comment by holmesworcester** [comment]
@kingalg can you still reproduce this in the latest version? moving to blocked until this is confirmed.

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.30

Can't reproduce it anymore so I don't think that this problem still exist.
