### ISSUE TITLE
Double success message for registration 

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1102]
v 0.8.5 on android
v 0.14.5 on desktop

Android tried to join community created on MacOS. Duplicated success message appeared on general channel. 

<img width="423" alt="Screenshot 2022-12-12 at 16 20 44" src="https://user-images.githubusercontent.com/68909168/207086492-a7a6e0e9-b0b1-40f1-8fad-4f87a200b2ea.png">

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1104

**Comment by siepra** [comment]
I was not able to reproduce the problem but in the PR I suggested one possible solution which may secure the case

**Comment by EmiM** [comment]
It **may** be related: https://github.com/TryQuiet/quiet/pull/1106
Registration requests were doubled each time fetching registrar address threw error
