### ISSUE TITLE
Libp2p does not handle tor connection problem

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#111]
We knew that libp2p is trying to reconnect in case of failed connections, but there is at least one tor problem that does not disappear itself.

https://www.reddit.com/r/TOR/comments/a1vyxt/closed_1_streams_for_service_scrubbedonion_for/

  waggle:tor Nov 16 10:01:40.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
  waggle:tor  +15s
  waggle:tor Nov 16 10:01:56.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
  waggle:tor  +16s
  waggle:tor Nov 16 10:02:12.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
  waggle:tor  +17s
  waggle:tor Nov 16 10:02:27.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
  waggle:tor  +15s
  waggle:tor Nov 16 10:02:44.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
  waggle:tor  +16s
  waggle:tor Nov 16 10:02:58.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
  waggle:tor  +14s

**Comment by holmesworcester** [comment]
@vinkabuki still an issue?

**Comment by vinkabuki** [comment]
Not relevant anymore, closing
