### ISSUE TITLE
Emoji picker fails when internet offline

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1115]
Right now the emoji picker shows a blank grid of emojis when the network is offline. This suggests that the emoji picker might be connecting to the internet, i.e. not over Tor, which would be a security issue if true. 

Steps to reproduce:

1. Start quiet and connect
2.  Disable wifi
3. Open emoji picker and search for an emoji

Expected: all emojis display as normal

Actual: blank spaces appear

**Comment by EmiM** [comment]
Yes, it's downloading emojis from cdn

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1294

**Comment by EmiM** [comment]
Note for @kingalg: turn off internet connection after initializing tor but before opening emoji picker for the first time.

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.3
Systems - all

It's fixed. 

Steps I took to check it:
1. Installed fresh Quiet on all systems.
2. Wait for everyone to create/join community.
3. Turn off Internet (without opening emoji picker before!).
4. Once Internet is turned off open emoji picker for the first time.
5. Emojis should be displayed correctly in a picker and it should be possible to add them to the conversation the user is preparing to be send after Internet connection is established again.
