### ISSUE TITLE
Ctrl+z not working on chromebook

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1128]
v 0.16.0
System - chromebook

Ctrl+z is not working as expected on Chromebook.

No problems with ctrl+z on other systems.
Ctrl+a, ctrl+v ctrl+c are working correctly on all systems.

**Comment by holmesworcester** [comment]
I can't reproduce this on my chromebook. Odd!

**Comment by holmesworcester** [comment]
This works for me in latest ChromeOS in a debian VM.

**Comment by kingalg** [comment]
On this recording you can see me doing ctrl+v on typing area and then trying to use ctrl+z several times. 

[Screen recording 2022-12-15 13.30.19.webm](https://user-images.githubusercontent.com/68909168/207860130-82dd74de-2744-4c45-9d32-5e46b0b392b5.webm)

**Comment by kingalg** [comment]
Now (v 1.0.0-alpha.16) it does work on chromebook but doesn't on mac and windows.

Steps to recreate: copy some long text, past it using ctrl+v (or command+v). Use crtl+z or command+z. It doesn't undo last action instead it moves cursor to the begining of the sentence (exactly as in recording above).

**Comment by kingalg** [comment]
quiet@2.0.3-alpha.15

It's working on all systems now. I think that it may have started working when we did changes to text area. Anyway -  it's fixed.
