### ISSUE TITLE
**RELEASE PROCESS DOC**

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1130]
**Roles:**
* Team: team
* QA: @kingalg
* Release owner: @siepra 
* PM: @holmesworcester

**Trigger:** Release process begins when all issues from Sprint are merged and moved to Ready for QA. Typically we'll do desktop releases first, then repeat the process for mobile release.

**Process:**
1. **Team** ensures build is working correctly with automated tests and self-QA smoke test
3. **Team** prepares release candidate for **QA** (desktop alpha, Play Store internal, App store internal) on a release branch
5. **QA** tests for issues on call platforms and moves all blocking issues discovered (criteria: any regression, any new bug that creates a general feeling of unreliability, or any issue that is incompletely implemented according to the issue description) to Sprint column and mentions them in #qa channel.
7. **Team** drops any other work to work on new issues in Sprint column
5. **PM** can asynchronously decide a bug is not a blocker, devs and **QA** can consult **PM** if they suspect a bug is not really a blocker despite meeting criteria
6. **PM** can approve release in advance, pending completion of issues, or wait to give approval
6. Once all issues are complete, **QA** approves release and notifies **PM**, team
8. Once **PM** and **QA** approve release, **release owner** deploys release:
9. **Release owner** tells **PM** that root CHANGELOG.md is ready to be updated 
10. **Release owner** confirms that all hotfixes to previous releases have been merged to the release branch and to develop (this should have happened already)
11. **Release owner** promotes internal Play Store to external
12. **Release owner** submits internal App Store build for external review
13. **Release owner** updates links on website (in gh-pages branch) and in README
14. **Release owner** waits for App Store approval and promotes release to external
15. **Release owner** ensures developer instructions in README are up to date
16. **Team** merges any fixes from master to develop
17. **Team** can merge all work from branches to develop
18. **Team** bumps major dependencies (Node, Electron, React, React Native, IPFS, OrbitDB, Tor)
19. **Team** bumps any dependencies with dependabot alerts

This helpful diagram from @siepra captures the overall flow:![image](https://user-images.githubusercontent.com/213678/222443255-aee311c4-5d71-4d2c-bda2-4bd4a1dda380.png)Mobile checklist: https://docs.google.com/spreadsheets/d/1kAD-BeZ-OcjbvhKcwQL1cBDquBr0d6dAtg_x8maRsLQ/edit#gid=1459229595Desktop checklist: https://docs.google.com/spreadsheets/d/1OhgDfhESWPZbwp57KNTaceGUzB8TBLE0XDs0C8La2rY/edit#gid=0

TODO: summarize alpha release process

**Comment by leblowl** [comment]
@holmesworcester can we close this in favor of the PUBLISHING.md file?
