### ISSUE TITLE
User can't open files on mobile, and there's no explanation

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1133]
Right now when users try to view or open a file on mobile, nothing happens, which makes the app seem broken. Any solution that solves this apparent brokenness is an acceptable solution. 

For example:
1. User clicks a file and sees a message "Sorry, file open is not supported yet on mobile"
2. Quiet opens the file if it has already been downloaded, but shows a message "Sorry this file has not been downloaded yet" if not. 
3. The complete solution where things behave exactly the same as on desktop.

~If the complete solution with tests is less than a day's work, let's do it. Otherwise let's do whatever seems like it unlocks the most value for the least work.~

update: let's do 1 and just show "Sorry, files are not supported yet on mobile".

**Comment by EmiM** [comment]
It's not a bug, it's not implemented yet.

**Comment by EmiM** [comment]
@holmesworcester is it enough for now?
![Screenshot_20230308-182808](https://user-images.githubusercontent.com/6099829/223807321-92867242-4128-412e-8799-302c371c2137.png)

**Comment by holmesworcester** [comment]
Sorry, opening files is not supported yet on mobile.

(With a period at the end)

And the title could be 'Not supported yet'

And yeah that's good!

**Comment by holmesworcester** [comment]
@EmiM is this released? I see it was merged to develop some time ago.

**Comment by kingalg** [comment]
1.2.0

Looks like @holmesworcester described.

@holmesworcester - we need to discuss if we should show users that the file is downloaded as we do now. But this is discussion for different issue. This one is resolved. 

![Screenshot_20230424_132416](https://user-images.githubusercontent.com/68909168/233982955-cbf0197e-5358-4300-b799-6bdefea79947.jpg)
