### ISSUE TITLE
Messages "lost" (hidden) after update, still visible on mobile

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1135]
A group of users installed Quiet desktop from our website on November 22 on 2 Macs (version 0.10?) and were having a conversation. 

A third user joined their community on December 14th, and this caused everyone to lose their history going back to the 22nd. From this point forward they could only see messages going back to the 14th.

However, when people joined with Android (version?) the Android version synced all messages back to the 22nd. 

When Holmes joined with Quiet desktop (Linux, version 0.16 alpha) on  December 13, he was able to sync all messages. 

However when users with the missing messages upgraded on December 19 to version 16 (?) the old messages still did not reappear. 

Logs all seem normal and I can provide them. Not posting here because they contain user onion addresses.  

It seems like this problem will be difficult to reproduce, and that unless we have some immediate and correct hypothesis about what's happening we'll need tests that randomly try these sort of patterns of joining, disconnecting, connecting, and upgrading between different versions. 

My guess is that everything is synced but that the frontend is not updating for some reason. Or perhaps old messages are being treated as invalid because of some problem with the signature.

**Comment by kingalg** [comment]
I'm trying to reproduced it with a little more fresh channels but no luck. Could you tell me when you will have Quiet open on Monday so I can check this on all machines joining to our channel (it's oldest and it's the one where you encounter this issue, so it makes sense to check there). 
I need 1 - 2 hours when I will be sure that you have opened Quiet. 
(you can message me on Quiet qa channel with the time).

**Comment by holmesworcester** [comment]
@vinkabuki @EmiM what is a way to get logs from the users who are affected here?

**Comment by holmesworcester** [comment]
I'll ask folks for logs. In this case what we'll need is some way to see what people are experiencing without seeing all their messages. Like a sanitized version of app state that doesn't include private information.

**Comment by Kacper-RF** [comment]
The issue is probably deprecated and we cannot reproduce it (development team decision)
