### ISSUE TITLE
Secure backend socket.io from other applications that can access localhost i.e. browser

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#114]
https://stackoverflow.com/questions/14600472/securing-socket-io

**Comment by vinkabuki** [comment]
@holmesworcester not sure about if other apps can see this, afair not, but also I think other app can connect to our socket so it's even worse, but I am again not 100% sure, but I don't see any reason against it

**Comment by holmesworcester** [comment]
Note: we should fix these on master and release an update before 2.0

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1940
