### ISSUE TITLE
Fix scrollbar position (broken after adding latex support)

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#1163]
https://github.com/TryQuiet/quiet/issues/1025#issuecomment-1382892285

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1181

**Comment by EmiM** [comment]
Changed displaying tex to inline form. It would look like that:

![image](https://user-images.githubusercontent.com/6099829/213769243-8ca6a88f-cf72-4b6d-8892-61ce1220392f.png)

**Comment by holmesworcester** [comment]
Awesome! Is behavior similar now on both desktop and mobile?

**Comment by EmiM** [comment]
I did not touch mobile this time so it stayed the same as was before - also inline (see screenshot in linked issue).

**Comment by holmesworcester** [comment]
Great!

**Comment by kingalg** [comment]
v 1.0.0-alpha.20

Fixed.
