### ISSUE TITLE
Latency problem in 0.18.7-alpha.1

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1168]
Since the upgrade of ipfs/libp2p on mobile, we have observed that message latency sometimes increases to 30 seconds or more. 

Note that this is not just a connection failure. Messages don't simply stop working. And they don't "get stuck" and then heal after one successful message. Instead we can see very high latency across multiple messages.

It does seem to "heal" sometimes. 

I don't know of steps to reproduce, but it seems to happen in 3-user communities, and I think 2x desktop + 1 mobile is the scenario I've seen it in the most.

I'll throw down some hypotheses here but please don't let these stop you from investigating and creating your own hypotheses:

1. Latency happens when two nodes are not directly connected
2. Latency happens because the Tor connection is disrupted and then restored.
3. Latency happens because one or more Tor connections have very high latency (I don't think it's this, but it's possible)

**Comment by holmesworcester** [comment]
If you look at [libp2p-js releases](https://github.com/libp2p/js-libp2p/releases) there are some bugfixes since 0.40.0 that seem relevant to performance and latency/reliability:

* https://github.com/libp2p/js-libp2p/issues/1496
* https://github.com/libp2p/js-libp2p/pull/1527
* https://github.com/libp2p/js-libp2p/issues/1509
* https://github.com/libp2p/js-libp2p/pull/1498

Should we try upgrading?

**Comment by siepra** [comment]
Blocked by #1170

**Comment by Kacper-RF** [comment]
Fixed in https://github.com/TryQuiet/quiet/issues/1194
