### ISSUE TITLE
Slow connection times because libp2p isn't dialing simultaneously

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1169]
**Problem:** Since upgrading libp2p/ipfs, connecting to peers on startup and reconnecting after being offline are both slower than they should be because libp2p is not attempting multiple simultaneous connections. It should attempt some max of 10 connections at once. Right now it's attempting one connection at a time and only retrying when when connection fails. 

**What we think is going wrong:**  In our first refinements to libp2p we changed some settings so that libp2p would dial multiple addresses simultaneously. These settings no longer work.

**What counts as success:** We should be able to confirm that: 1) if you join a community, you attempt to dial all of the peers up to some configured max (currently 10?) simultaneously or as soon as you find out about them. 2) If you are in a community and reconnect, you should dial many peers simultaneously up to the max. Because the onion connection can take some time and because some peers will be offline, this will ensure that we find at least one good peer quickly.

**Comment by EmiM** [comment]
Found potential problems:
1. We have set 2 min timeout in libp2p peerDiscovery bootstrap config which caused libp2p to do nothing for the first 2 min. In other words - it started discovering peers from given bootstrap list after 2 min. Since no one remembers why we set it it will be removed (default timeout is 1 second so libp2p starts dialing peers right away).

2. Community owner is always bootstrapping with 1 peer (itself). Because of that owner's peer does not try to dial anyone and just waits to be dialed by some other peer. This is a bug, I will create a separate issue for that.
I'm wondering if we could use libp2p persistent datastore to keep information about discovered peers between app launches. One thing is that it would ignore our peers prioritization mechanizm.

**Comment by EmiM** [comment]
Notes:
* Autodialer dials one peer at a time (see https://github.com/libp2p/js-libp2p/blob/master/src/connection-manager/auto-dialler.ts#L137). I am pretty sure it always worked that way but this time response times are high, especially for 404 and 504 responses. Examples:

```
libp2p:dialer 1 tokens request, returning 1, 9 remaining +1ms
  backend:libp2p:websockets connect 2cwiluyne5p7qaazmx4kmjhmtty5giz3l7cpnkuzeela4d6khkdn5xid.onion:443 +11s
  backend:tor Jan 30 18:28:26.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
  backend:tor  +2m
  backend:libp2p:websockets:err connection error: Unexpected server response: 504 +2m
connect 2cwiluyne5p7qaazmx4kmjhmtty5giz3l7cpnkuzeela4d6khkdn5xid.onion:443: 2:00.136 (m:ss.mmm)
  backend:libp2p:websockets:err error connecting to /dns4/2cwiluyne5p7qaazmx4kmjhmtty5giz3l7cpnkuzeela4d6khkdn5xid.onion/tcp/443/wss/p2p/QmRhSxzVM5rYcDqhdW8T3UJWF8r1LciLMZmG6X7Li8HXKj. Details: Unexpected server response: 504 +0ms
```

-> **2:00.136 (m:ss.mmm)** of waiting for one dial

```
libp2p:dialer 1 tokens request, returning 1, 9 remaining +1ms
  backend:libp2p:websockets connect 2cwiluyne5p7qaazmx4kmjhmtty5giz3l7cpnkuzeela4d6khkdn5xid.onion:443 +2s
  backend:tor Jan 30 18:31:08.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
  backend:tor  +30s
  backend:libp2p:websockets:err connection error: Unexpected server response: 404 +19s
connect 2cwiluyne5p7qaazmx4kmjhmtty5giz3l7cpnkuzeela4d6khkdn5xid.onion:443: 18.507s
  backend:libp2p:websockets:err error connecting to /dns4/2cwiluyne5p7qaazmx4kmjhmtty5giz3l7cpnkuzeela4d6khkdn5xid.onion/tcp/443/wss/p2p/QmRhSxzVM5rYcDqhdW8T3UJWF8r1LciLMZmG6X7Li8HXKj. Details: Unexpected server response: 404 +0ms
```

-> **18.507s**  of waiting for one dial

**Comment by holmesworcester** [comment]
We need to find a way to force libp2p to be more aggressive and asynchronous/parallel when connecting to peers it knows about, otherwise it will take forever to connect to *any* peers. Let's ask them how!

**Comment by holmesworcester** [comment]
The release notes for 0.40.0 specifically say what to do to achieve the old behavior!

> to replicate the old behaviour, listen for ['peer:discovery'](https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#a-peer-has-been-discovered) events and [dial](https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#dial) peers manually

See: https://github.com/libp2p/js-libp2p/releases/tag/v0.40.0

Also, should we upgrade to 0.42? There are a bunch of bugfixes since 0.40.0 that could be creating issues for us. See my comment here: https://github.com/TryQuiet/quiet/issues/1168#issuecomment-1410629341

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1193
This MR includes:
* changes for #1189
* removing libp2p bootstrap 2m timeout 
* bugfix for sorting bootstrap peers introduced after upgrading libp2p (caused by libp2p event's object interface change)

Bumping libp2p will be done in a separate MR

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1198 - upgrade libp2p and its dependencies

**Comment by EmiM** [comment]
Further work here: https://github.com/TryQuiet/quiet/issues/1169
