### ISSUE TITLE
Tor onion address already registered error

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1171]
Since using Quiet 18, I have seen the following error in my logs:

` backend:tor Jan 17 12:07:35.000 [warn] Onion Service private key collides with an existing v3 service.`

While this is only a warning, I also see:

`  backend:conn Couldn't launch community for peer QmaUcphyAFUwpz4S3MGuzgSBuVv7ZP2oHE3MpvtD3HPExL. 550 Onion address collision +143ms`

Note that in this case I'm also seeing the error in #1167. Is it possible that this is the cause and `backend:conn` is incorrectly attributing it to the tor warning? 

Full error: `backend:conn Couldn't launch community for peer xxxx. 550 Onion address collision +636ms`

Steps to reproduce:
1. Start Quiet and create community. 
2. Quit and restart

Expected: everything works fine (it used to)
Actual: I get the above error.

Also it looks like it's a "non-fatal assertion", that is that Tor is still working. 

It seems like in this case you will not be able to be reached at this onion address until later when we're able to re-register. But that shouldn't mean we give up.

**Comment by vinkabuki** [comment]
It's on our side:

It happens when you try to spawn the second hidden service with the same privateKey as the first one. It is probably only symptom of other error. In case of failed community initialization, we send another request to initialize community which tries to spawn hidden service again

**Comment by siepra** [comment]
Blocked by #1170 (probably fixed in https://github.com/TryQuiet/quiet/pull/1193)

**Comment by EmiM** [comment]
@kingalg did you see this error in Quiet >= 1.0.0?

**Comment by kingalg** [comment]
@EmiM no, I've never seen this error neither in 1.0.0 or any older version (I didn't get Quiet 18 for tests so it was specific for this version I didn't had a chance to interact with it).

**Comment by vinkabuki** [comment]
closing as it's already fixed
