### ISSUE TITLE
Heisenbug when creating community (16.0.0)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1177]
In 16.0.0 we are getting a javascript error on startup when users first create a community. This may have "fixed itself" in 18 but we should assume it has not.

Here's what you see in the js console:

![image](https://user-images.githubusercontent.com/213678/212971575-733611f0-8313-4a36-b3bf-4eb92663c6e1.png)

Logs in CI look normal, nothing unusual.

**Comment by kowalski** [comment]
To clarify, does it end up working well once it connects ?
Or is the screenshot the final state and the app gets stuck at this point?

**Comment by holmesworcester** [comment]
The app gets stuck at this point, yes.

**Comment by kowalski** [comment]
The real problem is that we are stuck on the screen.
The problems about connecting to data port are not the issue, just happen to be on the screenshot

**Comment by holmesworcester** [comment]
Notes: we should look at what triggers moving on from this screen. (Bartek says that this screen should disappear once you have something in state manager, but Marek may be right that you might send channel data to backend too early before having a websocket connection, and then it's lost and never goes back to the app.)

**Comment by holmesworcester** [comment]
Let's wait until the new release is out, and then see if folks can reproduce this bug in the new release.

**Comment by Kacper-RF** [comment]
Unfortunately the problem still exists, Marek build version from develop branch on 10.02.23 and observed this bug

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/1251

**Comment by kingalg** [comment]
It's a heisenbug so there is no reliable way to test it. @vinkabuki added logs that will help us with diagnosis in case this happens again.

I'm closing this issue but this is "re-open in case of heisenbug" case.
