### ISSUE TITLE
[Feature Request] Enable easier onboarding via always on Stable Peer

### ISSUE THREAD

**Issue by vRobM** [TryQuiet/quiet#1180]
As a headless or headless+web client install in a docker container, one could deploy it on a VPS or more available node to avoid having the need for mobile/laptop intermittent users needing a synchronized onboarding. 

The web client would also allow for less local state keeping, allowing one to keep it on a home lab or other private space one has frequent access to.

If packaged for something like a Cloudron.io App, one gets access to a built in TURN/STUN server.

**Comment by holmesworcester** [comment]
Thanks for this suggestion and apologies for the slow reply. Right now I've been doing this (albeit in a less efficient way) simply by running a Quiet instance in a cloud-hosted Ubuntu VM and accessing it through VNC.

These were the steps I followed: https://ubuntu.com/blog/launch-ubuntu-desktop-on-google-cloud 

If you wanted to run Quiet in headless mode that would be fairly easy to do, as this is how our integration tests work: https://github.com/TryQuiet/quiet/tree/develop/packages/integration-tests

Is this helpful? 

Also, feel free to email me and I can invite you to our existing Quiet community, if you'd like to talk about this idea further! h@tryquiet.org

**Comment by holmesworcester** [comment]
Seems like we found a provisional solution here. Closing for now.

**Comment by johays** [comment]
> If you wanted to run Quiet in headless mode that would be fairly easy to do, as this is how our integration tests work: https://github.com/TryQuiet/quiet/tree/develop/packages/integration-tests

@holmesworcester can you elaborate how I get this up and running? This would be very helpful in regards of running a always-on peer on a headless server/VM.

As in the original post, I think this would be a big step forward in regards of onboarding.

Thanx for creating and maintaining this software <3
