### ISSUE TITLE
Channel creation shows "required field" error when field is filled in

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1188]
On the develop branch, if you create a channel and try to create a second channel, or if you start to create a channel and close the modal and try again, you will see a "required field" error as soon as you begin typing. 

Steps to reproduce:

1. Click "+" to create channel
2. Close modal 
3. Click "+" to create channel again and start typing a valid channel name and create a channel

Expected: you can create a channel, no errors

Actual: you see "required field" error and cannot create a channel. 

Notes:
* "Required field" error flashes on modal close
* Hot reloading seems to "fix" things until you close the modal again.

**Comment by holmesworcester** [comment]
It looks like we bumped [react-hook-form](https://react-hook-form.com/) so there may have been a breaking change, and you can see a lot of fixes of this sort of thing in recent releases. https://github.com/react-hook-form/react-hook-form/releases

I tried bumping to the most recent release 7.42.1 and ran into TypeScript errors.

**Comment by kingalg** [comment]
v 1.0.0-alpha.14

Fixed.
