### ISSUE TITLE
Community owner is bootstrapping network with only its peer address

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#1189]
General problem: peer always bootstraps with list of peers that was obtained while joining/creating community, list is never updated after that.

Why:
* Community is started right on CommunityManager initialization, peer list is read from the file, passed to libp2p bootstrap list 
* Then state manager calls backend to launch community and sends the proper list of bootstrap peers however this signal and the proper list is ignored because community has already been launched.

**Comment by holmesworcester** [comment]
This seems like it would really mess up 2 person communities. Moving this to next sprint.

**Comment by EmiM** [comment]
This is done in common PR with https://github.com/TryQuiet/quiet/issues/1169: https://github.com/TryQuiet/quiet/pull/1193
