### ISSUE TITLE
quiet should dial "top 10" peers simultaneously on startup

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1201]
Problem: Right now, libp2p is taking a long time to connect because new versions of libp2p don't autodial peers immediately on discovery.

Solution: 
- we should dial n peers immediately, simultaneously on startup or in < 10 seconds 
- Let's do n=10 to start. 
- they should be "top 10" peers by our sorting of last-seen / most-online

We should have a test that makes sure it is dialing the peers.

We aren't going to worry about redialing or dialing after the top 10 because libp2p eventually will start dialing peers itself, and because we have an open bug with libp2p seeing disconnects.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1220

**Comment by EmiM** [comment]
@kingalg connecting to peers should be quicker on startup (for returning user, not talking about registering).
Also it should try do dial peers until first successful connection, after that libp2p handles dialing.

**Comment by kingalg** [comment]
v 1.0.0-alpha.20

It's quite fast I had no issues with this in recent versions.
