### ISSUE TITLE
Windows CI for E2E tests 

### ISSUE THREAD

**Issue by Kacper-RF** [TryQuiet/quiet#1204]
u6dq2sauzm3xyrdtxkrbcupd5jwjbpiwj6sv4hielbiyhp7cgweth4qd

**Comment by holmesworcester** [comment]
@Kacper-RF can you add more information to this about what is missing and what is planned?

**Comment by Kacper-RF** [comment]
It worked locally, but the problem was only on CI.

What I've debugged in the past is that the test stopped in the CI workflow at the loader screen "Starting Quiet"  after the user clicked on this debug modal. So the whole process of installing in the workflow and running the application worked

I think this is a great time to look now at this CI for Windows, due to the many updates we have.

**Comment by holmesworcester** [comment]
Okay, moved to next sprint

**Comment by Kacper-RF** [comment]
@holmesworcester 
I found bug which was problem with creating data dirs in helper method for Windows system(its little bit tricky to run app in e2e tests on Windows).
I have to work more on that issue to provide ability to run tests with multiple clients for Windows - but now it's much more clear path.
At this moment for mac and 2 ubuntu's are working tests with 1 client and also 2 clients, but for Windows only 1 client.
![image](https://user-images.githubusercontent.com/111343884/223102767-9398a2e4-bdc1-4200-9a94-dbc6272af7e5.png)

**Comment by holmesworcester** [comment]
@Kacper-RF  I don't think this should block release. It seems unlikely that two-player connectivity will fail on Windows when the app starts on Windows and when two-player messaging works fine on other platforms. Let's make a separate issue for this with your notes and handle it later unless you're already deep into it and / or it's a quick fix.

**Comment by Kacper-RF** [comment]
Great idea, so I will create separate issue in backlog and will give pull request with fixed CI for team. I working on this problem yesterday a little bit, so i will add some notes in new task

**Comment by Kacper-RF** [comment]
Created issue: https://github.com/TryQuiet/quiet/issues/1291
