### ISSUE TITLE
messages arrive slowly

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1208]
steps to reproduce:

1. join our dev community on desktop and mobile with releases from the website
2. wait for everything to sync and be working well
3. upgrade mobile to the latest alpha release 0.19.19-alpha.19
4. send messages between desktop and mobile

expected: messages arrive quickly if we are connected

actual: messages from desktop to mobile arrive quickly, but messages from mobile to desktop arrive with a 1 or 2 minute delay.

**Comment by siepra** [comment]
First observation: I didn't see a delay on iOS (small community, mobile 0.19.19-alpha.20, desktop latest develop, after merging libp2p bump)

**Comment by holmesworcester** [comment]
I am also not seeing this problem in the latest release. Should we close this for now?

**Comment by siepra** [comment]
I think it sounds rationally
