### ISSUE TITLE
- treated as whitespace at the beginning of username

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1215]
Version - 1.0.0-alpha.8 (I don't think that it's a new thing)
System - all systems

We accept one special sign in username and it's "-". Additionally if user uses space inside of username it will change to "-". However if user want's to start username with "-" our system will treat it as a space and "name cannot contain whitespaces" error will appear.

Below you can see error that user gets when username starts with "-"
<img width="476" alt="image (6)" src="https://user-images.githubusercontent.com/68909168/218445508-b400c428-1611-49ab-8b80-94cf89727c8e.png">

The only change that I did was removing "-" at the beggining of username and as you can see error disappeared. 
<img width="455" alt="image (7)" src="https://user-images.githubusercontent.com/68909168/218445572-e11f2a5d-a42f-4e67-a993-8b7ab606cd22.png">

It's a small bug but we are potentially giving users misleading error message by informing them that they have whitespace in the username when in reality it's a special sign "-".

**Comment by kingalg** [comment]
v 1.0.0-alpha.20

@holmesworcester - right now it's resolved in a way that "-" at the beginning of username disappears. Do we want to change it or do we want to add a rule that username can only start with letter or number?

Which rule for creating username you prefer:
1. Username can start with letter or number.
2. Username can start with letter, number or "-".

**Comment by holmesworcester** [comment]
I prefer rule 1.

**Comment by kingalg** [comment]
@Kacper-RF I think that we have an error message that is listing rules for creating community name. Can we add this info? As for issue from the task it's resolved so I'm closing this.

v 1.0.0-alpha.20

**Comment by Kacper-RF** [comment]
@kingalg 
Created issue: https://github.com/TryQuiet/quiet/issues/1306
