### ISSUE TITLE
Updater failure - automatic update bugged

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1218]
System: all
Version: 0.16.0

Automatic updater for users with version 0.16.0 doesn't trigger an update.

It's version specific. I've got updater tests for previous version (that updated Quiet to 0.16.0) and everything was working. Currently with 1.0.0 updater is working correctly (for example update from 1.0.0-alpha.4 to 1.0.0-alpha.8). 

@holmesworcester I'm not sure how urgent it is as it looks like problem is already resolved in newer version but 1) there may be users stuck on 0.16.0 and we may want to inform them that they need to instal new version manually, 2) 0.16.0 is version that we are currently offering on tryquiet. I'm testing 1.0.0 right now but I'm still missing linux version so we can't yet add it to try quiet.

**Comment by holmesworcester** [comment]
How would we know that it doesn't trigger an update, if 0.16.0 hasn't been triggered yet by a release?

**Comment by holmesworcester** [comment]
I think this is fixed. Kinga accidentally got on a non-alpha release
