### ISSUE TITLE
Notifications sounds are not working

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1228]
System - all
Version - 1.0.0-alpha.13 

Notifications sounds are not working. You can check this in two ways:
1. Receive message in a way that will trigger notification (make sure that you have notifications with sound turn on).
2. Go to "NOTIFICATIONS" menu in Quiet and try to change sound - normally it would play the sound that you are choosing. Now there is no reaction when sound is changed.

**Comment by holmesworcester** [comment]
We should fix this. Are there any accepted options for testing that sounds work?

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1235

**Comment by EmiM** [comment]
Answering your question @holmesworcester - jsdom does not support any media operations so audio api mocking is the only way I suppose. I added that and other tests that are checking our case.

**Comment by kingalg** [comment]
v 1.0.0-alpha.15
Fixed for all systems.
