### ISSUE TITLE
"Channel with this name already exist" doesn't always appear when the criteria are met

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1233]
System - all
Version - 1.0.0-alpha.14

Issue - sometimes "Channel with this name already exist" doesn't always appear when the criteria are met.

Steps to recreate (you need to have at least two channels - general that is there by default and any other additional channel):
1. Try to create "general" channel - you will get error message "Channel with this name already exist" (everything looks fine)
2. Close the window for creating channels and reopen it.
3. Try to create channel with the name of your second channel.

What should happen - it should be impossible to create channel with the name of already existing channel and the user should get clear error message: "Channel with this name already exist".
What happens - channel is not created but there is no error message.

**Comment by holmesworcester** [comment]
do we know how long this bug existed for?

**Comment by kingalg** [comment]
No. I check if the user can create channel with the name that already exist but I check it only once (and if you try it one time everything looks fine, only with second try error is missing). I think that I did that check before as sometimes I do random things repeatedly just to try to break things in a new way but I don't have a line in my checklist for this and therefore can't tell you with 100% confidence that (and when) it was working. My suspicion is that it's rather new as we were changing some things in this field.

**Comment by kingalg** [comment]
v 1.0.0-alpha.20

Fixed.
