### ISSUE TITLE
Can't open link on Quiet - Chromebook

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1234]
System - ChromOS (but the same version on linux is working also versions for Mac and Windows are working)
Version - 1.0.0-alpha.14

Steps to recreate:
1. Send link. 
2. Click on the link. 

What happens - when the user click on the link send to Chromebook there is no reaction.
What should happen - link should work and new window/tab should open.

**Comment by holmesworcester** [comment]
We don't have any users at this point on Chromebook. I think we can stop QA on Chromebook until we do-- the main reason for this was that I was on Chromebook so these affected me (which this one doesn't even!)

Closing
