### ISSUE TITLE
File download doesn't work consistently

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1237]
System - all
Version 1.0.0-alpha.14

Issue: files above 20BM that user need to manually approve to download sometimes are not downloaded. It's very random, we've tried to work on steps to consistently recreate this with @EmiM but were not able to.
Tips:
- if you want to recreate it try sending bigger files, at least 50MB,
- most probably problem is on receiving side as in configuration 3 computers - 1 sender, 2 receivers it happen that one of the receivers downloaded file correctly and second one did not initial this process,
- in some cases restarting app helped,
- file that is stuck at "Queued for download" doesn't interrupt with other activities in the app - user still is connected to other peers, can receive and send messages, pictures and small files.

**Comment by EmiM** [comment]
I reproduced it on dev versions. It's stuck after getting stats about file: 

```
  backend:db downloadFile cid QmVjoPeak2pMpfoVVnamwtNJTF37m7WRuvbiSPgzbtXooS +0ms
  ipfs:mfs:stat Fetching stats for QmVjoPeak2pMpfoVVnamwtNJTF37m7WRuvbiSPgzbtXooS +0ms
  ipfs:mfs:utils:with-mfs-root Loaded MFS root /ipfs/QmRYBQmH6e8jfcjUtKMyUaaxDaqqsr2AaxJzB6cBXndaMj +0ms
  backend:db downloadFile stat QmVjoPeak2pMpfoVVnamwtNJTF37m7WRuvbiSPgzbtXooS {
  cid: CID(QmVjoPeak2pMpfoVVnamwtNJTF37m7WRuvbiSPgzbtXooS),
  type: 'file',
  size: 7505569,
  cumulativeSize: 7507376,
  blocks: 29,
  local: undefined,
  sizeLocal: undefined,
  withLocality: false,
  mode: 420
} +5ms
```

**Comment by holmesworcester** [comment]
Can we make a test that reproduces the problem if run it 20 times?

**Comment by kingalg** [comment]
You mean automatic or manual?

**Comment by holmesworcester** [comment]
Automated, but that's also a good question. How many attempts does it take you to reproduce the bug?  The important thing is to create a test that uses as little of our stuff as possible that shows the bug, so we can show this to ipfs folks. 

This could also be related to the "messages arrive after large delay" issue. Maybe it is happening not just for large files but for messages sometimes as well.

**Comment by EmiM** [comment]
At the time of sending file there were no delays with receiving messages. Ipfs didn't even start downloading a file.
I was able to reproduce it locally right away.

**Comment by kingalg** [comment]
I was able to spot it quite fast. It happens often enough that uploading 1-2 files and trying to download them on two other computers should be enough (at least it definitely was today). And what @EmiM said - we could see in logs that it wasn't a case of slow downloading but it in fact didn't start at all. If I was persistent enough after few restarts of our app I was able to download most of those files. So if it started the rest was fine.

**Comment by Kacper-RF** [comment]
We have idea to test it in integration test package, but firstly they need to be fixed.
https://github.com/TryQuiet/quiet/issues/1153

**Comment by EmiM** [comment]
Tried sending large files on smaller setup (without tor):
https://github.com/vinkabuki/closeorbitdb/blob/test/large-file/test.js
https://github.com/vinkabuki/closeorbitdb/blob/test/large-file-with-custom-libp2p/test.js
in both cases file is sent properly so we suspect the problem may be associated with tor.

**Comment by EmiM** [comment]
Checked with minimal setup + our websocketovertor - works randomly as expected (most of the time doesn't):
https://github.com/TryQuiet/quiet/blob/test/send-large-files/packages/backend/src/libp2p/filetest.test.ts
also checked websocketovertor but without tor (so peers connect on localhost). This works every time:
https://github.com/TryQuiet/quiet/blob/test/send-large-files-websocketovertor-without-tor-and-certs/packages/backend/src/libp2p/filetest.test.ts

**Comment by EmiM** [comment]
Potential fix: https://github.com/TryQuiet/quiet/pull/1260

**Comment by kingalg** [comment]
v 1.0.0-alpha.20
System - all

Small files are downloading without any issue. Bigger (I've checked on 70, 80 and 200 MB) are either stuck on "Queued for download" or at some point of downloading. I didn't manage to download any of them. However - when the user that uploaded the file send the same file second time and second user that is stuck (either in queue or at some point of downloading) download it - previous file unstuck and continue download.

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/1260 
Keep in mind that this is a very ugly solution and it might have some unwated side effects

**Comment by holmesworcester** [comment]
We discovered that the problem here is that IPFS doesn't give us any reliable progress indicator, and that the method we were using just shows sequential progress which is misleading especially for small or large files. The change made in this PR should be reverted because we don't have a strong reason to believe it solves the problem and it may have side effects.

This is the backlog issue for solving the problem: https://github.com/TryQuiet/quiet/issues/1265

This is the short-term fix: https://github.com/TryQuiet/quiet/issues/1264
