### ISSUE TITLE
User should be able to open a quiet:// URI to join a community

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1276]
Right now users have to copy and paste an invite code. Our end goal is that users can send each other invite links like Signal, WhatsApp, or Discord that will get them into a community.

This issue's requirement is that the user can open a quiet://  URI in the app, on all platforms (desktop and mobile) that will join them to a community if they are not already part of a community. 

All other cases are covered in other issues.

**Comment by EmiM** [comment]
@holmesworcester what should happen if user opens quiet:// link while already being in a community?
Possible options I though of:
1. Ignore and do nothing
2. Display information that user is already part of community + something like "you can leave current community and then use invitation link"
3. Display information that user is already part of community with option (button) to leave current community and restart quiet with new invitation code. Not sure if that's necessary.

**Comment by holmesworcester** [comment]
You can do 1 for now. 

There's a separate issue for this: #1286

**Comment by EmiM** [comment]
Notes:
* whatsapp uses: `whatsapp://chat/?code=<here goes the code>`
* go to username modal immediately unless invitation code is wrong then display 'join community' modal with error/warning message

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1341

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.26
Done.
