### ISSUE TITLE
Joining screen should explain to user why it's taking so long

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1277]
Right now it can take a long time to join a community. We should offer explanation to users of why it is taking so long. 

*DESIGN*

Mobile: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-%2B-desktop-%2B-prototypes?node-id=1427%3A34911&t=Rda4DFJRzND1fEIl-4

Desktop: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-%2B-desktop-%2B-prototypes?node-id=1430%3A56335&t=Rda4DFJRzND1fEIl-4

This screen should display until messages in the general channel are visible. Until we have a progress bar, we can show an indeterminate progress bar. 

We might need to change this text based on user feedback before releasing. Hopefully that can be avoided.

**Comment by holmesworcester** [comment]
Most important things to show:
1. Tor bootstrapping.
2. Tor connection process in registration (most important because this is where we get stuck; show a new message at the beginning of each fetch. This will repeat many times in most cases. 'fetching/timeout/fetching/timeout/etc')
3. Orbitdb block download of messages. (doesn't have to be continuous or "make sense" just show what's happening.) 

Notes:
* We don't want to show "errors" that are not really errors. (maybe change them in the logs or maybe hide them)
* Maybe debouncing is a good idea so we don't show everything but we should everything that takes 1s or 2s. 
* Being busy and fast is good
* It's good if we can see what we got stuck on for debugging purposes
* Think of yourself as an artist trying to give the user some clear information about what's happening and reassure them that something is happening. 
* We can use indeterminate progress bars in most cases (bonus if we use a steady progress bar)

**Comment by holmesworcester** [comment]
The video isn't playing for me for some reason but I looked at the list in the PR. What is orbitdb block download?

**Comment by holmesworcester** [comment]
Also can you create the issues for iOS and Android?

**Comment by Kacper-RF** [comment]
I was thinking about this comment `Orbitdb block download of messages. (doesn't have to be continuous or "make sense" just show what's happening.)`

At this moment i'm working on this problem that after last log `Launched community` is a gap without logs and sometimes it can go further(to main view with general channel) but messages are not loaded yet, so i think i have potential solutions but i also want to add some logs.

Sure i will add issue for mobile

I sent this video file on devs-update channel

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.26 - done on desktop, to be check on mobile, I'm moving this one to "Ready for QA mobile"

**Comment by kingalg** [comment]
As Kacper mentioned above, mobile is handled in #1374 
This one is for desktop and is correct.
