### ISSUE TITLE
User should be able to view QR code of invite link

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1285]
Like #1284 but with QR codes. 

This is more important on mobile than on desktop so do it on mobile first.

Designs: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-%2B-desktop-%2B-prototypes?node-id=1430%3A51227&t=mVi4elcoeo8vvJma-4

If it's easy to do this on desktop using the same mobile designs let's do that. If not let's skip it.

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1375

**Comment by holmesworcester** [comment]
For the designs, we want the settings designs to match mobile because that's just how Jason and I want to do things going forward because it saves us from having to always design two cases.

**Comment by siepra** [comment]
Ok, should we have a separate ticket for unifying the views?
