### ISSUE TITLE
User already in a community should see "Sorry you can currently only join one community at a time. Multiple communities coming soon!" alert

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1286]
Someday we'll have multiple communities, but right now you can only be in one, so when a user clicks on a join link we have to show them an error alert if they are already in a community, because we can't let them join.
 
Proposed alert text:

"Sorry, you can only join one community at a time. This will change soon."

I picture this as a floating alert that disappears after a few seconds. But the important thing is that it's standard and easy to implement. 

UPDATE: @siepra did this on mobile and we can use the same design and text that he created

UPDATE: this should also include e2e tests for opening the link.

**Comment by siepra** [comment]
Already done on mobile in the following PR https://github.com/TryQuiet/quiet/pull/1358

**Comment by siepra** [comment]
![screenshot_20230323-155558_720](https://user-images.githubusercontent.com/15381135/227243425-ed8bcd06-233a-4c67-bfda-d134ba72e1f0.png)

**Comment by EmiM** [comment]
This is how it looks when implemented using our existing modals mechanism:
![image](https://user-images.githubusercontent.com/6099829/229543384-1d34ea04-b724-40a2-aa99-7673e0aff7d5.png)

Should we also display a similar thing if the url or invitation code in the url is invalid?

**Comment by holmesworcester** [comment]
This should say "We're" instead of "We are".  

Also I think the large text + red text is a bit too much. Let's not use red text.

> Should we also display a similar thing if the url or invitation code in the url is invalid?

Sure:

**Invalid link**

The invite link you received is not valid. Please check it and try again.

**Comment by holmesworcester** [comment]
But also, does a mobile issue exist for that? I created a separate issue. https://github.com/TryQuiet/quiet/issues/1396

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1398

**Comment by EmiM** [comment]
E2E test https://github.com/TryQuiet/quiet/pull/1419. Case with user having app opened while clicking on invitation link

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.26
It's working correctly.
