### ISSUE TITLE
All users should be able to invite others, not just owner

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1290]
Right now only the community owner can access the invite link. 

This is somewhat unnatural because it means people can't invite others. And limiting access to the owner offers little real protection against rogue inviters, since after all it's just a link—one you can't even change yet—and every member has seen it at least once.

We should make it so that the invite link is available to all users in the same way. 

I think it should be in orbitdb and only writeable by the community owner, since putting it in orbitdb would let us make it so the owner can invalidate or update the link in the future.

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.24

On all desktop systems tested by me I had a correct tab "Invite a friend" and I was able to see and copy working invite code.
