### ISSUE TITLE
[E2E] - Run multiple clients on Windows

### ISSUE THREAD

**Issue by Kacper-RF** [TryQuiet/quiet#1291]
At this moment we have problems to provide DATA_DIR while running e2e test for Windows.
Its problematic for 2 reasons, firstly its required locally to remove main catalog Quiet form LocalAppData/Programs for every test run and second reason is that is impossible to test 2 clients at the same time.

**Comment by holmesworcester** [comment]
@Kacper-RF is this done?

**Comment by Kacper-RF** [comment]
Yes, for Windows now we have two clients test, invitation link test and one client test.
