### ISSUE TITLE
Add Tor test for both NumEntryGaurds=3 and VanguardsLiteEnabled=0

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1296]
Tor folks recommended a few settings changes to increase connection success rate and in #1241 we found that they both seem to work.

However, we don't know if their effect is additive or not. 

We should add a test where  NumEntryGaurds=3 **and** VanguardsLiteEnabled=0 to compare to the other results.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1308
