### ISSUE TITLE
Tor already running breaks startup?

### ISSUE THREAD

**Issue by pdurbin** [TryQuiet/quiet#1298]
As I mentioned to @holmesworcester in Quiet-Team, on my Macbook M2 Quiet was working with 0.16.0 but then it stopped working after it autoupdated to 1.0.0. I get the spin of death:

<img width="912" alt="Screenshot 2023-03-07 at 9 01 08 PM" src="https://user-images.githubusercontent.com/21006/223600079-19815f68-5c39-480e-99de-91c3a09e732e.png">

## Regular start

```
pdurbin@air ~ % /Applications/Quiet.app/Contents/MacOS/Quiet 
Read extra envs: { TEST_MODE: 'false' }
electron main
WARNING: Missing strong random number source
options {
  socketIOPort: '52001',
  appDataPath: '/Users/pdurbin/Library/Application Support',
  resourcesPath: '/Applications/Quiet.app/Contents/Resources',
  platform: 'desktop'
}
grep: Support/Quiet/TorDataDirectory: No such file or directory
Error returned: <dictionary: 0x7ff84fe99750> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7ff84fe998e8> { length = 18, contents = "Connection invalid" }
}
Checking for update
Update for version 1.0.0 is not available (latest version: 1.0.0, downgrade is disallowed).
```

## Debug start

```
Last login: Tue Mar  7 19:26:46 on ttys000
pdurbin@air ~ % DEBUG=backend* /Applications/Quiet.app/Contents/MacOS/Quiet
Read extra envs: { TEST_MODE: 'false' }
electron main
Error returned: <dictionary: 0x7ff84fe99750> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7ff84fe998e8> { length = 18, contents = "Connection invalid" }
}
WARNING: Missing strong random number source
options {
  socketIOPort: '52079',
  appDataPath: '/Users/pdurbin/Library/Application Support',
  resourcesPath: '/Applications/Quiet.app/Contents/Resources',
  platform: 'desktop'
}
  backend:conn Creating https proxy agent: 52083 +0ms
  backend:tor Initializing tor... +0ms
  backend:tor Trying to spawn tor for the 0 time... +41ms
grep: Support/Quiet/TorDataDirectory: No such file or directory
  backend:tor Mar 07 21:02:49.632 [notice] Tor 0.4.7.13 (git-7c1601fb6edd780f) running on Darwin with Libevent 2.1.11-stable, OpenSSL 1.1.1s, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
  backend:tor Mar 07 21:02:49.632 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
  backend:tor Mar 07 21:02:49.632 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
  backend:tor  +74ms
  backend:tor Mar 07 21:02:49.633 [notice] Opening Socks listener on 127.0.0.1:52085
  backend:tor  +1ms
  backend:tor Mar 07 21:02:49.633 [notice] Opened Socks listener connection (ready) on 127.0.0.1:52085
  backend:tor Mar 07 21:02:49.633 [notice] Opening HTTP tunnel listener on 127.0.0.1:52083
  backend:tor Mar 07 21:02:49.633 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:52083
  backend:tor Mar 07 21:02:49.633 [notice] Opening Control listener on 127.0.0.1:52084
  backend:tor Mar 07 21:02:49.633 [notice] Opened Control listener connection (ready) on 127.0.0.1:52084
  backend:tor Mar 07 21:02:49.000 [warn] It looks like another Tor process is running with the same data directory.  Waiting 5 seconds to see if it goes away.
  backend:tor  +0ms
Checking for update
Update for version 1.0.0 is not available (latest version: 1.0.0, downgrade is disallowed).
  backend:tor Mar 07 21:02:54.000 [err] No, it's still there.  Exiting.
  backend:tor Mar 07 21:02:54.000 [err] set_options: Bug: Acting on config options left us in a broken state. Dying. (on Tor 0.4.7.13 7c1601fb6edd780f)
  backend:tor Mar 07 21:02:54.000 [err] Reading config failed--see warnings above.
  backend:tor  +5s
```

Huh. Another Tor process? Maybe I'll reboot. Reading config failed? No idea.

**Comment by holmesworcester** [comment]
`  backend:tor Mar 07 21:02:49.000 [warn] It looks like another Tor process is running with the same data directory.  Waiting 5 seconds to see if it goes away.
`

@EmiM can you look into this?

**Comment by siepra** [comment]
`grep: Support/Quiet/TorDataDirectory: No such file or directory`

Can you check if the mentioned directory exists under this path?

**Comment by EmiM** [comment]
It seems like grep did not work properly so old tor process was not cleared and new one started. 
What `ps -A | grep Support/Quiet/TorDataDirectory | grep -v grep | awk '{print $1}'` gives you?
And if that does not work then check `ps aux | grep /tor`
I'm interested in paths.

**Comment by pdurbin** [comment]
Hey, thanks for getting back to me. Could the problem be that it's supposed to be "Application Support" rather than "Support"?

While I'm running Quiet (with the spin of death), I can see this from `ps aux | grep /tor`:

`pdurbin          37878   0.0  0.2 34870464  32544   ??  Ss    9:28PM   0:00.33 /Applications/Quiet.app/Contents/Resources/tor/tor --SocksPort 52778 --HTTPTunnelPort 52776 --ControlPort 52777 --PidFile /Users/pdurbin/Library/Application Support/Quiet/torPid.json --DataDirectory /Users/pdurbin/Library/Application Support/Quiet/TorDataDirectory --HashedControlPassword 16:8CB0763D19EDF59560FD7BD9A8DCC4DC9A65319195B0F11F2B0025F5AF`

That is, `/Users/pdurbin/Library/Application Support/Quiet/TorDataDirectory` so it's a bit suspicious to me that error is `grep: Support/Quiet/TorDataDirectory: No such file or directory`. Maybe we need to put quotes around it?

Anyway, once I quit Quiet I no longer see anything from ps when I grep for "tor" or "TorDataDirectory".

I hope that helps. Thanks for asking! And thanks for improving the title of this issue!

**Comment by pdurbin** [comment]
@holmesworcester and I talked through this a bit today:

<img width="1279" alt="Screenshot 2023-03-12 at 1 35 31 PM" src="https://user-images.githubusercontent.com/21006/224562109-21420a5b-43de-49c9-84c3-8b5a9d0af089.png">

**Comment by pdurbin** [comment]
I just quit Quiet 0.16.0 and did a `ps` before launching it again. There's a process running:

`  501 40229 40143   0 Thu11PM ??         0:24.43 /Applications/Quiet.app/Contents/Resources/tor/tor --SocksPort 53533 --HTTPTunnelPort 53531 --ControlPort 53532 --PidFile /Users/pdurbin/Library/Application Support/Quiet/torPid.json --DataDirectory /Users/pdurbin/Library/Application Support/Quiet/TorDataDirectory --HashedControlPassword 16:1F6B4B66D5E936D66027E568AF7603120E0A59363208850479B8CEE03B`

Should I kill it?

**Comment by pdurbin** [comment]
Phew! Just to be safe, I restarted my macbook. Yes, it auto-upgraded to 1.0.0 but I was able to connect! Closing! 🎉

**Comment by EmiM** [comment]
I can see the same log (`grep: Support/Quiet/TorDataDirectory: No such file or directory`) on Kinga's macbook so it's still an issue. The problem reveals itself only when previous tor process wasn't killed properly.
I have potential fix

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.4

Fixed.

How I've checked it:
1. I've opened Quiet from terminal on Mac (with M1).
2. I've used ctrl+C to close Quiet (as this way of closing Quiet often leave tor running).
3. Checked if tor is still listed in Activity Monitor (it was).
4. I've opened quiet again (without killing tor).
5. Quiet opened correctly, no disconcerting logs were present.
