### ISSUE TITLE
User should be able to leave community on mobile

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1300]
Mobile: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-(and-prototype)?node-id=460%3A17126&t=i2gvPatZAwQfFJIq-4

There's some reconciling we haven't done yet between mobile and desktop, and all the other mobile settings aren't there yet, so on mobile just stick "Leave community" in this menu that slides up from the bottom when you click the "..." menu button in the top right.

Confirmation prompt text below headline should be:

"Are you sure you want to delete [community-name] from this device?" (with community-name in bold)

Notes:

It should delete all files and IDs associated with this community to the point where there is no suggestion that this machine was ever a member of the community.
In the designs for the community owner it says "Delete community" but it should be "Leave community" for everyone.
Once they leave a community they should return to the join/create screen.

**Comment by siepra** [comment]
I've added context menu for community. The designs does not clearly specify if the underlying screen should be greyed-out, but I think it's not a good idea because of status bar (the one that displays information about the time, battery, notifications, etc.) which cannot be modified in that way and it stands out weirdly. I added a box shadow for the menu instead. Here is how it looks:
![Screenshot_20230309-133000](https://user-images.githubusercontent.com/15381135/224024468-1fc11af2-6a4c-4c81-9f15-026e82310752.png)

**Comment by siepra** [comment]
![Screenshot_20230309-144854](https://user-images.githubusercontent.com/15381135/224045519-0aa13b91-3b99-46b0-828e-d491aceeb0d8.png)

**Comment by siepra** [comment]
@kingalg this task's scope is actually both mobile and desktop, as we changed the way leaving community works on desktop platforms (it's now unified) so it needs additional care from you

**Comment by kingalg** [comment]
1.2.0

iOS and Android - on both systems I've managed to leave community succesfully.
