### ISSUE TITLE
White screen after joining community in 1.1.0 alpha

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1310]
Steps:

1. Join community

Expected: joins
Actual: window is just a white screen, and all activity in the logs stops. 

I can reproduce this every time on Chromebook/Debian and on macOS 12.6.3 Intel 

One important answer to get when we look into this is: how did this bug slide by our e2e tests?

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1312

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.3

Fixed
