### ISSUE TITLE
JS error after leaving community

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1311]
Steps to reproduce on macOS (intel 12.6.3) 

1. Create community
2. Open settings
3. Click "Leave community"
4. Confirm

Expected: I leave the community

Actual (on Debian/Chromebook): no error message. App just closes. But when I reopen it I have not left the community (!) 

Actual (on Mac): JavaScript error dialog appears. `Uncaught Exception: Error: EPERM: operation not permitted, scandir '/Users/Library/Application Support/AddressBook'`

Why is anything scanning the addressbook? Let's fix this and add a test that would catch this error.

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1316

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.3

I still got this error on Windows but in #1322 it was decided that we are disable leaving community feature on Windows for now and for the rest of the systems we have no such errors so I consider it done.
