### ISSUE TITLE
Self host fonts on tryquiet.org and /join pages

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1318]
Webflow's default behavior is to pull fonts from the Google CDN, which is an error. The fonts are open licensed fonts so we can self-host them; we just have to set this up. 

Requirements:
* No page on tryquiet.org should load fonts from an external source like google or webflow
* Double check on `/` and `/join` that no resources are loaded from webflow, google, or some other third party (github is okay) 
* Double check that no other assets are loaded from webflow or other CDNs

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.24

Done.

Checked - nothing in "Network" when page is loading and all of our fonts can be find in "Sources".
