### ISSUE TITLE
User should see informative status updates during startup (Android)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1331]
Like #1280 but on Android. 

If we can't get it working in a straightforward way, we could try faking it, e.g. by showing "connecting to community owner / Retrying" or some such.

**Comment by vinkabuki** [comment]
@holmes is this a duplicate of https://github.com/TryQuiet/quiet/issues/1374 ?

**Comment by holmesworcester** [comment]
#1374 is for joining a community and this is for startup.

**Comment by holmesworcester** [comment]
We're making startup mostly asynchronous now so this issue is no longer relevant.
