### ISSUE TITLE
PublicChannels selector caching problem

### ISSUE THREAD

**Issue by Kacper-RF** [TryQuiet/quiet#1332]
PublicChannels selector has problem with correct sorting channels because of some kind of caching problem from previous selector array instance.

Fix with using `Array.from(...)` didn't work.

**Comment by holmesworcester** [comment]
@Kacper-RF does this manifest as a bug? How does this impact the user?

**Comment by Kacper-RF** [comment]
@holmesworcester 
I fixed that with new second selector with similar logic.
This selector is related to the correct sorting of channels in the sidebar and I haven't seen issues with this for a long time so I'd say users are not impacted
