### ISSUE TITLE
Update README for mobile development with clarifications of process

### ISSUE THREAD

**Issue by josephlacey** [TryQuiet/quiet#1338]
* Wireless debugging seems to be required.  Need to confirm and if so, make this clearer in the documentation
* Can we just include a name for the running docker container for easier repetitive referencing?
* What is does linking local packages do? Is `npm link` run on the host machine or within the Docker container?  What's the '<path-to-linked-package>' listed here?

**Comment by josephlacey** [comment]
> * Wireless debugging seems to be required.  Need to confirm and if so, make this clearer in the documentation

Marked this as optional with a message about understanding one's local network before using this feature.

> * Can we just include a name for the running docker container for easier repetitive referencing?

I've included a name in the container, which makes the next command more succinct, but this does require removing the container when exiting in order to avoid a name collision the next time this command is run.  Should names be kept random because the containers  are reused?

> * What is does linking local packages do? Is `npm link` run on the host machine or within the Docker container?  What's the '' listed here?

I marked this as optional as my development has needed it.

---

Other changes,

* Changed the third step in the Docker container section to a single command for the install.
* Rewrote some parts to make it clearer what each step does.
* Cleaned up some of the formatting

Changes can be previewed here,

https://github.com/josephlacey/quiet/tree/documentation/1338/packages/mobile

**Comment by holmesworcester** [comment]
Looks good! 

Do you think we should include a note for people who have trouble with USB debugging to try wireless debugging?

**Comment by josephlacey** [comment]
> Do you think we should include a note for people who have trouble with USB debugging to try wireless debugging?

We could, yeah.  Wiktor and I are also having a conversation on the PR about a few of the other changes.

**Comment by josephlacey** [comment]
> > Do you think we should include a note for people who have trouble with USB debugging to try wireless debugging?
> 
> We could, yeah. Wiktor and I are also having a conversation on the PR about a few of the other changes.

Added a note about this.
