### ISSUE TITLE
User can get stuck in "required field" state when creating community

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1352]
I'm not sure what the steps to reproduce here are but it's possible to get stuck in a "required field" state when creating a community. I was not able to continue even though I was entering valid values for community name.

**Comment by holmesworcester** [comment]
@josephlacey i thought i'd assign this to you since you were working on it last and it seems like a left over case from the channel naming issue.

**Comment by kingalg** [comment]
@holmesworcester I have steps to reproduce it - I've managed to do this on all systems.

If you switch between join and create community several times and then try to create a community you get:
![Screenshot 2023-05-09 at 11 15 49](https://user-images.githubusercontent.com/68909168/237051511-82861b24-48a7-419a-99d2-44352d8b1f28.png)
This error is still there even if the user restart the app.

**Comment by kingalg** [comment]
Version: 2.0.0-alpha.3
Fixed for MacOs, Linux and. Windows.
