### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1360]
Getting this error now when running 1.1.1

It causes a JS error to be shown to the user on quit. 

```
(node:23876) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
```

@vinkabuki this is happening on my VM and I can give you access

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/1372

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.26
Fixed
