### ISSUE TITLE
Windows crash on first run

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1369]
A user just reported a crash when first running Quiet on Windows.
 
![image](https://user-images.githubusercontent.com/213678/227947000-f9533af8-08a9-4c2d-a605-3b5bf553cdb0.png)

**Comment by HarshKapadia2** [comment]
Hey! Thank you for raising this issue @holmesworcester and sorry for the delay on responding to this!

I faced this error on starting Quiet 1.1.1 on my Windows machine. After this, it keeps buffering on the 'Starting Quiet' screen. When I quit that, I get the error below:

![image](https://user-images.githubusercontent.com/50140864/229265140-279de8ed-8021-4ac4-9095-5d2e285d60f7.png)

Machine stats:
- Edition: Windows 11 Home Single Language
- Version: 22H2
- Installed on: ‎22-‎09-‎2022
- OS build: 22621.1344
- Experience: Windows Feature Experience Pack 1000.22639.1000.0
- Processor" Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
- Installed RAM: 8.00 GB
- System type: 64-bit operating system, x64-based processor
- Pen and touch: No pen or touch input is available for this display
- Manufacturer: Lenovo
- Laptop model: Lenovo Ideapad 330S

**Comment by holmesworcester** [comment]
Thanks for the additional info! We'll fix this soon!

**Comment by kingalg** [comment]
Hello @HarshKapadia2! We were handling and resolving this issue in another task but everything should be working fine in our current release. Please let us know if you still experience any problems and thank you for your feedback!
