### ISSUE TITLE
Joining screen should explain to user why it's taking so long

### ISSUE THREAD

**Issue by Kacper-RF** [TryQuiet/quiet#1374]
https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-%2B-desktop-%2B-prototypes?node-id=1427%3A34911&t=Rda4DFJRzND1fEIl-4

* On Android it should work as it does on desktop, as per designs.
* On iOS we will have access to less information and things work differently, so we don't need it to work the same
* We need some solution that ensures that iOS doesn't break
* iOS should show the same screens but could use an infinite progress bar or show less information. 
* The joining screen is more important than the startup screen so focus on that.

Also, right now, the "replicating messages" step takes a very long time in my tests. I see the channel list, and I see the most recent messages, but when I go into any channel I just see a spinner. This is true even for a community with ~100 messages, and for channels with 0 messages! We should give the user some clue as to what's happening in this step. There's no point showing the channel list if it will be several minutes before they can see any messages. Ideally we would do something that made this faster, but if we can't do that we should show them what's happening in a clear way.

**Comment by pdurbin** [comment]
Related (I think):

- #837

**Comment by Kacper-RF** [comment]
@holmesworcester 
I have to tune a little bit animation (in React Native is different then in standard React app, because it is based on native API).
I'm also thinking of waiting for the first few messages in the channels, because now we show the full list of channels, but we still have to wait a few seconds for the messages to load.

https://github.com/TryQuiet/quiet/assets/111343884/b4747d9a-4609-4994-b9b5-8bdc592f6a21

**Comment by Kacper-RF** [comment]
Update:

Already added logic to wait that some channels have last message( I noticed that if only one channel has loaded the last message, the time to load the rest of the last messages from the other channels is short ), and join to our mature community without problems.

**Comment by kingalg** [comment]
v. 1.6.0

Initial post touched some points that are handled by different tasks (like ensuring that iOS doesn't break). So what I've checked was:

1. joining screen is present and provide information on Android when user join community
2. joining screen is present and provide information on iOS when user join community
3. joining screen is present and provide information on Android when user creates community
4. joining screen is present and provide information on iOS when user creates community

All of them were present and giving users information about joining time. Information that user can exit app and we will notify them once they are connected is false (especially on iOS) but this issue is handled by https://github.com/TryQuiet/quiet/issues/1642

**Comment by holmesworcester** [comment]
![image](https://github.com/TryQuiet/quiet/assets/213678/b11cfc7e-922b-45e0-9c3e-0ee9e6b2976e)

Text follows. To be completely accurate, let's vary it depending on the platform.

## iOS

**Please leave this screen open. Joining the first time can take a few minutes or more.**

Quiet stores data on *your* community’s devices (not Big Tech’s servers!) using the battle-tested privacy tool Tor to protect your information. Tor is fast once connected, but it can be slow at first, and leaving this screen will stop the process of joining.

## Android

**Please leave this screen open. Joining the first time can take a few minutes or more.**

Quiet stores data on *your* community’s devices (not Big Tech’s servers!) using the battle-tested privacy tool Tor to protect your information. Tor is fast once connected, but it can be slow at first, and leaving this screen could stop the process of joining.

## Desktop 

**Please leave the app open. Joining the first time can take a few minutes or more.**

Quiet stores data on *your* community’s devices (not Big Tech’s servers!) using the battle-tested privacy tool Tor to protect your information. Tor is fast once connected, but it can be slow at first, and closing this window will stop the process of joining.
