### ISSUE TITLE
Mobile app breaks if opened from the invitation link while joining is already in progress

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1384]
e.g. between pasting an invite link and registering username

**Comment by holmesworcester** [comment]
Ready for review?

**Comment by siepra** [comment]
Temporarily blocked by https://github.com/TryQuiet/quiet/issues/1392

**Comment by kingalg** [comment]
mobile@1.2.1-alpha.6

It was hard to check because Quiet was too fast but after several attempts I've recreated situation that previously caused break and it looks like it's fixed.
