### ISSUE TITLE
Send button turns into Quiet icon (1.2.0-alpha 14)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1387]
Steps to reproduce:

1. Install Quiet 1.2.0-alpha.14 from tryquiet.org's play store link after having had a previous Quiet installed.
2. Join community
3. Begin typing in the message field

Expected: send button turns active
Actual: send button turns to Quiet logo

**Comment by holmesworcester** [comment]
This might be helpful? Seems like it was a bug in fresco, which we use https://github.com/facebook/fresco/issues/2667#issuecomment-1476119354

**Comment by siepra** [comment]
I checked bumping fresco requires also upgrading Kotlin and causes some crashes on app start, so maybe it's better to leave it as it is for now, or downgrade it to 2.5.0?

**Comment by holmesworcester** [comment]
Let's leave it, especially since we're not even sure if this is it. We can move this to backlog.

**Comment by siepra** [comment]
I think we can bump fresco as some time ago I bumped all major dependencies in Android project (including Kotlin cradle plugin)
