### ISSUE TITLE
Latest Android alpha crashes frequently

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1389]
One tricky thing about the release we've been working up to is that because invite links could be opened by a desktop user or an android user, we need to release them all at once. This means that any problems in the mobile release will block desktop release. 

I've been testing out the latest Android alpha and I've been seeing a huge increase in crashes and "OS kills app" to the point where it has become unusable with our internal community. (It still works fine with test communities which is probably why the issue has not been obvious in development. 

I've also seen problems on chromeOS:
https://github.com/TryQuiet/quiet/issues/1357

**Comment by siepra** [comment]
So I'd say the more data we process the more likely it is our app will be slaughtered by the os.
Nothing has changed in the very core of the Android app, so if you say small communities works fine, I think it's the best proof it's a matter of optimization
