### ISSUE TITLE
Spinner freezes after pasting invite code

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1404]
Steps:

1. Join community by pasting invite link/code

Expected: spinner button should appear and spin until next screen appears. 

Actual: it appears but freezes, which makes me think the app has crashed. 

Ideally this step should happen so fast that a spinner isn't even needed.

**Comment by siepra** [comment]
Does this happen on Android exclusively?

**Comment by holmesworcester** [comment]
We're redesigning this anyway to match desktop (with a progress bar, etc) so we don't have to worry about this.
