### ISSUE TITLE
Problem rejoining after leaving community

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1427]
Steps to reproduce on Ubuntu:

1. Join community
2. Leave
3. Try to join again with new username

Expected: it's fine
Actual: I got a ton of wild errors.

**Comment by vinkabuki** [comment]
could you paste some of these wild errors?

**Comment by holmesworcester** [comment]
I'm able to reproduce this every time.

**Comment by holmesworcester** [comment]
@Kacper-RF or @EmiM can you reproduce this? It seems like one of you is in the best position to fix it.

Here are the logs. It goes into some loop so the logs are giant. It was hard for me to tell when the actual error happened so I'm including everything. 

[error-logs-rejoining.zip](https://github.com/TryQuiet/quiet/files/11200227/error-logs-rejoining.zip)

**Comment by Kacper-RF** [comment]
PR: https://github.com/TryQuiet/quiet/pull/1439

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.28

Rejoined 5 times on each system (to the same community and also joined different community after quitting) and no errors or any other problems.
