### ISSUE TITLE
Loading Screens issues

### ISSUE THREAD

**Issue by Kacper-RF** [TryQuiet/quiet#1429]
- Showing the fun logo on community creation doesn't really make sense because it's like too fast +
- No need to say "this can take some time" if we're already showing some tor status update. Startup is fine without that. +
- Also this is on a temporary splash screen that disappears anyway. I think this should just show the logo. +
- "Fetching" is the step we get stuck on, so we should give more information here if possible. "Fetching" should be "Connecting to community owner via Tor" +

**Comment by holmesworcester** [comment]
@Kacper-RF is there a PR for these?

**Comment by Kacper-RF** [comment]
Yes - https://github.com/TryQuiet/quiet/pull/1435

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.30
Fixed.
