### ISSUE TITLE
"Join modal" visible after clicking invitation link on MacOS

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#1431]
User clicks on invitation link -> 'join modal' is displayed for a moment before user is redirected to 'username' modal.
It's visible when app is closed and user clicks on invitation link.

**Comment by holmesworcester** [comment]
We should fix this before release because most of our desktop users have been on mac, so everyone will see this.

**Comment by kingalg** [comment]
I've replicated this on my mac, so once we have a solution I will be able to check it immediately.

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.26
 Fixed.
