### ISSUE TITLE
"Invite a friend" tab should say "Add members" to be consistent with mobile

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1465]

**Comment by richardtorres314** [comment]
Hi @holmesworcester! I've created a PR that should address this GitHub issue if that's alright. Let me know your thoughts. Thank you!

**Comment by holmesworcester** [comment]
Thank you! I just approved the GitHub actions run and I bet a bunch of our snapshot tests will fail and need to be updated. For the sake of getting familiar with them would you like to update them? 

If you'd rather not I'm sure someone on the team can just do it and merge.

**Comment by richardtorres314** [comment]
Can and will do!

**Comment by richardtorres314** [comment]
@holmesworcester Looks like the PR has been merged. Can we close this issue? Thank you!

**Comment by holmesworcester** [comment]
I just moved this to "Merged". Our flow is to close issues after QA so I'll let @kingalg close it when she gets to it. 

It's good you pinged me though because we would have lost track of it otherwise. Thanks again!

**Comment by richardtorres314** [comment]
No problem!

**Comment by kingalg** [comment]
desktop@2.1.0-alpha.0
System: Windows, Linux, MacOS

Done.
