### ISSUE TITLE
Bottom sheet menu for share/add/leave/etc should be animated

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1474]
The bottom sheet appearing and disappearing feels pretty unnatural without animation. I believe the intention of the design was for this to animate. Something like this though I don't think we have any sheets so long they need to be scrollable:

https://github.com/gorhom/react-native-bottom-sheet

Also, when you click on items in this menu, the transition should animate in whatever the native way is on iOS, either to the right or down and back up again.

**Comment by siepra** [comment]
We cannot use the library you posted without refactoring the whole context menu part of the application. Although better solution is just to add https://reactnative.dev/docs/animations to the component (I believe we already use it somewhere else in the app).

Additionaly, context menu looks weird on iOS as it's bottom border displays differently than on Android. I think we can fix that as a part of this task



![Image](https://github.com/TryQuiet/quiet/assets/15381135/777586ba-cd7c-4a5d-b7eb-94516c4b7591)

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1589

**Comment by kingalg** [comment]
1.4.0
Mobile

If I understand it correctly bottom sheet movement when we display/hide it should be visible and animated. At least this is how it looks after recent changes and for me it looks nice.
