### ISSUE TITLE
Crash on iOS, lost community, had to reinstall

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1476]
I just experienced a string of weird behavior and crashes. Here's how it happened:

0. I disabled display lock on my phone so I could leave the app open
1. I joined a small community with ~100 total messages, two channels, and a handful of users, using the invite link.
2. Registration took a long time, but maybe it was just Tor randomness
3. I joined the community and I could see the channel list, but when i navigated into each channel it said "replicating messages" with a spinner (even the channel with 0 messages!) this spinner displayed for a really long time.
4. I successfully synced messages eventually (5-10 mins for 100 messages) and successfully sent some messages. everything was super fast. 
5. I left the app open for a while and at some point I locked my phone
6. When I returned to Quiet there was a black screen and no ability to do anything
7. I restarted the phone to see if that would help, and then opened Quiet again
8. Quiet started up and showed the "join community" screen... the community I'd joined was gone!
9. I tried to rejoin it by clicking the invite link
10. I saw the Quiet startup screen again (I think this means it crashed)
11. The app has been on the startup screen for several minutes and I think is just stuck. I'll have to uninstall and reinstall to fix this.

Some version of the above happened with another test too, again with a very small community (so it's not the known performance issue caused by many messages.

It seems like the important thing is for @siepra to get to a point where he can reproduce it. Maybe having an older/slower iPhone will help if there are difficulties reproducing this.

**Comment by siepra** [comment]
I think we should wait for #1574 to be done and then see if the problem persists

**Comment by siepra** [comment]
There's a great chance it's been fixed by https://github.com/TryQuiet/quiet/pull/1619

**Comment by holmesworcester** [comment]
Cool let's mark this as done

**Comment by siepra** [comment]
@holmesworcester what do we do about this one? Did anyone experience this problem since the release of the fix I mentioned in July?
