### ISSUE TITLE
User can't sign in on iOS: keyboard blocks "continue" button

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1494]
This happens on a bunch of screen sizes. We should push the form up to the top of the screen *and* let users scroll it, in case they have magnification cranked up. 

Also the form field should have focus and the keyboard should be open when you land on this screen, if it isn't already. 

![Image](https://user-images.githubusercontent.com/213678/235176085-ab6e135c-e17c-4cea-a855-3dbbfa81cc86.png)

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1595

**Comment by kingalg** [comment]
v 1.4.0

Done
