### ISSUE TITLE
User sees blank space under action sheet on iOS

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1496]
Action sheets are supposed to come up from the bottom, but on some iOS screen sizes we see a space below the action sheet. This looks weird and a bit broken.

Could be caused by the difference between buttonless and home-button iOS devices. 

![Image](https://user-images.githubusercontent.com/213678/235178458-7f6e05b0-29ec-4a80-9c5e-20d8b8e5c0a3.png)

**Comment by siepra** [comment]
https://github.com/TryQuiet/quiet/pull/1601

**Comment by kingalg** [comment]
v 1.4.0 
System - iOS

Now it looks fine.
