### ISSUE TITLE
"Link copied" overlay should be centered vertically

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1497]
This "link copied" overlay should be centered vertically; according to our designer it feels weird right now. (doesn't feel weird to me, but I trust him on this, partly sinceI'm not an active iOS user, while he is.)

![Image](https://user-images.githubusercontent.com/213678/235179094-b498f547-ed28-4dab-8454-95abd0110d83.png)

**Comment by siepra** [comment]
I think we should limit this change to iOS only as for Android users it's more intuitive to see this kind of things near the bottom edge of the screen

**Comment by EmiM** [comment]
@holmesworcester should the whole overlay/popup be in the center of the screen? Do I understand it correctly?
Tasks about visual changes should include designs or at least the draft, I also don't use iPhone so I don't know what "feels weird" or "feels right".

**Comment by holmesworcester** [comment]
Good point re designs. For this i left it out because I thought we could use the existing android app as a reference.

**Comment by holmesworcester** [comment]
https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-%2B-desktop-%2B-prototypes?node-id=1927%3A44738&t=1LNS0fo81TSR0rvG-1

There should be examples here

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1594 centered for ios

**Comment by kingalg** [comment]
v 1.4.0 - ios
It's centered as described. 
@holmesworcester I see that color of overlay is a different (Emilia didn't change it so it may be something in mobile settings?). Are you ok with darker overlay? If not, I will create a new task for handling color issue. 

![IMG_1384](https://github.com/TryQuiet/quiet/assets/68909168/bf7fd813-5966-436c-b68f-bd798a49c798)

**Comment by holmesworcester** [comment]
It seems ok

**Comment by kingalg** [comment]
Great, so it's done.
