### ISSUE TITLE
Message entry field grows wider with message

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1499]
Steps to reproduce on desktop:

1. Type a long message without a linebreak

Expected: line wraps
Actual: message field gets wider and messes up layout

![Image](https://user-images.githubusercontent.com/213678/235321380-6efc57c8-3747-484e-af3d-ee96d1884522.png)

**Comment by Kacper-RF** [comment]
https://user-images.githubusercontent.com/111343884/236788810-248031a4-ec33-4c84-b4f7-f2103ed7e843.mp4

**Comment by holmesworcester** [comment]
Is there an easy way to catch this with a test? Storybook?

**Comment by Kacper-RF** [comment]
I think Cypress test should catch this

**Comment by kingalg** [comment]
@holmesworcester looking at how the screen looks like it was on Linux, right?

**Comment by holmesworcester** [comment]
The screenshot of the bug that I took a the top of this issue was taken on Ubuntu, yes.

Is that what you mean ?

**Comment by kingalg** [comment]
Yes, I wanted to make sure. But I've checked it on all systems available to me (including Linux with Ubuntu distribution) and it looks like it's fixed. (Version: 1.2.1-alpha.3)
