### ISSUE TITLE
Move all shared interfaces to a separate package (models)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#152]
We're facing dependency-cycle problems from time to time. For example: We cannot use nectar's interfaces inside identity package and setting up the environment often fails on CI (https://github.com/ZbayApp/monorepo/runs/4865506209?check_suite_focus=true)

**Comment by holmesworcester** [comment]
@siepra is this still relevant?

**Comment by siepra** [comment]
No, we currently use state-manager for it
