### ISSUE TITLE
Deleting general channel does't work consistently

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1523]
Desktop: Version: 1.2.1-alpha.3
Mobile: mobile@1.2.1-alpha.6

System: ios and android
I didn't encounter it on desktop but @vinkabuki did. It also happen to me only for general but potentially it may happen for any channel.

What happens:
1. I had "owner" on desktop, two desktop users and two mobile users (ios and android).
2. Owner removed general. 
3. On all desktops general was successfully deleted. 
4. Both ios and android still have general - they both get the info that "xyz deleted all messages in #general") but old messages are there. You can see it below.

![Screenshot 2023-05-12 at 13 56 52](https://github.com/TryQuiet/quiet/assets/68909168/38c7ac15-6534-4dcd-b8db-ea4f15767ff3)

It doesn't happen every time as after several attempts I've deleted messages from general on mobile.

**Comment by Kacper-RF** [comment]
Pull request(draft) with a detailed list of subtasks:
https://github.com/TryQuiet/quiet/pull/1525

**Comment by holmesworcester** [comment]
@Kacper-RF some questions:

1. what happens in the new design if someone makes multiple channels with the same name?
2. what happens if two people do it simultaneously or maliciously 
3. is `channel.address` the right name for this? i think `address` is a legacy name from when we used Zcash and that we should just use `channel.id` or something else

**Comment by holmesworcester** [comment]
Okay.

So it will still be possible to create channels with duplicate names, because two clients can make changes that the other isn't aware of. What will happen in this case? We should have tests to make sure it works as expected.

**Comment by vinkabuki** [comment]
It's not clear for me what was the previous behavior of this, probably backend would throw exception, we never tested that and it never happened. this is super super edge case very very unlikely to happen. atm it will probably not throw exception but it will create two separate databases for the same channel and messages from both of those will be aggregated into one channel on frontend.

We have that case in mind ofc, but this is way less important and complicated than adding backward compatibility for channels after refactoring address to id

**Comment by holmesworcester** [comment]
We tested the previous behavior, as I remember. What would happen is that the newly created channel would simply be the same channel. It was weird but acceptable.

Let's write a test for this case to make sure nothing bad happens.

**Comment by kingalg** [comment]
On desktop it's working ok, but on mobile we are still having issues. They will be handled in separate issue: https://github.com/TryQuiet/quiet/issues/1550

**Comment by holmesworcester** [comment]
I'm still seeing multiple general channels on mobile in 1.3.0

**Comment by kingalg** [comment]
1.3.1 - fixed
