### ISSUE TITLE
Autoupdate to v. 1.2.1-alpha.7 on Windows sometimes fails

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1542]
Version - update from Quiet-1.2.0-alpha.30 to Quiet-1.2.1-alpha.7 (but potentially from other older versions as well)
System - Windows

Notes: we are unsure what are specific steps to reproduce it. It happened a few times on two different computers with Windows and @kingalg and @Kacper-RF witnessed it. 

What heppens - when updating Quiet on Windows to version Quiet-1.2.1-alpha.7.dmg sometimes we see white screen. Other times we get to a screen to join/create community and username even if there was already community and username before updating.

**Comment by vinkabuki** [comment]
I can't break it on the same machine

**Comment by kingalg** [comment]
I will try again today after I finish other tests. If I fail with braking it I suggest to close this one until we have more informations.

**Comment by siepra** [comment]
I'm closing as we're already after major 2 release
