### ISSUE TITLE
User is stuck on last step of registration

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1543]
Version: 1.2.1-alpha.7
System: Windows and Linux (it may happen on MacOS as well but so far we saw it only on those two systems)

Steps to recreate
1. Install version Version: 1.2.1-alpha.7
2. Sometimes user is stuck at the last step of registration (at least it looks like it on frontend). Other users see that this user is registered and user that is stuck can even get popups with new messages but it looks like he is still in registration process. Refreshing with F5 is working. 

@Kacper-RF could you add info about timing that is probably cause of an issue that we are facing here?

**Comment by holmesworcester** [comment]
@vinkabuki can you link this to the previous issue you mentioned?

**Comment by holmesworcester** [comment]
@Kacper-RF can you put your notes in this ticket?

**Comment by Kacper-RF** [comment]
Probably it's related to `LoadingModal.tsx` component, and problem that even if channels are replicated(i saw them from console log), one of the values returned from selector(`isCommunityInitialized?`) is still in not case that we expect to close that modal.
After refreshing by F5 community is correctly loaded

**Comment by kingalg** [comment]
Version: 1.10.0-alpha.0

This issue has been resolved in previous version.
