### ISSUE TITLE
Download buttons on webpage hidden sometimes

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1553]
This is an issue with the webpage but it's relevant to the app too.

For some screen sizes, the link https://tryquiet.org/#Downloads will not display the download button. See screenshot.  

![Image](https://github.com/TryQuiet/quiet/assets/213678/d88d60fd-ba85-4f5a-abfa-3169db48d15c)

We should move the name property so that it works right.

**Comment by holmesworcester** [comment]
I included a partial-but-acceptable fix for this here: https://github.com/TryQuiet/quiet/commit/4bfc0edce2b00d3fdd623f30dd77f60998e2bff8

**Comment by kingalg** [comment]
Fixed. Checked on Chrome, Firefox and Safari.
