### ISSUE TITLE
Delay after pasting invite code

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1554]
There's a weird delay on mobile after pasting the invite code. There shouldn't be, because we don't really need to *do* anything in this step except perhaps validate the code. 

Steps to reproduce:
1. Paste invite code to join new community

Expected: choose username screen displays immediately
Actual: there is a delay of several seconds

**Comment by vinkabuki** [comment]
That's not true, we do a lot of things at this step, hence adequate delay. Maybe it's possible to move HS private key and peerid generation to frontend.

**Comment by holmesworcester** [comment]
Why move it to frontend? 

Also why not move it to *after* the user creates a username since there's already a wait there? How hard would that be?

Or alternately we could create your first community HS and keys on startup.

**Comment by vinkabuki** [comment]
I've moved network creation to create username step, so it's kind of merging with waiting for certificate which is already very long so we basically have long delay + 2s which makes no difference from UX perspective

**Comment by kingalg** [comment]
v 1.4.0
Mobile

Now it moves immediately from joining community to registering username.
