### ISSUE TITLE
Register over OrbitDB

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1555]
As part of #1340 we are letting users join communities without registering. This lets us send the registration to the owner and receive a response asynchronously in public messages with attachments.

In our first implementation these can be public messages in the general channel. "User requested registration," e.g. and having this simplicity will help for debugging.

**Comment by vinkabuki** [comment]
putting those messages on general channel sounds like adding complexity to me, rather than simplicity, so we should use a separate db.

**Comment by holmesworcester** [comment]
Noted. Then yeah let's do it that way!

**Comment by EmiM** [comment]
Done as a part of https://github.com/TryQuiet/quiet/issues/1557
