### ISSUE TITLE
Remove connection authentication

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1556]
As part of #1340 we should remove connection authentication so that users can connect to the community's network immediately using one or more community onion addresses.

**Comment by vinkabuki** [comment]
To be exact: community members libp2p addresses.

**Comment by kingalg** [comment]
How can I test this and is there a visible impact for users?

**Comment by holmesworcester** [comment]
The main thing is that when all these changes are done, a user should be able to join without the owner being online.

There might be other visible impacts but they're all secondary and might be hard to see.

**Comment by EmiM** [comment]
Original PR: https://github.com/TryQuiet/quiet/pull/1671

Fix for regression, probably introduced while resolving conflicts with develop: https://github.com/TryQuiet/quiet/pull/1765

**Comment by kingalg** [comment]
Version: 2.0.1-alpha.7
mobile@2.0.0-alpha.21 (iOS 319)

Users can consistently join the app when the owner is offline.
