### ISSUE TITLE
Put multiple libp2p addresses in invite link

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1557]
As part of #1340 we should give invite codes as many onion addresses is practical, since the more URLs the greater the chances of connecting. We should put the owner and inviter first and then sort using the prioritization we currently have e.g. last-seen. 

For a limit, quickly figure out what the max URL size is that Whatsapp, Signal, and Gmail will linkify and pick a number that fits. IE had a 2048 character limit and would return an error, but it's been deprecated. 

We should behave gracefully if an onion address is truncated by some other app, just in case. A truncated final onion address should not cause an error.

**Comment by vinkabuki** [comment]
It's confusing, afaik we want to connect to community peers immediately and put a csr in orbitdb, right?

**Comment by vinkabuki** [comment]
This is also quite a lot of work as we have to change the joining/registration flow and all related events exchange.

**Comment by holmesworcester** [comment]
> It's confusing, afaik we want to connect to community peers immediately and put a csr in orbitdb, right?

Yes we want to try to connect to as many peers as we can, so that we succeed even if only one of them is online and reachable. 

This will also reduce the chances of having to retry to connect to someone, or of their onion address not being ready yet, because we will be connecting to multiple onion addresses.

**Comment by EmiM** [comment]
Checked URL size that will linkify for some of the apps. The number is the number of params' characters (after `https://tryquiet.org/?codes=`)

Whatsapp: 640 too many, 512 OK (**on mobile**). Desktop seems to not have restrictions - tested up to 2055
Signal: 640 too many, 512 OK
Google hangout: OK, tested up to 2055
Gmail: OK, tested up to 2055

Whatsapp and Signal are the most restrictive.

**Comment by holmesworcester** [comment]
Great research! 

How does it fail? Does the URL fail to open or linkify? Or does it truncate the URL when you open it? 

If we are designing this URL to still be valid when truncated (i.e. ignore a truncated onion address) can we just include a longer link because sometimes that works? Or do we have to limit our links to 512 for them to work in Whatsapp/Signal?

**Comment by EmiM** [comment]
Whatsapp and Signal just unlinkify params on receiver side if URL is too long:

![Screenshot_20230731-151321](https://github.com/TryQuiet/quiet/assets/6099829/634d9375-93a4-4566-8e06-cb2199af100b)
![Screenshot_20230731-150055](https://github.com/TryQuiet/quiet/assets/6099829/6fd93c97-e25f-41bb-9188-48c86309885f)

**Comment by EmiM** [comment]
Tried with fragment identifier (https://tryquiet.org/join/#aaaaaaaaa(...)) and without parameters (https://tryquiet.org/join/aaaaaaaaa(...)) and those were also not transformed into link on the receiving side.

**Comment by holmesworcester** [comment]
Yeah that should be fine. We'll just give people the new invite link, right?

**Comment by holmesworcester** [comment]
Old invite links not working is fine.

**Comment by EmiM** [comment]
```
onionAddress -> 56 characters
peerId -> 46
"=" -> 1
"&" -> 1
```
so each pair takes 104 characters. 
If we consider whatsapp and signal restrictions then we can only fit 4 or 5 addresses in URL

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1686

**Comment by holmesworcester** [comment]
Which addresses do we currently choose? Can you describe the criteria?

**Comment by EmiM** [comment]
Known issues (to be resolved in next iteration):
* invalid invitation code warning modal will not show right now (invalid code in deep link case)
* existing community will not have community metadata in db
* UI for invitation URL is not pretty (url can be very long)
* "The same url has been used to open an app (mobile)" case is temporarily (or forever) not handled because url can change often.

**Comment by holmesworcester** [comment]
What's the "same url" case?

**Comment by holmesworcester** [comment]
And is there a way we can add the community invite link to existing communities? Or is that done?

**Comment by EmiM** [comment]
> What's the "same url" case?

I think it was handled to redirect user to the proper screen if they already registered to the same community (because they have the same registration url in redux that they are trying to use).

> And is there a way we can add the community invite link to existing communities? Or is that done?

Invitation url is constructed from connected/most active peers so... it is done.

**Comment by EmiM** [comment]
We support being a member of only one community at the time. There is no need to check if we belong to THIS community. If we belong to any community user gets info that he already belongs somewhere so the invitation link cannot be used anyway.

Fix for invitation code format on website: https://github.com/TryQuiet/quiet/pull/1803

**Comment by kingalg** [comment]
Version: 2.0.1-alpha.7
Done.
