### ISSUE TITLE
Unregistered users should be obvious

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1558]
Unregistered users should have the note "Unregistered" next to their name

https://www.figma.com/file/TV9pF84Ob8pLYRLu83gNol/Joining-when-owner-is-offline?type=design&node-id=571-2124&mode=design&t=C8hfFvMP9S6qUm4E-4

![Image](https://github.com/TryQuiet/quiet/assets/213678/999aab88-4bec-4ccb-a1b9-c275535c84f4)

**Comment by Kacper-RF** [comment]
@holmesworcester I have one question - what if the user is unregistered and used a duplicate username, which label is more important in this case?

**Comment by holmesworcester** [comment]
Duplicate.

**Comment by kingalg** [comment]
Version: 2.0.0-alpha.12
System: Windows, MacOS, Linux

Unregistered users get "Unregistered" label and in case it's duplicated unregistered username they get "Duplicate".

There is a bug and system messages sometimes shows as "Unregistered" - it's part of the issue https://github.com/TryQuiet/quiet/issues/1842 to be handled in current sprint.

<img width="425" alt="Screenshot 2023-09-21 at 11 21 59" src="https://github.com/TryQuiet/quiet/assets/68909168/2f84c1af-e0b2-48ca-a38f-459aea077926">

User can click on "Unregistered" label and get more details.

<img width="581" alt="Screenshot 2023-09-21 at 11 26 09" src="https://github.com/TryQuiet/quiet/assets/68909168/f156f745-24c2-4409-8e02-7f7f228a5129">

Issue will be closed **after mobile versions are ready and check**
