### ISSUE TITLE
Warn user of duplicate unregistered names

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1559]
As part of #1340 we are letting unregistered users send messages. We should use these designs to warn users if an unregistered user has the same name as a registered user **or** as another unregistered user: 

In the message screen, all duplicate usernames should have a "duplicate" warning:

https://www.figma.com/file/TV9pF84Ob8pLYRLu83gNol/Joining-when-owner-is-offline?type=design&node-id=311-7523&mode=design&t=eS9WDLYpQNod1Acl-4

![Image](https://github.com/TryQuiet/quiet/assets/213678/d92202e5-8b11-43ad-a1a4-caeebf320e17)

Tapping on this warning should take users to an explanation and warning:

https://www.figma.com/file/TV9pF84Ob8pLYRLu83gNol/Joining-when-owner-is-offline?type=design&node-id=320-2662&mode=design&t=eS9WDLYpQNod1Acl-4

![Image](https://github.com/TryQuiet/quiet/assets/213678/ee795120-8229-4c96-a471-f4d6d5ef64ca)

**Comment by kingalg** [comment]
@holmesworcester this issue is about unregistered user having the same username as registered user. Is it also possible that two unregistered users will have the same names? I can't find issue for this and I was thinking if this is technically possible or not?

**Comment by holmesworcester** [comment]
It's definitely possible. Unregistered users having the same name can be handled with the same warning as registered/unregistered.

**Comment by kingalg** [comment]
quiet@2.0.3-alpha.0

Done on Desktop and Mobile. All issues discovered in this area has been reported in separate github issues.
