### ISSUE TITLE
New/unread message indicator sometimes missing

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1565]
1.3.1 - android and iOS (I saw it in earlier versions as well, so this is not the one that introduced this issue). 

Sometimes when the user is on channel list view and new message appear on general channel "new" icon is missing. User gets the message, channel is moved to the top, notification is received as it's suppose to be nut "new" is missing.

It can happen on both systems and so far I didn't catch a straight way to reproduce it. Below you can see one example of when it happened:
1. iOS - installed 30 minutes earlier, several channels (including general) removed, Android - freshly installed, no channels removed yet. 
2. Both in channel list view. 
3. General channel removed (correctly)
4. iOS - there is “new” icon, Android - “new” icon missing

Missing icon mostly happens for system messages (like new user or deleted channel) but I also saw it for regular message on general channel.

**Comment by holmesworcester** [comment]
I don't think this should block release since it's likely an existing issue.

**Comment by kingalg** [comment]
@holmesworcester I agree, I've added it to the backlog, we should have a look at this one day but it's definitely not a blocker.

**Comment by holmesworcester** [comment]
Update: this is happening to me on desktop too. Steps to reproduce:

1. Go to general channel on desktop Quiet 1.4.0
2. Send message from mobile Quiet 1.3.1 to channel "test"

Expected: notification arrives and highlight appears on channel name showing new message, and message is visible when I click on channel.

Actual: notification arrives, but no white highlight appears indicating new messages in that channel. Message is visible when I click on channel though.

Not creating a separate issue because I assume it's the same issue or related.

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1653

**Comment by kingalg** [comment]
@Kacper-RF can you add some short explanation with why we had this issue and in what way your fix resolves the problem? I didn't encounter this issue on desktop, as Holmes did, so I want to be sure that I understand what was happening to test it and try to "break" it in the future.

I'm currently in a **version: 2.0.0-alpha.3** and from my perspective everything looks fine on **all desktop and mobile** systems.

**Comment by Kacper-RF** [comment]
Probably problem was in Redux state, that user somehow had `undefined` property in `joinTimestamp` filed which was required to mark message as new.

Now it is secured and even if the user has `undefined`, this field is validated and in this case the current timestamp is saved

**Comment by kingalg** [comment]
Version: 2.0.1-alpha.7

I didn't observe this issue for a long time so I consider this fix to be working.
