### ISSUE TITLE
Registration when username is already taken is bugged

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1579]
Version: 1.3.1-alpha.0
System - not related to the specific system

Steps to reproduce:
1. Have one Quiet opened 
2. Join with other Quiet and try to register the same username that already exist in this community
What should happen - user that tries to join should get a message that this username is already taken.
What happen - user that tries to join is stuck on "joining now!" screen. Host see that he tries to join and register that this username is taken (see screen below) but there is no indication in the logs on joining user side that this information get to the joining user. 

<img width="900" alt="Zrzut ekranu 2023-06-16 o 12 37 47" src="https://github.com/TryQuiet/quiet/assets/68909168/98f454ed-31b5-49b5-beee-c83011089982">

**Comment by holmesworcester** [comment]
Moved to sprint, since this affects new users. 

Fix should include an e2e test.

**Comment by kingalg** [comment]
Fixed.
