### ISSUE TITLE
White screen on joining (1.2.0 - latest in play store)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1614]
Steps to reproduce, Android 13, Pixel 6:

- Join our community using the invite link
- Register a username

Expected: it works
Actual: you get a white screen

I'm not sure if 1.2.0 is supposed to be our latest release (what happened to 1.3.0?) but I've had this report from multiple users and just experienced it myself when doing a fresh install of the production release.

@kingalg at the very least, we need to add "Fresh install of production app from Play Store" to our QA flow, after each release. I think this has been happening for a *while*.

**Comment by vinkabuki** [comment]
just to be sure: you were joining from 1.2.0 to 1.2.0, right?

**Comment by holmesworcester** [comment]
This is resolved by the release
