### ISSUE TITLE
(iOS) app crashes when coming back to foreground in mature community

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1615]
Steps to reproduce:
1. Install the app
2. Join mature community (eg. Quiet official one)
3. Send a message
4. Lock the phone
5. Unlock the phone

Expected behavior:
App displays splash screen and after a while it becomes operate

Actual behavior:
App crashes and minimizes

Version
TestFlight 1.4.1 (278)

**Comment by siepra** [comment]
Can we include an e2e test as a part of the solution?

**Comment by siepra** [comment]
Here is how to debug iOS app ready for submission https://developer.apple.com/library/archive/qa/qa1764/_index.html

**Comment by siepra** [comment]
This was probably fixed by https://github.com/TryQuiet/quiet/pull/1619

**Comment by siepra** [comment]
I added an e2e Detox test for minimizing and bringing back the app https://github.com/TryQuiet/quiet/pull/1623

**Comment by kingalg** [comment]
Version: 1.8.0
System: iOS

I went through steps mentioned in initial description of this issue (I've joined our community with user test310723) and it immediately crasher. App crashed several times during testing if it can go to backround and be bring back smoothly.

Note: as described, it happen only in mature community. Doing the same with two different iOS devices on fresh community and 2-weeks old community didn't crash the app.

@holmesworcester as Wiktor is on holiday, should someone else take care of this issue or we are going to wait for Wiktor?

**Comment by holmesworcester** [comment]
@Kacper-RF @EmiM this is up to you.

**Comment by Kacper-RF** [comment]
I think we'll focus first on tasks that have a more clear fix path, this one requires specific criteria like a more mature community, so is more harder to debug

**Comment by holmesworcester** [comment]
Let's consider this one blocked until wiktor returns then

**Comment by kingalg** [comment]
To be check on  15.01.24 in our team community once it'll be more "mature".

**Comment by kingalg** [comment]
App does not crash but it's not syncing until it's fully restarted (swiped up and opened again). @siepra do you consider this separate issue or is this still connected?

**Comment by kingalg** [comment]
mobile@2.1.1-alpha.0 | iOS 350

The initial issue is resolved, so I'm closing it.
