### ISSUE TITLE
(iOS) UI not responsible after coming back to foreground if user has left community before joining the current one

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1616]
Steps to reproduce:
1. Install the app
2. Join/create community
3. Leave community
4. Join/create community
5. Send message
6. Lock the phone
7. Unlock the phone

Expected behavior:
App displays splash screen and after a while it becomes operate

Actual behavior:
UI stops being responsive (user can see channels list but can't enter any)
After a while the app crashes and minimizes

Version:
TestFlight 1.4.1(278)

**Comment by siepra** [comment]
Can we include an e2e test as a part of the solution?

**Comment by siepra** [comment]
The problem was redux persist store has been clearing multiple times (due to hooking on a websocket lifecycle event)

**Comment by siepra** [comment]
Unfortunately, there's no way to write unit test for saga responsible of this behavior as it'd be too trivial and I'd not actually check anything.

Also RNTL tests are not effective enough as the logic to put under tests is app-wide (it includes both frontend, backend and native lifecycle events handling)

I'm learning bout ways to enhance Detox tests somehow in order to achieve satisfying test results

**Comment by siepra** [comment]
I added an e2e Detox test for minimizing and bringing back the app https://github.com/TryQuiet/quiet/pull/1623

**Comment by siepra** [comment]
Previously we observed the app kept displaying joining screen after coming back to foreground. We thought we solved the problem when this behavior stopped appearing but in fact, it only covered the deeper hidden issue.

Here are the logs from one of the runs:
```
2023-07-18 11:18:36.795845+0200 Quiet[818:132586] [javascript] Flushing redux store
2023-07-18 11:18:36.805173+0200 Quiet[818:132586] [javascript] [TypeError: undefined is not an object (evaluating 'state.entities')]
2023-07-18 11:18:36.806056+0200 Quiet[818:132586] [javascript] The above error occurred in task anonymous
    created by anonymous
    created by takeEvery(channel, )
    created by handleActions
    created by handleActions
    created by useIO
    created by useIO
    created by useIO
    created by setConnectedSaga
    created by takeEvery(Init/setWebsocketConnected, setConnectedSaga)
    created by startConnectionSaga
    created by takeLeading(Init/startWebsocketConnection, startConnectionSaga)
    created by initMasterSaga
    created by initMasterSaga
    created by initMasterSaga
    created by takeEvery(Init/setStoreReady, initMasterSaga)
    created by rootSaga
    created by rootSaga
    created by rootSaga
Tasks cancelled due to error:
takeEvery(channel, )
takeEvery(Init/suspendWebsocketConnection, cancelRootTaskSaga)
takeEvery(Init/setWebsocketConnected, setConnectedSaga)
setConnectedSaga
setConnectedSaga
handleSocketLifecycleActions
takeEvery(Init/setStoreReady, initMasterSaga)
2023-07-18 11:18:36.816629+0200 Quiet[818:132586] [javascript] closing socket connection
```

Interesting thing is most of them are multiplicand (3 times in this case)

**Comment by kingalg** [comment]
Version 1.8.0
System: IOS

I wen't through those steps on two different IPhones several times.
1. Install the app
2. Join/create community
3. Leave community
4. Join/create community
5. Send message
6. Lock the phone
7. Unlock the phone

Result are slightly different than initially but it's still bugged.
UI stops being responsive (user can see channels list but can't enter any) - user see channel list but is unable to do anything because after short time (1-3 seconds) the app crashes and minimizes.

**Comment by siepra** [comment]
Those are separate issues

**Comment by kingalg** [comment]
Great, so this one should be closed.
