### ISSUE TITLE
Messages sent to #general after bringing app to foreground are appearing greyed-out

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1624]
It only affects #general channel.
A following Detox e2e test revealed that https://github.com/TryQuiet/quiet/pull/1623

**Comment by vinkabuki** [comment]
It's because we do not wait for services to initialize, once socketio is connected we allow user to perform actions in the app, so it's possible to send message before storage service is initialized, hence greyed out message, because it's never added to db

**Comment by kingalg** [comment]
Version: 1.8.0
Systeem: iOS

Fixed
(this one still remains a problem: https://github.com/TryQuiet/quiet/issues/1677)
