### ISSUE TITLE
UI unresponsive after switching to homescreen and back

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1633]
Steps to reproduce in quiet version 1.4.2 on 1st gen iPhone SE:

1. Open Quiet in our test community
2. Switch to message list and then back to channel list 
3. Press home button to switch to home screen
4. Tap Quiet icon on home screen to return to Quiet
5. Switch from channel list to message list

Expected: message list opens 
Actual: message list doesn't open. 

I can scroll whatever list I'm on but I can't navigate between different screens in the app after returning to the app from the home screen, unless the app crashes and restarts, which sometimes happens.

@siepra I think the most important thing here is if you can confirm that you can reproduce this. 

If you can't reproduce it, you might want to try a lower spec phone, like an iPhone 6, 7, or 8.

**Comment by holmesworcester** [comment]
I was also able to successfully return to the app, send a message immediately once I was able to, and get the message in a "greyed out" state that did not resolve even after several minutes.

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/issues/1624

**Comment by vinkabuki** [comment]
for the first two we must look closer at services bootstrap, especially tor.

**Comment by holmesworcester** [comment]
It's 1.4.2

**Comment by holmesworcester** [comment]
I think this is a duplicate and fixed in 1.5.x
