### ISSUE TITLE
"Powered by React Native" splash screen (iOS)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1639]
The iOS app still shows a default React Native splash screen instead of e.g. a Quiet logo. We should fix this. 

e.g. https://www.codementor.io/@blessingoraz/changing-default-splash-screen-in-react-native-9y2wy580l#comment-bwvg85wqx

**Comment by siepra** [comment]
We'll need a separate issue for Android

**Comment by siepra** [comment]
![Uploading Zrzut ekranu 2023-09-19 o 15.52.28.png…]()

**Comment by siepra** [comment]
<img width="456" alt="Zrzut ekranu 2023-09-19 o 15 52 28" src="https://github.com/TryQuiet/quiet/assets/15381135/5923ff1c-5814-4bc4-9dcd-12b3891183e0">

**Comment by siepra** [comment]
https://github.com/TryQuiet/quiet/pull/1834

**Comment by siepra** [comment]
Here is a corresponding issue for Android https://github.com/TryQuiet/quiet/issues/1835

**Comment by kingalg** [comment]
mobile@2.0.1-alpha.7 (iOS 325)
Platform: iOS

Fixed.

![4972FD6F-19A8-4F86-9967-6C6D2B1977C3](https://github.com/TryQuiet/quiet/assets/68909168/1eaa5ff3-22d9-4482-9521-bd124cd669b1)
