### ISSUE TITLE
Can't send messages after quickly unlocking phone

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1645]
Steps to reproduce in iOS, version 1.5.0 on an iPhone SE 1st gen:

1. Join a community and confirm messages are being sent/received
2. Wait until screen locks due to inactivity and *immediately* unlock.
3. Send messages

Expected: messages are sent or not lost, or app restarts 
Actual: The app doesn't restart, I can type messages and send them, but they disappear, go nowhere, and are lost. If I go back to channel list I see a white screen. 

It appears that the backend is unreachable but the frontend doesn't know it.

**Comment by holmesworcester** [comment]
Question: does the frontend independently observe whether or not the backend is reachable? For example, can it ping for a response just to make sure the backend is alive, so that it can indicate to the user that it is not, or restart the backend? 

This seems like good defensive coding because if the backend is a separate process there may be cases where the backend dies and the frontend did not die.

**Comment by vinkabuki** [comment]
Let's make it clear:
Messages greyed out - backend dead
Messages not appearing - frontend dead

**Comment by siepra** [comment]
@holmesworcester Is this issue still accurate? I think this https://github.com/TryQuiet/quiet/pull/1619 was the solution
