### ISSUE TITLE
Invite users to click and see an explanation what's happening during joining process

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#1648]
@holmesworcester needs designs

**Comment by holmesworcester** [comment]
Can you add more detail to this?

**Comment by holmesworcester** [comment]
Me neither. Was created by bartek without enough detail. Moving to blocked.

**Comment by vinkabuki** [comment]
Me neither actually, I've just copied and pasted it from #1340 as it sounded to me a candidate to separate task.

**Comment by holmesworcester** [comment]
Closing
