### ISSUE TITLE
User should be able to tap/click on "unregistered"  label to learn what it means

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#1649]
When we let users join without the community owner being online, we label users who are not registered  with an "unregistered" label so that it's clear their names are not final yet. 

Users should be able to click or tap on this label to see an explanation of what it means. Designs:

https://www.figma.com/file/TV9pF84Ob8pLYRLu83gNol/Joining-when-owner-is-offline?type=design&node-id=311-5980&mode=design&t=zJWpEmDpd1LSWwEO-4

![Image](https://github.com/TryQuiet/quiet/assets/213678/f089b23b-b64c-491b-af2a-ef089a7b7691)

**Comment by kingalg** [comment]
@holmesworcester @vinkabuki - could you please provide some designs and more detailed description?

**Comment by holmesworcester** [comment]
I didn't create this issue so I'm actually not sure what is meant here. I think this was created when we split the epic and it's based on the designs, but because there's no description I don't know what it means :)

We need to add a few lines of issue description even if it seems obvious!

Moving to 'blocked'

**Comment by vinkabuki** [comment]
It was just copy-pasted from #1340, so I also didn't know details.

**Comment by kingalg** [comment]
Version: 2.0.0-alpha.12
System: Windows, MacOS, Linux

User is able to click on "unregistered" to get details. 
Inside popup "OK" and X (close) buttons are working.

<img width="798" alt="Screenshot 2023-09-21 at 11 51 00" src="https://github.com/TryQuiet/quiet/assets/68909168/142a0735-ac7d-4452-97b9-e843521ff501">

Issue can be closed after **checking this on mobiles** that are not yet ready.

**Comment by kingalg** [comment]
mobile@2.0.1-alpha.7 (iOS 325)
System: android and ios

Button works correctly on mobile devices. I'm not sure about matching design. Is the one on figma intended to cover half of the screen and our implementation is wrong or what we did is correct? @holmesworcester 
Our implementation:
<img width="328" alt="Screenshot 2023-10-17 at 12 47 15" src="https://github.com/TryQuiet/quiet/assets/68909168/9a2cadc6-76f6-4230-bfd8-0db42c51e31d">
Figma design:
<img width="258" alt="Screenshot 2023-10-17 at 12 48 18" src="https://github.com/TryQuiet/quiet/assets/68909168/eaacc2bb-43b6-4985-8df9-9664d547c73d">

**Comment by holmesworcester** [comment]
The figma version is correct. We have an animated drawer that animates up from the bottom of the screen that we use for settings. It should use this.

**Comment by kingalg** [comment]
@vinkabuki @Kacper-RF which of you did work on that? Could you take this back and correct it according to figma design? (FYI - buttons are working correctly).

**Comment by Kacper-RF** [comment]
I'll take care of it

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1985

![image](https://github.com/TryQuiet/quiet/assets/111343884/f2608e7a-db3b-43be-b57f-2cc60a558a6b)

**Comment by siepra** [comment]
This design is bad. It's hard to read, spacings are inconsistent and the button is definitely too small

**Comment by kingalg** [comment]
It's still a little different then in designs - there is a break between sentences. I think that with break it's better but still - not like in designs. Below you can see screen from IOS. @holmesworcester do you accept this version?

![2C141478-56CF-4101-A7A5-D3DEB02D1275](https://github.com/TryQuiet/quiet/assets/68909168/b478b1d6-93f7-451e-995a-7386c0ec7ab7)

**Comment by holmesworcester** [comment]
Let's stick to the designs. These small things add up.

The two differences I see are the line break and the style of the button.

**Comment by siepra** [comment]
And why is Figma better? Once we add it we'll never correct it so let's not rush and make it look good instead of forcing some obviously bad design just because it's like that on Figma

**Comment by kingalg** [comment]
mobile@2.0.3-alpha.6 (iOS 333)

Now it's matching figma design.
