### ISSUE TITLE
Add e2e tests for 'registrar-offline' joining flow

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#1650]
Not sure what you had in mind here @vinkabuki but I added details in a comment...

**Comment by holmesworcester** [comment]
Can we do three-player tests? If so, I think this would be:

1. Alice creates community and invites Bob
2. Bob joins
3. Alice goes offline
4. Bob invites Carol
5. Carol joins, and appears as "unregsitered"
6. Alice joins, and Carol is registered. "Unregistered" flag goes away.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1826

**Comment by holmesworcester** [comment]
This is good to merge @EmiM
