### ISSUE TITLE
Touch target on back button is too small

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1654]
Right now when tapping the "back" (back arrow) button to return to the channel list from the message list, I often don't tap within the area and it appears that the app is not working correctly. The problem is especially noticeable on an iPhone SE 1st gen, but also happens on a much larger Pixel 7.

It's common for touch targets to be larger than their respective button.

We should make it as large as is reasonable.

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1669
