### ISSUE TITLE
Make Tor startup non-blocking (if it gives us >2x speedup)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1656]
Depending on the result of profiling in #1655 we should make Tor startup non-blocking, to improve backend restart time on iOS.

This change will improve startup time on all platforms. 

Note: if we can, we should still show Tor startup and connection progress when joining communities, if Tor has not yet completed starting up and connecting. Once Tor is connected we would show "registering username" and other steps in the joining process.

**Comment by Kacper-RF** [comment]
We decided on our internal meeting to not merging these changes with asynchronous Tor startup, as it does not help with the main goal of the sprint, which is to launch iOS app faster and will prevent further bugs from this layer.

**Comment by Kacper-RF** [comment]
I would say that we don't want to provide that changes if they not correspond with actual goal, as You suggested yesterday, and we discussed one more time about this today morning.

**Comment by holmesworcester** [comment]
Makes sense. We can do a subsequent release right after and QA this work separately from everything else.

**Comment by Kacper-RF** [comment]
@holmesworcester 

Screen with Tor bootstraping progress has been deleted. I added small icon with Tor status in sidebar to inform user what is current status of Tor (I can remove it if you want, but it was helpful in the development process ).

I think we can move Tor progress info to joining screen(for joining user) as You suggested on last weekly.

2 videos - creating community and restarting app: 




https://github.com/TryQuiet/quiet/assets/111343884/26b3ee8c-358f-42f6-afdd-4b121f6147d1



https://github.com/TryQuiet/quiet/assets/111343884/f60a723c-93f0-4d65-96c6-75026d80afd9

**Comment by holmesworcester** [comment]
Can't see these videos in the GitHub app.

I think we should start using loom or similar for screencasts since there are some issues with putting videos directly in issues.

**Comment by Kacper-RF** [comment]
That's strange, even if you check from a standard browser like Chrome?

**Comment by holmesworcester** [comment]
@Kacper-RF can you make me a list of the different kinds of status so I can work on it with Jason?

For example, which of these states do we have?
* No internet
* Problem with Tor connecting
* Tor connecting progress
* Joining community
* Downloading channel data

etc.?

And what information do you want to have access to, associated with these? 

Related: #1673

**Comment by Kacper-RF** [comment]
I think in more simpler way, mostly in the form of a list that Wiktor wrote.

Tor status  = connected/disconnected, 
Websocket = connected/disconnected
Community initialized =  true/false

Tor bootstrapping status we can move to joining screen for user which is currently joining to community. 

Joining community - it's a joining process with progress bar and downloading (some) channel data is included, like very first messages to not showing user empty channel 

In general, i added this tor status because me as a user need that information, so maybe is worthy consider to do a little research with other users of Quiet which information will be helpful for them ?

**Comment by holmesworcester** [comment]
What does community initialized mean?

**Comment by holmesworcester** [comment]
@Kacper-RF so I talked about this with Jason and I think we're going to put an item in the Settings section where you can get to "Network status" and we're going to have a shortcut to it that can show some visible loading indicator if it's actively loading or connecting, or some alert indicator if something is wrong or if you're not connected to any peers. 

But once you click to this screen it will be a simple list of keys and values and we can put whatever we think is helpful here, and it will be easy to change because it's just text.

**Comment by Kacper-RF** [comment]
Sounds good to me !

**Comment by holmesworcester** [comment]
Let's track this in the other issue. We haven't finalized the design yet.

For releasing this, the important thing is that the Tor indicator as designed by kacper only appears in dev builds (for debug purposes) and not in production.

**Comment by kingalg** [comment]
Version: 1.9.0-alpha.0

Done and working. This change did not impact ios. The rest of the systems are checked.
