### ISSUE TITLE
User should be able to navigate app immediately

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1657]
On iOS, backend restart is blocking access to the app. To the extent that we can let users into the app and let them do things before the backend is started, we should do this. 

We can disable functionality (like greying out the send button) if that functionality is not available yet. 

We should avoid adding more logic or state to the frontend than exists already. Ideally we can make the backend become available in a few seconds, so this intermediate state shouldn't be so important.

It's most important to do this for returning users, but if it's just as easy to make it work for first time users (join/create screens) let's do that too. 

It's most important to do this on iOS, but if it naturally affects and improves startup time on all platforms, let's do that too.

**Comment by kingalg** [comment]
Version: 2.0.0-alpha.3
It looks quite good right now but we are still working on some details related to opening application in other issues.
