### ISSUE TITLE
User should be able to compose messages immediately

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1658]
Right now there is some lag where the backend takes time to restart, on iOS, and users cannot enter the app and send messages. 

In #1657 we let the user into the app to navigate messages, but they cannot send messages, because the backend is not ready to receive them. 

Let's add a message queue so that users can compose and queue messages for sending before the backend is alive. Messages should be greyed out until sent.

**Comment by siepra** [comment]
Related to https://github.com/TryQuiet/quiet/issues/1677

**Comment by holmesworcester** [comment]
Will we try to make a queue on the frontend side as described in the issue? Or will we start some part of the backend quickly enough to be able to send messages almost immediately? My memory of our decision is that we decided to do the latter. Double checking if this is true.

**Comment by leblowl** [comment]
@holmesworcester In general, I think it's very easy to start a minimal version of the backend just as quickly as the frontend (starting a http server is very quick). We can then queue things on the backend via LevelDB (or alternative) if needed.

**Comment by kingalg** [comment]
Version: 2.0.1-alpha.7
