### ISSUE TITLE
Send button disappears, can't send message

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1678]
Steps to reproduce on 1st gen iPhone SE:

1. Type text into field and keep typing until it wraps multiple lines

Expected: text wraps, send button visible
Actual: text field grows, send button disappears

We should have a visual regression test (ideally) or e2e test to catch things like this.

**Comment by holmesworcester** [comment]
@Kacper-RF @EmiM this is something we can do while the others are out, right?

**Comment by Kacper-RF** [comment]
I can reproduce that error so we should fix it.

**Comment by holmesworcester** [comment]
Do we have tests for mobile that are capable of catching this kind of problem?

**Comment by Kacper-RF** [comment]
I will check if we have tests that can prevent this bug

![Image](https://github.com/TryQuiet/quiet/assets/111343884/f8ead383-af34-41a9-9593-cd4e5920b66b)

![Image](https://github.com/TryQuiet/quiet/assets/111343884/ca18b819-37c2-4edc-80d4-04f6dec79be4)

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1683

**Comment by kingalg** [comment]
v 1.8.1

Fixed.
![4B10D998-AFE4-4227-9824-B79694690162](https://github.com/TryQuiet/quiet/assets/68909168/b0ff368b-3b27-4fb5-a7df-c44f9a4e8196)
