### ISSUE TITLE
Big files download is bugged

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1684]
Version: 1.5.0
System:  all on desktop

**Description:**  
Big files download is bugged, user can't download full file.

**How it was discovered:**
- I've discovered it while checking issue https://github.com/TryQuiet/quiet/issues/836 (User should be able to send a file on mobile). Everything looked good with gifs, pictures and ~20MB files but when I've tried to upload bigger file (200 MB) on mobile and download it on desktop Quiet it stopped after downloading few percent of the file. 
- Initially I thought that something is wrong with upload on mobile so I've tried to send file similar in size from desktop to desktop. Result was the same for each platform that I've tried.

**More detailed description:**
- buttons for downloading and cancelling are working
- at the beginning (first few % of the file) everything looks as expected
- after reaching few % (for me ot was between 1%-13%) download stops and does not resume by it's own
- after restarting Quiet with active downloading it resumes as it should but again stops after reaching few %
- logs to which I have an access doesn't provide any additional information but @EmiM has some backend logs that may be helpful and she will add them to this issue

**Steps to recreate:**
- try to send any file that doesn't download automatically (for example 50MB) 
**Expected**: you can download the file.
**Curren**t: download stops after reaching few percent and does not resume

**Success criteria**

If a fix isn't straightforward, we can mitigate it by limiting file size for now.

**Comment by kingalg** [comment]
@holmesworcester - @EmiM had a look at this issue (I initially let her know as I thought that it's connected with her working on upload on mobile) but it's more of @vinkabuki territory and it will require quite a lot of Emi time to learn what he already knows. We can either dedicate Emi time or wait 1,5 week for vinkabuki to return.

**Comment by holmesworcester** [comment]
It's disappointing that our tests didn't catch this. @EmiM do we have a release where the tests are passing? Is this a regression? 

Agreed that bartek should fix the bug.

**Comment by EmiM** [comment]
@vinkabuki added some logs, not sure if they will be helpful. It's not that downloading is stuck, it's just **extremely** slow and I can see quite a lot `this.ipfs.block.get` ('COULD NOT FETCH BLOCK' log below) timeouts. May it be just a tor issue?
```
backend:IpfsFileManagerService updateTransferSpeed +89ms
  backend:IpfsFileManagerService processedBlocks 74 +0ms
  backend:IpfsFileManagerService uniqueProcessedBlocks 74 +0ms
  backend:IpfsFileManagerService updateTransferSpeed totalBytesDownloaded 18613809 +0ms
  backend:IpfsFileManagerService updateTransferSpeed fileState QmSnneRXwgc7qzyg5H14VUM57CRzx7UJTBGtrKaXmnw6jM. 18613809/55215635 +0ms
  backend:IpfsFileManagerService updateStatus QmSnneRXwgc7qzyg5H14VUM57CRzx7UJTBGtrKaXmnw6jM downloading +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK Qmdxxvu5MAmxvcemJBKKHWKFE77BPBRusuqhEFTyeT2fcN +144ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmPajp2bxnnV1GnNiY9GCi39TF886VUxgk34NtUUCyZU4n +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmcbM8KPin8iJ7odeS8qZhYhHM18Kmohn6LhyFfBNTq88j +400ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmbkYNTwJ2GRXbPiiytd4ffYZXzL34HdQmwtqdXM1Mzk3r +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmUDKd8sy36LNhAd7zWGwpN1YGhtWWz4qZHpKMqbnHtHHp +39ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock Qmc2MDPRZYZdLeGxFhiCH8YqssY1sWpXWADgo7QnFqqmD8 +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmbZmWWZtBDNTsqPXUmH8ferDDKU696j7FrTtqsodZqG8E +0ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmQkjHCXtsCDXbRP5c9YckM6VdDSR3UPXarxASjccKoRSs +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmNRQGvka1KxgVALgFDurVaU6i7er8ZfjCHmz8uaER1Nax +1ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmNSa3SrvZxUMAfXQjoDEBzHJyASVDGmCEErHoncotdrVm +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmdYg7KQsePtyLsb62KM3NfGffNPeXcBYTz6hDqyikmdAG +2ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmTPuLgG87dRm6RxfZEq8x54AeoeRLYATrgXb2AH6k8id4 +0ms
backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmP4rqakYYwp8HA1kMwmFCEZVNAEyNgDqyA4NGMAPYt8ZF +2ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmPwApu23L1J6zL89t68f3YU5TeZTTwdyq9s6MANyhygUZ +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmRbJagjPjuZWjMu8deMw1n3Wipp2bBNtuH8RLCdZTzsR5 +2ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock Qmb9Bc4LAiDhQn99wGcamwL7NW1PQ9CteGrEzoJXbq9foq +1ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmXaPajTXcpyHeHZaBUqw3kkkQByfzGo65UMPDvY48o9hc +2ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmRac4SdMk3vQHh3xQQ4UqnQRR4vJiPUosPP1dkhFZ1soP +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK Qme7dmujtnBEZ9uWMaDfWsZDME6pFaraZSWi21ADoKvXLW +1ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmSMHNEBBEnsE9kzkrtcGx13ybuqcq7Gp53zK4jfxA4sWe +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmZ7Jwhfeex3WRZMmqcyK8QRQqcrCQQM4n4kXviQL2EtCy +4ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmXGN21bvA8DfPndjbqwLeW9akXSM795UuY9KosaZTrdG7 +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmeG5RiDwd43TbhXYTJxaQX1GHsNFZVjtLAaE3qPTtcVHF +1ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmfWjgwnJqVKn37VrVhAcvdjuHBJnJBQkGwHzSv69VPaBk +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmcMkLJ6Jxm1NyXVMiyB8QHav6N7WGYBvGjCtADT4GxDGc +1ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock Qmd4fCT18UmByPezUcgFvwqg99BpQy2MrBTh1HeGsQtkJU +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmXybnNPvW1ji2YFFjvNvHmofjbqUsENR5wxpBXWRBXpKx +1ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmbzDLBTR8hugGANNaYJUoeDnFTdhwTzUCiisjwFWeVTMk +0ms
  backend:IpfsFileManagerService COULD NOT FETCH BLOCK QmV1QZ9WxSPQ9YvMgBinc7Z8QY174D4hpm8yorxuDWYNPh +0ms
  backend:IpfsFileManagerService downloadBlocks fileMetadata addToQueue link screen-20230717-220304 +0ms
  backend:IpfsFileManagerService processBlock QmbUjFdtrMDZM2ueU5aeQnFJZZe1LjLySviAtKqVLFmUYe +0ms
  backend:IpfsFileManagerService updateTransferSpeed +398ms
  backend:IpfsFileManagerService processedBlocks 74 +0ms
  backend:IpfsFileManagerService uniqueProcessedBlocks 74 +0ms
  backend:IpfsFileManagerService updateTransferSpeed totalBytesDownloaded 18613809 +0ms
  backend:IpfsFileManagerService updateTransferSpeed fileState QmSnneRXwgc7qzyg5H14VUM57CRzx7UJTBGtrKaXmnw6jM. 18613809/55215635 +0ms
  backend:IpfsFileManagerService updateStatus QmSnneRXwgc7qzyg5H14VUM57CRzx7UJTBGtrKaXmnw6jM downloading +0ms
```

**Comment by holmesworcester** [comment]
Regarding our tests though, did our tests pass because it completes slowly and our tests give a very generous time to complete? Does this test run on every PR? The first thing I want to nail down is why Kinga discovered this issue instead of it being discovered by our tests. 

Maybe it's a Tor network conditions thing that didn't emerge until after we gave the build to Kinga? Is it affecting any other reliability in Quiet?

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/issues/1641

We did not have tests for sending and receiving large files.

Note for Bartek: I left Quiets opened and when I opened (woke up) my laptop, the file (52MB) finished downloading within 15 seconds.

**Comment by leblowl** [comment]
I am noticing the same thing, even with a 3 minute long timeout, it just fails to download blocks. On my system it looks like it downloads a couple blocks and then gets clogged up. When I set the queue concurrency down to 1, it seems like it's working. I'm not entirely sure how the queue concurrency works with pqueue, since JS is single threaded, but if it's running each promise which sends a request via the network and not waiting for the promise to resolve before running the next one, then perhaps with concurrency 40, we might have up to 40 simultaneous requests. Perhaps some piece in the stack can't handle that many concurrent requests. I am also noticing that when it gets clogged up, the uploader cannot send messages any more, like I type a message into the input box but it never shows up. Seems to not be able to receive messages either. The downloader can still send messages it seems, but the uploader doesn't receive them. Not sure where the issue is exactly, but it does seem to work with concurrency of 1, although it may download slower.

**Comment by holmesworcester** [comment]
I think we're looking for a quick fix to this so we can move on to iOS work. Let's use 1 or a number between 1 and 40 that seems reliable.

I have a vague memory that previously we had a problem where downloads would get stuck if a block was unavailable if concurrency was set too low. @EmiM does this ring a bell?

@vinkabuki do you remember?

**Comment by leblowl** [comment]
@holmesworcester It seemed like only 1 worked for me. I will review the algorithm and make sure it doesn't get stuck if a block is unavailable.

**Comment by leblowl** [comment]
It doesn't appear to get stuck if a block fails. It appears to use a queue and cycle through the blocks until it finds one it can download and then cycles through them all again, indefinitely.

**Comment by kingalg** [comment]
desktop@2.0.1-alpha.0

It's working.

It's incredible slow (it took 2 hours to download 62mb file) but it is working so speed is a topic for another issue.
