### ISSUE TITLE
Too much white space between keyboard and typing area

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1689]
Version: 1.8.1
System: iOS, smaller devices (like older series SE)

Description: on smaller devices when the user want's to type a message they can see big gap between typing area and keyboard. It's not a problem on bigger screens.

![45D49D54-FE0D-4A07-8671-35DC873B7D0B](https://github.com/TryQuiet/quiet/assets/68909168/36119e79-3d66-4732-8a3a-2d8b5ca33dfc)

Below from the left: android device, small iOS device and bigger iOS device. As you can see white space is disproportionately bigger on smallest device. 

<img width="1049" alt="Screenshot 2023-08-07 at 11 38 48" src="https://github.com/TryQuiet/quiet/assets/68909168/deb73571-f7f3-4ead-a504-efe09e477899">

**Comment by siepra** [comment]
![IMG_0008](https://github.com/TryQuiet/quiet/assets/15381135/f795475d-0bb9-46b1-a586-30785089fdcc)

**Comment by kingalg** [comment]
mobile@2.0.1-alpha.7 
System: iOS

Fixed, spacing looks good now.
