### ISSUE TITLE
Peer disconnecting crashes community owner Quiet

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1694]
Version: 1.7.1. (we had this issue in previous versions but it was either fixed or wasn't that severe - there is @Kacper-RF PR from May connected to that bug: https://github.com/TryQuiet/quiet/pull/1539) 

**Issue:** Peer disconnecting crashes community owner Quiet

**Steps to recreate:**
1. Create community on desktop (I mostly used MacOS for recreating that bug)
2. Join this community from different device
3. Close the app of joiner
**Expected:** Owner can use Quiet without any issue.
**What happens:** Owners app crashes.

**Console:**
<img width="1558" alt="Screenshot 2023-08-10 at 11 54 57" src="https://github.com/TryQuiet/quiet/assets/68909168/d4288051-5828-4e1a-ad24-2fba17a0e88a">

**Terminal:**
<img width="1680" alt="Screenshot 2023-08-10 at 11 56 18" src="https://github.com/TryQuiet/quiet/assets/68909168/307388d3-d62a-497f-a337-13ea36e1b20f">
<img width="1676" alt="Screenshot 2023-08-10 at 11 56 32" src="https://github.com/TryQuiet/quiet/assets/68909168/8056aaab-2def-4ee9-be7c-be7fb777881a">

**Comment by holmesworcester** [comment]
We should fix this before release if it's a regression. 

Why didn't the e2e tests that caught it before catch it this time?

**Comment by Kacper-RF** [comment]
I saw that problem randomly showed sometimes since May, and I created in that time pull requests with changes that can trigger that issue in e2e workflow and catch that error, so e2e tests on this branch are failing:
https://github.com/TryQuiet/quiet/pull/1539

But issue as far as i remember was not included in the previous sprints

**Comment by kingalg** [comment]
Version:  1.7.1-alpha.3
Fixed.
