### ISSUE TITLE
Use rounded icon on Windows, Linux

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1714]
In #1438 we made a nice rounded icon. Let's use it on Linux and Windows too! 

A user reported that the square edge icon looks weird amongst other rounded icons in their system tray.

**Comment by rajdip-b** [comment]
Hey @holmesworcester, can I take up this issue?

**Comment by holmesworcester** [comment]
Sure!

**Comment by rajdip-b** [comment]
Hey @holmesworcester, I tried updating the images but unfortunately after running `npm run distUbuntu` and running the Quiet app image from dist, the icon doesn't show up. Am I doing something wrong?

PS I have just changed the `icon.png` with the newer image.

**Comment by rajdip-b** [comment]
> Gah, actually there is an issue for that too: #485.
> 
> One solution would be to enable flatpak and other package formats on Linux, since we think those will work with icons out of the box. The downside is that I don't think many of them support automatic updating, except through a maintained repository: #1708
> 
> For this issue, if your change works on Windows, and if the new image file is present on Linux, then I think we're good.

But I don't have windows :(

**Comment by holmesworcester** [comment]
> But I don't have windows :(

Me neither! 

If you're feeling patient, I can vouch for these Microsoft-provided VMs as I've used them in the past with Parallels, and they seem to support VirtualBox too. https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

It's kind of a funny thing where Microsoft knows most developers don't have Windows and is happy to accommodate. :) 

It's up to you of course! But from the project's standpoint there are Windows-only issues on desktop that come up sometimes and it would be wonderful for us to have more people set up to work on them.

**Comment by rajdip-b** [comment]
Okay! I'll set up MS.

**Comment by rajdip-b** [comment]
Hey @holmesworcester, I was wondering if you folks have some place where we can communicate about the features/queries.

**Comment by holmesworcester** [comment]
We've been trying to use Quiet! email me for an invite! h@quiet.chat

**Comment by siepra** [comment]
Hello @rajdip-b thank you for your contribution!

Could you sync your fork with our latest changes and merge them into your branch? After that `lerna run lint` should take care of whitespaces formatting so that CI 'Check' will pass.

Also, it'd be great if you posted screenshots from various platforms to confirm everything looks fine after your changes.

Thanks again!

**Comment by rajdip-b** [comment]
surely! I'll do that ASAP

**Comment by kingalg** [comment]
desktop@2.1.0-alpha.0
On Windows, we have a rounded icon.
On Linux, as mentioned above, there is still a matter of #485

**Comment by rajdip-b** [comment]
> desktop@2.1.0-alpha.0 On Windows, we have a rounded icon. On Linux, as mentioned above, there is still a matter of #485

Hey, when I was working on the issue, I remember I came across an article that said it has got something to do with how the app was built. Although it was working on my device, I had to make some changes to my machine to actually pick it up.
