### ISSUE TITLE
Update certificate for macOS build (& fix notarization)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1721]
From Apple:

> Your Distribution Certificate will no longer be valid in 30 days. To generate a new certificate, sign in and visit [Certificates, Identifiers & Profiles](https://developer.apple.com/account/resources/certificates/list).

I'm pretty sure this is the macOS certificate we use for avoiding warnings on macOS. We should update this ASAP.

Let me know if you need access to this area.

**Comment by holmesworcester** [comment]
@kingalg are you seeing any problems with Gatekeeper warnings when doing a fresh install on Mac OS? 

@siepra did this get updated?

**Comment by kingalg** [comment]
@holmesworcester no problems or unexpected messages on my side.

**Comment by holmesworcester** [comment]
Got a report from a user of: 

![image](https://github.com/TryQuiet/quiet/assets/213678/76d0380d-5cd0-4393-9654-8df987a10619)

Our own devices won't be a reliable view of this.

**Comment by siepra** [comment]
Isn't it just the fact that people download Quiet from source other than App Store? The solution is to click "Show in Finder", then ctrl+click the Quiet icon and choose "open"

**Comment by holmesworcester** [comment]
> Isn't it just the fact that people download Quiet from source other than App Store? The solution is to click "Show in Finder", then ctrl+click the Quiet icon and choose "open"

That is a possible workaround but it's not what users typically have to do. Try downloading Spotify or Slack, e.g., and you'll see that this is not necessary, because the app is properly signed. 

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

**Comment by siepra** [comment]
What version did the user try to run?
Here is a commit of Barter's' for fixing notarization https://github.com/TryQuiet/quiet/commit/1d98ec3b63f0696d8d3dc1ce9c074aff825107cd
It should be fine since version 1.9.6 (2.0.2-alpha.0)

**Comment by holmesworcester** [comment]
There are two separate issues: 

1. Altool deprecation
2. Certificate expiration 

This issue is for the second, which I believe is the problem here.

**Comment by siepra** [comment]
I don't think it's the second case as all our certificates are valid

**Comment by siepra** [comment]
@Kacper-RF spotted an error trying to notarize the app last time (it was easy to miss as it didn't interrupt the job).
We pushed a fix for configuration and started the build https://github.com/TryQuiet/quiet/pull/2078/files

![Image](https://github.com/TryQuiet/quiet/assets/15381135/9aa73b2f-fc03-4cc0-a867-919669baffcb)

**Comment by holmesworcester** [comment]
What a weird situation. Apple's warning makes it sound like action is required. Does every release involve getting a new certificate?

**Comment by siepra** [comment]
_Does every release involve getting a new certificate?_ - no, a certificate have it's expiration date after which it must be renewed

**Comment by siepra** [comment]
I don't know how to make electron-builder stop in case of notarization fail @EmiM @vinkabuki you're more familiar with electron-builder, do you have any thoughts?
