### ISSUE TITLE
Heisenbug - can't join community on Windows (isCommunityInitialized is false)

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1750]
Version - 1.9.0 - this is an issue in PRODUCTION version
System - Windows 11 Pro
 
Issue: 
1. I've installed fresh version of Quiet.
2. Tried to join our "big" community. 
3. I saw messages showing in notifications but the app was not fully. going through registration process.
4. I've tried restarting the app but it changed nothing.

![image](https://github.com/TryQuiet/quiet/assets/68909168/1a10e73c-3810-44b6-b046-3516d07700ac)
Read extra envs: { TEST_MODE: 'false' }
2023-08-31T13:59:33.672Z quiet Initializing debug logger
setAsDefaultProtocolClient true
electron main
2023-08-31T13:59:35.245Z quiet Initializing debug logger
2023-08-31T13:59:35.246Z quiet Initializing debug logger
2023-08-31T13:59:35.247Z quiet Initializing debug logger
WARNING: Missing strong random number source
2023-08-31T13:59:35.631Z quiet Initializing debug logger
2023-08-31T13:59:35.631Z quiet Initializing debug logger
2023-08-31T13:59:35.711Z quiet Initializing debug logger
options {
  socketIOPort: '52565',
  appDataPath: 'C:\\Users\\WinFish\\AppData\\Roaming\\Quiet',
  resourcesPath: 'C:\\Users\\WinFish\\AppData\\Local\\Programs\\quiet\\resources',
  platform: 'desktop'
}
configOptions {
  socketIOPort: '52565',
  torBinaryPath: 'C:\\Users\\WinFish\\AppData\\Local\\Programs\\quiet\\resources\\tor\\tor.exe',
  torResourcesPath: 'C:\\Users\\WinFish\\AppData\\Local\\Programs\\quiet\\resources\\tor',
  torControlPort: 52568,
  options: {
    env: {
      appDataPath: 'C:\\Users\\WinFish\\AppData\\Roaming\\Quiet\\Quiet'
    }
  },
  env: {},
  bootstrapMultiaddrs: [],
  createPaths: true
}
2023-08-31T13:59:35.742Z quiet Initializing debug logger
2023-08-31T13:59:35.743Z quiet Initializing debug logger
2023-08-31T13:59:35.813Z quiet Initializing debug logger
2023-08-31T13:59:35.814Z quiet Initializing debug logger
2023-08-31T13:59:35.814Z quiet Initializing debug logger
2023-08-31T13:59:35.815Z quiet Initializing debug logger
2023-08-31T13:59:35.815Z quiet Initializing debug logger
2023-08-31T13:59:35.816Z quiet Initializing debug logger
QUIRT DIR C:\Users\WinFish\AppData\Roaming\Quiet\Quiet
2023-08-31T13:59:35.817Z quiet Initializing debug logger
2023-08-31T13:59:35.818Z quiet Initializing debug logger
2023-08-31T13:59:35.819Z backend:SocketService init:started
2023-08-31T13:59:35.820Z backend:SocketService Data server running on port 52565
2023-08-31T13:59:36.266Z backend:SocketService socket connection
2023-08-31T13:59:36.266Z backend:SocketService init: connection
2023-08-31T13:59:36.266Z backend:SocketService init:finished
2023-08-31T13:59:36.269Z backend:Tor Initializing tor...
2023-08-31T13:59:36.270Z backend:Tor C:\Users\WinFish\AppData\Roaming\Quiet\Quiet\torPid.json exists. Old tor pid: 13176
[
  '--SocksPort',
  '52574',
  '--HTTPTunnelPort',
  '52569',
  '--ControlPort',
  '52568',
  '--PidFile',
  'C:\\Users\\WinFish\\AppData\\Roaming\\Quiet\\Quiet\\torPid.json',
  '--DataDirectory',
  'C:\\Users\\WinFish\\AppData\\Roaming\\Quiet\\Quiet\\TorDataDirectory',
  '--HashedControlPassword',
  '16:08AADFA641BE713B60DEE34F81218DAA036BDF8769A9C7E5B44C92E788'
]
Checking for update
2023-08-31T13:59:36.646Z backend:Tor Deleting C:\Users\WinFish\AppData\Roaming\Quiet\Quiet\torPid.json
2023-08-31T13:59:36.672Z backend:Tor Aug 31 15:59:36.677 [notice] Tor 0.4.7.13 (git-7c1601fb6edd780f) running on Windows 8 [or later] with Libevent 2.1.12-stable, OpenSSL 1.1.1s, Zlib 1.2.13, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Aug 31 15:59:36.677 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
2023-08-31T13:59:36.694Z backend:Tor Aug 31 15:59:36.699 [notice] Configuration file "C:\Users\WinFish\AppData\Roaming\tor\torrc" not present, using reasonable defaults.
2023-08-31T13:59:36.696Z backend:Tor Aug 31 15:59:36.699 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\WinFish\<default>. Is this what you wanted?
Aug 31 15:59:36.699 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\WinFish\<default>. Is this what you wanted?
2023-08-31T13:59:36.699Z backend:Tor Aug 31 15:59:36.703 [notice] Opening Socks listener on 127.0.0.1:52574
Aug 31 15:59:36.705 [notice] Opened Socks listener connection (ready) on 127.0.0.1:52574
Aug 31 15:59:36.705 [notice] Opening HTTP tunnel listener on 127.0.0.1:52569
Aug 31 15:59:36.705 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:52569
Aug 31 15:59:36.705 [notice] Opening Control listener on 127.0.0.1:52568
Aug 31 15:59:36.705 [notice] Opened Control listener connection (ready) on 127.0.0.1:52568
2023-08-31T13:59:36.740Z backend:Tor Aug 31 15:59:36.000 [notice] Bootstrapped 0% (starting): Starting
init
2023-08-31T13:59:36.750Z backend:ConnectionsManagerService attachTorEventsListeners
launch 1
2023-08-31T13:59:36.756Z backend:ConnectionsManagerService launchCommunityFromStorage
launchCommunityFromStorage - community {
  id: '59F18EAFF9A893C3918A890F7DE4EEB9',
  peerId: {
    id: 'QmPdYEzuJb8Vz1NMkkcbVvhGtuPrj8XbmdWRpb8Suw2iDZ',
    privKey: 'CAASqAkwggSkAgEAAoIBAQCuUilJN40j+1vDmWJDxs7UlO4Bquhq15U24e2A1krZQv6DAoqwIquzYz7kwwLpmDhIY5mNO2Zi3HQiwsTYd6uoo5LX9YZEM3VL2dkrwOHDT5UYLcM+s0aFsO4IpQvaGm9A5fFm0tjEe0qYeDk+YcIM8LDB4s54GJOn/LuXVGIdWme3LP4dEtGTmc4gqSSwq9ow3eGbcsssA3gQQjoESGYtktyJ2cSxvRKWe0b6wMG4C4Or42tECAkdRRBDF4uWzLU1+pR8v1MemLZsgr5w/fBAxtoUYRo5I++XoIupGt69pINHq6ZCfCPi9y7bAufCOO2EL64pwzMkgxFQBEuXh5wLAgMBAAECggEAHLGKeTJLKa6QusAPJC/f0K8ZBC5BJoEI3ylOIkRjuqJj6WWsNXTnhVYjPp1458F2FjhKyKwL3N8DwMsFgsoj99TA8YpJCQXdW1hm/mQ35SG+3WV++12gEJaAf+zG6CYsxOZ0l2PCaYkPzMwRRBrsSZv+xFNUgAEvoNmheTXbFpCKJ0kbRDuY7ep6S2qgsMGqkcarE3fNI3cxSo+Kflf0X9f/mqkBmKXJH5zt3oIQi+mj4VlzgUdo2JTZVpiaBG7izFPXzqHDbHRF9ovBp6E7dJwIwK0PcLwARYB1cAwyWax4UK/Vq+3Uv+m2+p1NH6qYcyIAoxkpmTIwF/YAggM0PQKBgQD1kU5ZeXMZhJXt1ZC2G5Ikm+XZBI7q+CwU1+i2c390Buu/8KcXxmZ03Vp8c6HAduvNUtqd/e579p5LsoD3JHX+cuW6YGXllvxc4tPA38uiMA9uvpJ5+ojNF9H+sh9xAiivXRDp1vB0JnFpqNdUO5967grWqv3OnireyF+V9JOSLQKBgQC1ugFfWRNedhf7uqVJKT7jaH2z7+WU9+aCljLUsXzbzQ8LKgPJ2Aw2Y1/PRonORL0LAk0LVlV+S6TJxmx9bTQGe1nDnTtMwHdInCQlgmone2+Qh1/GX6EaXwpd0plcrDeKp5J7HhZIvMK8/TISrZu2D4es+nl73iSfZ6nTBvmiFwKBgHonBapMV4zh/xKHoax0moXLZtJFCjKnsIXNwNzBJy04JB0eQH/7GQwY7+HoQxXSEgnYpRbiMbdIPgW5jZ1iba9cyBmlygoiyPYLfvn6WPkcnxCfi41RqqsapkLjp/A2+rYAvWEUohek59V/P12PKw2jS5DtDcOxufGICsQ1HRMhAoGBAKy8pMdULVQR3tQ54xi66vtQfIQIWWsThPnF+YUxPKTVsyICit1Wzqz4Ir8sppr5vdP0GPXY16UYFAhz4vYKUnSC1Z1aHF7lZ70OJlG9OFhVPYPdGg2/IqylgH4UTBDJ5nWWuWbr/3SecGEiL3GPsj4JXwbug4FZc+hNqiBcNfd7AoGBAKdq2L7YGjob+yPyIGWImRY3hIVWKVgad5AutFdYiyx+zBKtlg3VPIrXeyxt2vpUjcjKLPszqnCawwZf4B61L5K50HycO1edt7kDm+AhE8Zw7qhhI3+IMzOGEJsWl9vfqb8zUVbpBq0LoHXQuHy6cOFxqVXtSSNO4O3jvgt32u39',
    pubKey: 'CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCuUilJN40j+1vDmWJDxs7UlO4Bquhq15U24e2A1krZQv6DAoqwIquzYz7kwwLpmDhIY5mNO2Zi3HQiwsTYd6uoo5LX9YZEM3VL2dkrwOHDT5UYLcM+s0aFsO4IpQvaGm9A5fFm0tjEe0qYeDk+YcIM8LDB4s54GJOn/LuXVGIdWme3LP4dEtGTmc4gqSSwq9ow3eGbcsssA3gQQjoESGYtktyJ2cSxvRKWe0b6wMG4C4Or42tECAkdRRBDF4uWzLU1+pR8v1MemLZsgr5w/fBAxtoUYRo5I++XoIupGt69pINHq6ZCfCPi9y7bAufCOO2EL64pwzMkgxFQBEuXh5wLAgMBAAE='
  },
  hiddenService: {
    onionAddress: 'bdzlvacg3mgvraf3nshm3xu2noit73jfh6xkn7nscyqlj3fwfju5wryd.onion',
    privateKey: 'ED25519-V3:4PICxrGVGqeOCRjDvwrCQyvrON6AeZFS37xZFRS8JHwNuFERx3R5UcfUlOJ9rNLLFqUciTqSEhEPjFBnKZrAng=='
  },
  certs: {
    certificate: 'MIIDgDCCAyWgAwIBAgIGAYo7fDyIMAoGCCqGSM49BAMCMBUxEzARBgNVBAMTCnF1aWV0LXRlYW0wHhcNMjMwODI4MDkzMTUyWhcNMzAwMjAxMDAwMDAwWjBJMUcwRQYDVQQDEz5iZHpsdmFjZzNtZ3ZyYWYzbnNobTN4dTJub2l0NzNqZmg2eGtuN25zY3lxbGozZndmanU1d3J5ZC5vbmlvbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABG0JOE7RqL7P7UC0AVNK1J0Yg65Vba2wtEGEUTHCaZs7JLHtYtt6neP5tmBU3mIbVRBI8z2/aCEBSOM2wauA1lujggIrMIICJzAJBgNVHRMEAjAAMAsGA1UdDwQEAwIAgDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwggFHBgkqhkiG9w0BCQwEggE4BIIBNAirxeDsYFODFwz1SNNaHX46fAxApE1J8qUrPkLMO5TE12JCIYZjR8Si0eztywUVCIfuwT9xg3q5vjTX2JMd6O0YDggrB+R0l97rJ0N9nl2DLHEn3f6l/eR4VW7wI4+jPzKW89VLWjvTjMt0n4MUgOkkqu/lMjYzDFjm9QoTLaJR2bJuuNUiWgC5qXfadzFneflM2nBWHFbw2jGPxQ1558N0hk6HZc83+ccc66sbTZDl+hzAIoeY1G8dfhcKkjrjTVUHvulWz6RPQ8ez+oV0afWX80GYAQXj9Gb8bF16iFooGdKjcIyEI0CUCLcs936IaK4jCAgCq6uJskzwCgT4DaaHbQxF5oHQ6UEO2NWRJ6tfVY8MlYKjo8cM4BW5+3qkyhJ6o6Yg79UCYV0Wv4haL+Ts3IHwMBkGCisGAQQBg4wbAgEECxMJa2luZ2EyODA4MD0GCSsGAQIBDwMBAQQwEy5RbVBkWUV6dUpiOFZ6MU5Na2tjYlZ2aEd0dVByajhYYm1kV1JwYjhTdXcyaURaMEkGA1UdEQRCMECCPmJkemx2YWNnM21ndnJhZjNuc2htM3h1Mm5vaXQ3M2pmaDZ4a243bnNjeXFsajNmd2ZqdTV3cnlkLm9uaW9uMAoGCCqGSM49BAMCA0kAMEYCIQCaQg6DibzGAqA82gQY0iBNcJo3MkfG/B1lJOM2jM1+QgIhAMBPzPvi3hnQECYcKF3/t8UDcGB2xuQOnOsMd3DL1Qjv',
    key: 'MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgz6Jo7Lu0xe4bTDcmPtn+TniKpyGsqOveUNeIWLVi+zSgCgYIKoZIzj0DAQehRANCAARtCThO0ai+z+1AtAFTStSdGIOuVW2tsLRBhFExwmmbOySx7WLbep3j+bZgVN5iG1UQSPM9v2ghAUjjNsGrgNZb',
    CA: [
      'MIIBWDCB/qADAgECAgEBMAoGCCqGSM49BAMCMBUxEzARBgNVBAMTCnF1aWV0LXRlYW0wHhcNMTAxMjI4MTAxMDEwWhcNMzAxMjI4MTAxMDEwWjAVMRMwEQYDVQQDEwpxdWlldC10ZWFtMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQAEUOcH8Lor0eIo6kV1scnjyrHVjGBObdmn+8o686UevfK7vGR5b7VjccX5nlFLHNAScpcqjaZxY+CEsE4m8GaM/MD0wDwYDVR0TBAgwBgEB/wIBAzALBgNVHQ8EBAMCAIYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMAoGCCqGSM49BAMCA0kAMEYCIQCmD0vBtDLk2VOfulk4xlWQmLyMouvO2hDrlppQvPQBswIhAL6McoW2W/VPs852GfrvV5sWKnwoJLgrUYL9Bikdq2nq'
    ]
  },
  peers: [
    '/dns4/k5exlvr5v2ce3jp3gifqjxn542tjsooo7pzrciu6r76xicp7jkf5m5yd.onion/tcp/443/wss/p2p/QmaUcphyAFUwpz4S3MGuzgSBuVv7ZP2oHE3MpvtD3HPExL',
    'QmaUcphyAFUwpz4S3MGuzgSBuVv7ZP2oHE3MpvtD3HPExL',
    '/dns4/5o4ku5qawixnlinhel26nabwriwfwh4sjaxr3tzvhrork24ssbi3ziad.onion/tcp/443/wss/p2p/QmdcviSM1bUS9vYriTLXpjfBezvz4Jxa8Fy2KzbzqE2Jja',
    '/dns4/leaiyhmi57c4pq24oz736zrwwtdqcbpmozrfdj7cnrzyym5q6l5d5nid.onion/tcp/443/wss/p2p/QmdauVfTAeWk8JL4KsattrSQSV9C5EjSuCP18dHTh81Rvv',
    '/dns4/cqs3mhq7yerinoo3cv4bryn737enhrbhdycscxn7lzhxeuaoxay57dyd.onion/tcp/443/wss/p2p/QmccJqu96aUFmwLdtqTwmwBRb1GJ2Q7dXtES1RhC8J14nw',
    '/dns4/zlpc3f3xlvegyw5ceszya4lwdzlbd5gl7dj7f4f32whm24z6bodhyrad.onion/tcp/443/wss/p2p/Qmcn6crAz2fiHMBuUKiWrE71EWLK9zwdsh8Kd2w3qcMrVu',
    '/dns4/pngsudozy7cazpwa2f3njwltmzsdoizp3t5uclxlbaykepz4uwblrvqd.onion/tcp/443/wss/p2p/QmVmx7wK3TzV2Kvv2aCJ1XLXhocQsJxvzgAFoHBtmPkNTF',
    '/dns4/2ykgggnw63tabsah5rxrlmgkbxoqr6nhheqt3cvidi7pfesnrnlf7vad.onion/tcp/443/wss/p2p/QmQam8VcVKpHSi8GGBjC3sQ2aMxWGpYiSmHuDBXhKjwF8B',

**Comment by vinkabuki** [comment]
@holmesworcester  UI state says that community is not initialized - > those are my logs I've added for hunting for heisenbug, so it works perfectly as I wanted - someone run into this and delivered the direction we should extend our logs to find the source.

**Comment by kingalg** [comment]
@vinkabuki is going to extend logs to have more informations in the future if someone encounter this bug. He asked me to close this issue as there is no point of keeping this open - we are already tracking heisenbug.
