### ISSUE TITLE
Add methods for extracting user data from CSR

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#1763]
Now we rely on CSRs as our source of data of users. Add methods for extracting user data fields from CSR - nickname, commonName, peerId, dmPublicKey.

**Comment by holmesworcester** [comment]
@vinkabuki nudge nudge nudge, add some detail here! Title-only issues often cause problems down the road.

**Comment by vinkabuki** [comment]
Added details, hope it won't cause any problems now! sorry!

**Comment by holmesworcester** [comment]
Is this a blocker to releasing? What does it enable?

**Comment by vinkabuki** [comment]
it enables displaying unregistered users names

**Comment by holmesworcester** [comment]
Got it, so it's required. In the future it would be good to put 'so we can display unregistered usernames' in the issue title.

**Comment by kingalg** [comment]
Version: 2.0.0-alpha.12

Done (consulted with Bartek).
