### ISSUE TITLE
Every user opening Settings for the first time should be in a tab with invitation link

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1764]
Every user opening Settings for the first time should be in a tab with invitation link.

At this moment (**Version: 2.0.0-alpha.3**) it is true for the owner (as per implementation of issues: https://github.com/TryQuiet/quiet/issues/235 and https://github.com/TryQuiet/quiet/issues/235) but not for joining users. 

**Expected behavior:**
When the user opens Settings for the first time, regardless if it's an owner or new user, they should see tab with invitation link (currently called "Invite a friend" but in the future "Add members" as per https://github.com/TryQuiet/quiet/issues/1465).

**Comment by holmesworcester** [comment]
@vinkabuki we should just do this now.

**Comment by kingalg** [comment]
Version: quiet@2.0.0-alpha.12
System: Windows, Linux, MacOS

Done.
