### ISSUE TITLE
Running Chromatic tests for forked PRs

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#1775]
I think it would be nice to allow a maintainer to run Chromatic visual regression tests for PRs from forked repos. Currently, it appears that it's necessary to create a branch on the quiet repo.

**Comment by holmesworcester** [comment]
Sounds good to me. Putting this in "Next sprint" but you can do it whenever!

**Comment by Kacper-RF** [comment]
I think there are two solutions:

1. External collaborator should add chromatic secret to his settings in forked repository.
2. Marek suggested that if You(Holmes) give this token to external collaborators when they ask, maybe it should be plain text ? It will probably completely remove the problem of running this workflow by other collaborators, but I know this may not be optimal for security reasons.

**Comment by holmesworcester** [comment]
I don't understand what you mean by plain text. You mean just put it in the repo?

**Comment by Kacper-RF** [comment]
Yes

**Comment by holmesworcester** [comment]
I have to check if chromatic has capped billing, or if there are other potential security issues.

I really don't like it, by default.

Can we run these tests ourselves for outside contributors?

**Comment by siepra** [comment]
@holmesworcester Chromatic's documentation says for oss forks we should just commit the project token as plaintext
https://www.chromatic.com/docs/github-actions#run-chromatic-on-external-forks-of-open-source-projects

**Comment by holmesworcester** [comment]
Okay let's do it!

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1862
