### ISSUE TITLE
Introduction of C4 diagrams to explain architecture to new contributors

### ISSUE THREAD

**Issue by Kacper-RF** [TryQuiet/quiet#1777]
I think that as part of a better onboarding of external collaborators, it is worth creating C4 diagrams of the Quiet ecosystem, thanks to which they will have a chance to see how different layers of the application work, what they are responsible for and communicate with each other.

As first step I will include two first levels of C4:

1.System context level -  overall scope of the application and how it interacts with users. Recommended for people who just want to understand how Quiet works.
2.Container level - more detailed diagram with detailed application layer such as mobile apps, backend, state manager etc. Focuses on high-level technology, recommended for software developers who want to work as collaborators and become familiar with ecosystem.

https://c4model.com/

**Comment by holmesworcester** [comment]
Great, let's do it.

**Comment by Kacper-RF** [comment]
Yes, of course i can do it.
But I'll start working on it tomorrow at the earliest or on Thursday, because now we are focused on trying to finish new registration flow(we are integrating all layers at the moment) which is worthy to be on diagrams in new form.

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1819
