### ISSUE TITLE
UserLabelComponent styling typo

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1810]
`UserLabel.component.tsx:41` "mergin" instead of "margin"

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1814

**Comment by leblowl** [comment]
Looks like this has been fixed on develop: https://github.com/TryQuiet/quiet/blob/f94151bd0ac3325fa384d48f98cb27c5d0d7f66b/packages/mobile/src/components/UserLabel/UserLabel.component.tsx#L41

**Comment by leblowl** [comment]
I'd suggest closing this issue unless you'd like to take a look @kingalg

**Comment by siepra** [comment]
We observe labels all the time so I guess we'd spot any abnormal presence of the component. Closing it then
