### ISSUE TITLE
Production Android release cannot (ever) join community

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1812]
The current Quiet production release of Android will never join a community created by the current production release of Quiet desktop, at least on Linux (haven't tried Mac yet but I assume it's the same.)

Steps to reproduce:

1. Open tryquiet.org in an incognito window and click to download the Android app (to ensure you aren't getting internal testing versions). You should see version 1.10  
2. Do a fresh install of Quiet Android 1.10 
3. Do a fresh install of Quiet desktop (Linux) from tryquiet.org. I'm reproducing this on Ubuntu.
4. Confirm you can join your community by starting another instance on desktop and using the invite link.
5. Try to join the community on your fresh install of the production release of Quiet Android

Expected: you join

Actual: you get stuck on the "Connecting process started" phase, forever.

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1813

**Comment by kingalg** [comment]
mobile@2.0.1-alpha.7 (iOS 325)

During last few days I've joined from android about 30-40 times with both QR code and link directly past in the app. This issue is solved.
