### ISSUE TITLE
Lerna bootstrap failure on windows

### ISSUE THREAD

**Issue by Ahmedouu** [TryQuiet/quiet#1818]
tried this a few times already on linux and windows and it keeps failing just on windows.

![image](https://github.com/TryQuiet/quiet/assets/33392644/a0b9620c-92f4-41c1-870e-e6bdbdb4caa3)

**Comment by EmiM** [comment]
Could you go to packages/backend and run `npm run prepare`? It will tell us more what happened. It may be a problem with patch.

**Comment by yaronarik** [comment]
I had the same issue



![npm run prepare](https://github.com/TryQuiet/quiet/assets/94235955/798d4778-53b7-40fb-94e3-6b98ff4ee900)

**Comment by vinkabuki** [comment]
You're missing patch lib.
Quick solution is to remove "applyPatches" in prepare script in backend package. applyPatches is just for mobile platforms.

**Comment by Ahmedouu** [comment]
@vinkabuki  I tried that but prepare keeps failing to run cause of the websockts module: 
![image](https://github.com/TryQuiet/quiet/assets/33392644/bdef30d6-0331-4eaf-8363-41120db7c244)

**Comment by vinkabuki** [comment]
@Ahmedouu It is just a warning, do you see something like "webpack 5.75.0 compiled with 6 warnings in 10857 ms" ? You should, it's the last output line after running npm run prepare

**Comment by Ahmedouu** [comment]
yeah I see it then I start the desktop package I get this websocket error:

![image](https://github.com/TryQuiet/quiet/assets/33392644/f37d1da4-4d9c-4d0d-b406-291c9dd04bb1)

then we I try to bootstrap again i get this:
![image](https://github.com/TryQuiet/quiet/assets/33392644/0a159c20-040d-471a-92bd-e213253dae70)

so I removed the prepare script and managed to bootstrap with no errors but still got the websocket error when I start the desktop app..

**Comment by Ahmedouu** [comment]
PS C:\Users\USER\projects\quiet\packages\backend> npm run prepare

> @quiet/backend@2.0.0-alpha.3 prepare
> npm run webpack


> @quiet/backend@2.0.0-alpha.3 webpack
> webpack --env mode=development && cp ./lib/bundle.cjs ../backend-bundle/bundle.cjs

assets by path nest/ 38.2 KiB 67 assets
assets by path *.ts 633 bytes
  asset rn-bridge.d.ts 473 bytes [compared for emit]
  asset backendManager.d.ts 122 bytes [compared for emit]
  asset index.d.ts 38 bytes [compared for emit]
assets by path __old/registrarTest/*.ts 24 bytes
  asset __old/registrarTest/parseRegistrarTestResults.d.ts 12 bytes [compared for emit]
  asset __old/registrarTest/torRegistrarTest.d.ts 12 bytes [compared for emit]
asset bundle.cjs 20.3 MiB [compared for emit] (name: bundle)
orphan modules 324 KiB [orphan] 166 modules
runtime modules 4.21 KiB 8 modules
modules by path ./node_modules/ 14 MiB
  javascript modules 13.4 MiB
    cacheable modules 13.4 MiB 3570 modules
    + 4 modules
  json modules 607 KiB 24 modules
modules by path ../ 1.23 MiB 73 modules
modules by path ./src/ 194 KiB
  modules by path ./src/nest/ 184 KiB 45 modules
  modules by path ./src/*.ts 9.79 KiB
    ./src/backendManager.ts 4.83 KiB [built] [code generated]
    ./src/rn-bridge.ts 4.96 KiB [built] [code generated]
+ 34 modules

WARNING in ./node_modules/@nestjs/common/utils/load-package.util.js 9:39-59
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@nestjs/core/nest-application.js 6:28-77
 @ ./node_modules/@nestjs/core/index.js 26:21-50
 @ ./src/backendManager.ts 3:0-43 33:22-58 72:22-58

WARNING in ./node_modules/@nestjs/core/helpers/load-adapter.js 9:39-63
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@nestjs/core/nest-factory.js 10:23-56
 @ ./node_modules/@nestjs/core/index.js 28:21-46
 @ ./src/backendManager.ts 3:0-43 33:22-58 72:22-58

WARNING in ./node_modules/@nestjs/core/helpers/optional-require.js 6:39-59
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@nestjs/core/nest-application.js 12:27-64
 @ ./node_modules/@nestjs/core/index.js 26:21-50
 @ ./src/backendManager.ts 3:0-43 33:22-58 72:22-58

WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/express/lib/application.js 22:11-28
 @ ./node_modules/express/lib/express.js 18:12-36
 @ ./node_modules/express/index.js 11:0-41
 @ ./src/nest/app.module.ts 21:0-30 129:34-41
 @ ./src/backendManager.ts 6:0-46 33:59-79 72:59-79

WARNING in ./node_modules/ws/lib/buffer-util.js 113:23-44
Module not found: Error: Can't resolve 'bufferutil' in 'C:\Users\USER\projects\quiet\packages\backend\node_modules\ws\lib'
 @ ./node_modules/ws/lib/websocket.js 31:21-45
 @ ./node_modules/ws/index.js 3:18-44
 @ ./node_modules/socket.io-adapter/dist/index.js 7:18-31
 @ ./node_modules/socket.io/dist/index.js 42:28-56
 @ ./node_modules/socket.io/wrapper.mjs 1:0-33 3:43-45
 @ ./src/nest/app.module.ts 25:0-47 67:39-47
 @ ./src/backendManager.ts 6:0-46 33:59-79 72:59-79

WARNING in ./node_modules/ws/lib/validation.js 117:24-49
Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\Users\USER\projects\quiet\packages\backend\node_modules\ws\lib'
 @ ./node_modules/ws/lib/sender.js 11:30-53
 @ ./node_modules/ws/index.js 8:19-42
 @ ./node_modules/socket.io-adapter/dist/index.js 7:18-31
 @ ./node_modules/socket.io/dist/index.js 42:28-56
 @ ./node_modules/socket.io/wrapper.mjs 1:0-33 3:43-45
 @ ./src/nest/app.module.ts 25:0-47 67:39-47
 @ ./src/backendManager.ts 6:0-46 33:59-79 72:59-79

6 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.75.0 compiled with 6 warnings in 13907 ms
'cp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by vinkabuki** [comment]
@Ahmedouu 
Replacing webpack script with this "webpack --env mode=development && xcopy .\\lib\\bundle.cjs ..\\backend-bundle\\bundle.cjs" and running npm run prepare (modified, without applyPatches) should solve the problem

**Comment by EmiM** [comment]
Most of the scripts are Windows-friendly now: https://github.com/TryQuiet/quiet/pull/1870

Notes:
* there may be a problem with applying patch on Windows (`npm run applyPatches` in packages/backend) - if git apply fails or running desktop throws "Electron failed to install correctly" one needs to modify electron-fetch lib file according to `electron-fetch-git.patch` and rerun webpack in backend (npm run webpack) before running dev desktop again.
* I did not focus on mobile development of Quiet on Windows - it may not work for now
* I generally recommend using powershell but bootstrap has been adjusted to also work in cmd.

**Comment by EmiM** [comment]
Sorry but we have to revert those changes: https://github.com/TryQuiet/quiet/pull/1937
Windows binary is not being built properly on CI right now and we would have to investigate it more deeply. My guess is that it's because of the not-always-working patch in the backend package.
I recommend using git-bash or wsl to develop on Windows machine for now.

**Comment by Ahmedouu** [comment]
I see, no worries, I use both just prefer windows.

Thanks,
