### ISSUE TITLE
Display "<user> has joined <community>" message when unregistered user joins

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#1836]
It's important for people to see when a new user joins the community, so we should show this when they join and not when they register.

I don't think we can guarantee that this message will always be sent as soon as the new user can read new messages, until we have implemented https://github.com/local-first-web/auth, so I will create a separate issue for that.

For now, it's okay if the joining user themself triggers the message.

**Comment by leblowl** [comment]
I agree, I think it makes sense that a member announces themselves when they join (even if they are not registered). I think we should probably implement this as part of the new unregistered user changes. @holmesworcester any thoughts?

**Comment by holmesworcester** [comment]
Yeah we should. This message noting that someone has joined is really helpful.

**Comment by holmesworcester** [comment]
Text change:

When new users join, members should see the following message from the "Quiet" identity: 

> @newuser has joined Community-name!  🎉"
> 
> Note:  @newuser is not yet registered, so they'll have the "unregistered" badge until the community creator (@owner) registers them, which will happen automatically when @owner next appears online. [Learn more]"

[Learn more] can link to an FAQ entry.

**Comment by Kacper-RF** [comment]
PR: https://github.com/TryQuiet/quiet/pull/1968
Contains core logic and desktop part, the mobile part will be made as a separate PR



![Image](https://github.com/TryQuiet/quiet/assets/111343884/467b3208-87c9-46ee-a1f7-7cdfad120ab5)

**Comment by holmesworcester** [comment]
Is anyone else nervous about this new explanatory text? I think it might be overthinking things and at the very least we'll need something shorter.

What about "@matt has joined and will be registered soon.🎉 [Learn more]"?

Even this is strange because in many cases the user will already be registered by the time people see this message, and they won't always be registered soon.

**Comment by Kacper-RF** [comment]
Variant with short info message:




![Image](https://github.com/TryQuiet/quiet/assets/111343884/44860dba-bc73-41b0-b795-a589922e5fc5)

**Comment by siepra** [comment]
Hey, I did take a look at the PR and have some thought on the implemented logic:
The one who joins only says hi, but it's the receiver who actually moderates the message content before displaying it - it kinda secures providing disinformation by the one who joins but also complicates things in a bad way on the receiver side. I suggest that the receiver doesn't moderate the content, but rather checks it's validity (by comparing the data from CSR with message content format) and in case of spoofing he can easily blacklist the sender. It'll result in limiting the complexity in receiver's presentation layer and will be way easier to modify/replace later.
@Kacper-RF @holmesworcester

**Comment by holmesworcester** [comment]
If we do it this way we should show this as coming from the user who joined, since they actually control what the message is. 

It's less nice but more secure and makes more sense. 

I'm not sure what it will look like, since it's someone talking about themselves in the third person, so it's kind of weird. Perhaps we should use our markdown feature to put this text in italics.

**Comment by siepra** [comment]
I mean, we should verify if the message fits the fixed format, so there'll be no way to send anything other than "[username] has joined and will be registered soon. :tada: [Learn more]"

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/2067

**Comment by kingalg** [comment]
Desktop: Version: 2.0.3-alpha.8
Mobile: mobile@2.0.3-alpha.9 (iOS 336)

I've checked it on all available systems (I did multiple registration in several configurations for a few hours) and I did not spot any issue.
