### ISSUE TITLE
"New user" message should explain registration

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1839]
When new users join, members should see the following message from the "Quiet" identity: 

> @newuser has joined Community-name!  🎉"
> 
> Note:  @newuser is not yet registered, so they'll have the "unregistered" badge until the community creator (@owner) registers them, which will happen automatically when @owner next appears online. [Learn more]"

[Learn more] can link to an FAQ entry.

**Comment by leblowl** [comment]
Related to https://github.com/TryQuiet/quiet/issues/1836 and https://github.com/TryQuiet/quiet/issues/1837. It seems like we might be able to consolidate these issues?

**Comment by holmesworcester** [comment]
#1837 seems like it should remain separate because it's a lot harder to guarantee that this message is sent than it is to send it most of the time.
