### ISSUE TITLE
Match designs for mobile chat input

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1840]
Design: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-%2B-desktop-%2B-prototypes?type=design&node-id=1427-35267&mode=design&t=hu0dnBSZOiEyejIs-4

**Comment by siepra** [comment]
iPhone SE7

![Image](https://github.com/TryQuiet/quiet/assets/15381135/34c71be7-c378-40d7-b99f-bf5b1921e24e)

**Comment by holmesworcester** [comment]
This is awesome! Just noting that the image attachment designs don't match (they should be smaller, with a non-fuzzy PNG, inside of the text input field which would get taller) but I am 100% in favor of making incremental improvements. Just noting this here for kinga that this level of improvement is fine. (And for siepra if you wanna keep going)

**Comment by siepra** [comment]
Yes, the attachment design is something that we really need to work on. Although as you said, incremental improvements are the way!

**Comment by siepra** [comment]
There were visual regression in input component, not caught soon enough due to e2e tests being down. I reverted the changes merged into develop and plan to re-open the PR after providing corresponding fixes.

**Comment by kingalg** [comment]
mobile@2.0.1-alpha.7 (iOS 325)

Done. Implementation matches design.
