### ISSUE TITLE
User missing "Unregistered" label

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1848]
Version: 2.0.0-alpha.12

3 users:
Mac (mac2209) - owner
Windows (win2209) - joined from link provided by the owner
Linux (lin2209) - joined from link provided by win2209 AFTER turning off the owner

**What should happen**: when lin2209 joined the owner was turned off so a new user should be able to send messages but they username should have label "Unregistered".
**What happened**: user lin2209 joined when the owner was offline. There was no message from the system that the user has joined (which is correct, we only send this message after user is registered) however when lin2209 send a message "Unregistered" label was missing.

Situation is pictured on a screenshot below (no "has joined" message and no "Unregistered" label).

<img width="717" alt="Screenshot 2023-09-22 at 11 54 22" src="https://github.com/TryQuiet/quiet/assets/68909168/363093a6-d69c-49f8-8dd1-a81bcc31aa87">

Once I turned the owner on system message that "lin2209 has joined" appeared so it confirms that before he was unregistered but missing the label. 
<img width="565" alt="Screenshot 2023-09-22 at 11 57 17" src="https://github.com/TryQuiet/quiet/assets/68909168/69e2bfc3-9d20-466a-817c-2bb851537dd2">

I've lost logs when I was trying to reproduce this bug, I will provide them if I encounter this bug again.

**Comment by holmesworcester** [comment]
Let's keep watching for this, double check the logic, and if no one else sees it we can close it.

**Comment by siepra** [comment]
I'm gonna review the logic while working on https://github.com/TryQuiet/quiet/issues/1900

**Comment by Kacper-RF** [comment]
Unfortunately neither me nor Bartek couldn't reproduce that issue (testing on Linux and Mac), so I added logs in React components and Redux selector to debug this issue in the future.

**Comment by siepra** [comment]
I'm moving it to 'blocked' as we wait for more data

**Comment by siepra** [comment]
I'm removing assignees as anyone can pick it up and examine debugging logs with Kinga atm

**Comment by kingalg** [comment]
I've tried to reproduce it today but I've got updated to the version that is not backward compatible and got stuck on that. I'm going to retry with newest version tomorrow and let you know about results.

**Comment by kingalg** [comment]
Version: 2.0.3-alpha.5

@siepra @holmesworcester I can't reproduce it in the newest version, looks like it's no longer an issue. I've tried with 5 users for desktop and mobile joining in several different configurations and everything looks fine. I'm closing this issue and moving to done. Feel free to re-open it if you disagree.
