### ISSUE TITLE
App must target Android 13 (API level 33) or higher

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1857]
We have until October 31 to target Android 13 (API level 33) to be able to push updates.

https://support.google.com/googleplay/android-developer/answer/11926878

**Comment by siepra** [comment]
Our application has been targeting API level 33 for some time already. I think this was not a warning but announcement and is not affecting Quiet application in any way

**Comment by leblowl** [comment]
Agreed, it looks like we are already target v33: https://github.com/TryQuiet/quiet/blob/99651b03cd2fe415c4a4f57da8eef824644e15dd/packages/mobile/android/build.gradle#L10-L11
