### ISSUE TITLE
Introduce Architecture Decision Record (ADR)

### ISSUE THREAD

**Issue by Kacper-RF** [TryQuiet/quiet#1861]
I would suggest to introduce ADR to our project as a possible solution for situations where we don't know why some non-obvious part of the code works this way or why we choose a certain solution or even a technological framework. 

Sometimes understanding some non-obvious part of the code takes a lot of time, or you even need to talk to the person who designed it

Even now, when we work with the Username Taken feature, we have to write some logic that probably requires explanation for people who don't code this part.

I already created some draft of that document(we will create ADR folder and then create separate files as `title.md` in that folder)

- Title
- Status( accepted | rejected | proposed | deprecated)
- Context (what is our problem)
- Decision (what we want to do as solution)
- Consequences (how it will affect app or individual parts of the app)
- Code location: (package->file)
- Date: (dd.mm.rrrr)

I can create template for that, and first example .

Please share your thoughts @holmesworcester  @leblowl  (I already shared this idea on our internal Rumble Fish daily).

**Comment by holmesworcester** [comment]
I'm open to this but would want to hear others' thoughts on the best way to accomplish these goals.

**Comment by leblowl** [comment]
I think I'm leaning more towards using RFCs (Request For Comments) (which are basically just proposals) using github issues. These can describe the proposed changes in detail before starting the big change and then the PR can link back to the RFC issue. I also think documentation is always helpful, especially documentation for internal workings of quiet, perhaps just in a `docs` directory.

**Comment by Kacper-RF** [comment]
I had possibility to write something like that because of request from Emi to describe new code part:
https://github.com/TryQuiet/quiet/pull/2054

**Comment by siepra** [comment]
I think Kacper's idea is brilliant. I personally like it better than RFCs as those can get messy and requires people to look them up on GitHub. Also those are kinda separate things so we can do both and benefit from both approaches

**Comment by leblowl** [comment]
It looks like we've done this sort of. At least there is one that is now outdated: https://github.com/TryQuiet/quiet/blob/develop/docs/handleCsrReplicationEvent.md. I'm going to close this. Feel free to re-open it.
