### ISSUE TITLE
Text cut off by editing field when sending long message

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1869]
Someone who heard about Quiet is trying to use it for a private community for their business, which is a community for hairstylists. They're very excited about p2p and privacy, but they ran into a bug that confused them and made them lose faith in Quiet. 

They sent a Loom, but it has some maybe private information from their desktop so I shared it privately with some folks on the team. It's probably too late to win back this user (they were really frustrated and need something that "isn't a first draft" in their words) but I'd like to fix this soon as a gesture and maybe win them back.

Steps to reproduce:

1. Paste a [long message](https://gist.githubusercontent.com/rt2zz/e0a1d6ab2682d2c47746950b84c0b6ee/raw/83b8b4814c3417111b9b9bef86a552608506603e/markdown-sample.md) into the text entry field
2. Confirm that the scrollbar of the text entry field is all the way to the top.

Expected: user should see the beginning of the long message.
Actual: user does not see the top of the long message, which leads a user to suspect that the message has been truncated. 

(See screenshot with selected sample text alongside. Note how the scrollbar is in the top position but the text is not line 1 in the selected text, "An h1 header.")

![Image](https://github.com/TryQuiet/quiet/assets/213678/dbfb2460-0ef2-4972-ba6b-e1e764aede92)

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/1878

**Comment by kingalg** [comment]
Version: 2.0.1-alpha.7

Fixed.
