### ISSUE TITLE
Clean up publishing automation

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1888]
Publishing recent hotfixes brought to light problems with our current automation setup for releases.
As a consequence, this PR containing changes to workflows and Lerna setup has been made https://github.com/TryQuiet/quiet/pull/1863.
It contains a list of changes in it's description.

**Comment by siepra** [comment]
I think we can handle https://github.com/TryQuiet/quiet/issues/908 as part of this task

**Comment by siepra** [comment]
I think one more useful thing would be to prevent some of the long-running jobs from being triggered by **DRAFT** PR (I've found this thread that may be helpful https://github.com/orgs/community/discussions/25722)
Although, this PR of mine has already grew big and I think it's best to stop adding more complexity to it.
Nevertheless, we may want to open an issue and schedule it for later? What do you think @leblowl @kowalski @vinkabuki @EmiM @Kacper-RF ?

**Comment by kowalski** [comment]
since it's 1 line with if I think it's faster to just add it intead of describing it in the issue ;)

**Comment by siepra** [comment]
Of course, but in this discussion I see people are rather not agreeing on a single solution and even if I introduced anything, I'd have to test if it works and it takes time.

**Comment by kowalski** [comment]
AFNP

**Comment by leblowl** [comment]
Long running jobs like e2e tests? I'm okay with skipping those for draft PRs
