### ISSUE TITLE
Add communityMetadata store validation

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#1891]
Only the owner should be able to update the community metadata. Currently anyone can modify the community metadata. This allows anyone to change the owner certificate (and nickname) and community name.

As an example, we replicate community metadata here:
https://github.com/TryQuiet/quiet/blob/277f96631805071654ad15f2bdf7f03567d3fadc/packages/backend/src/nest/storage/storage.service.ts#L244-L248

We save the metadata to the Redux store:
https://github.com/TryQuiet/quiet/blob/277f96631805071654ad15f2bdf7f03567d3fadc/packages/state-manager/src/sagas/socket/startConnection/startConnection.saga.ts#L263-L271

We get the owner nickname from ownerCertficate:
https://github.com/TryQuiet/quiet/blob/277f96631805071654ad15f2bdf7f03567d3fadc/packages/state-manager/src/sagas/communities/communities.selectors.ts#L78

Which is used to send a channel message:
https://github.com/TryQuiet/quiet/blob/277f96631805071654ad15f2bdf7f03567d3fadc/packages/state-manager/src/sagas/publicChannels/createGeneralChannel/sendInitialChannelMessage.saga.ts#L20

Another example, we set the community name from communityMetadata.rootCa:
https://github.com/TryQuiet/quiet/blob/277f96631805071654ad15f2bdf7f03567d3fadc/packages/state-manager/src/sagas/communities/updateCommunity/updateCommunity.saga.ts#L6

which is displayed to the user in the left-side panel:
https://github.com/TryQuiet/quiet/blob/277f96631805071654ad15f2bdf7f03567d3fadc/packages/desktop/src/renderer/components/Sidebar/IdentityPanel/IdentityPanel.tsx#L49

**Comment by holmesworcester** [comment]
Whoever tackles this should dig into it a bit and write up a document proposing how to solve the problem and get feedback before they start writing code.

**Comment by leblowl** [comment]
@EmiM and I discussed that it is easiest and most in line with how we are currently using OrbitDB to simply include the community owner's OrbitDB identity ID in the invite link.

We can see how this ID is used to verify write permissions by OrbitDB's IPFSAccessController: https://github.com/orbitdb/orbit-db-access-controllers/blob/3741eb318e9c7efea5af15a54110cf6de8ae1fe3/src/access-controllers/ipfs.js#L20

After the owner initializes their OrbitDB databases for the first time, we can save their identity ID (orbitdb.identity.id) in LevelDB under a key like `ownerOrbitDbIdentityId`. We can add a new file like `src/nest/storage/identity.ts` with functions for storing and retrieving the owner identity ID. We can create a new access controller, like `CommunityMetadataAccessController` which in it's constructor retrieves the owner identity from storage and caches it in memory and then proceeds to check entry identity IDs like in https://github.com/orbitdb/orbit-db-access-controllers/blob/3741eb318e9c7efea5af15a54110cf6de8ae1fe3/src/access-controllers/ipfs.js#L20

In addition, the owner should sign the community metadata and the access controller should check that the community metadata is signed by the public key included in the community metadata payload.

The owner's identity ID should be sent to the frontend for incorporating it into the invite link. In order to include the owner's OrbitDB identity ID and a PSK (#1897) in the link, we will need to reduce the number of peers in the invite link by 1. So PSK + owner OrbitDB identity ID + 3 peers.

When a new user clicks that link and joins, the owner's identity ID should be parsed from the invite link and sent to the backend where it's stored in LevelDB (via the same interface defined in `src/nest/storage/identity.ts`). This should happen before initializing any OrbitDB databases. Once the owner ID is stored, proceed to first initialize the community metadata DB.

The community metadata DB stores the owner's public key, which we use for authentication is some instances (e.g. when checking cert validity). So we should wait until community metadata has been replicated before initializing the certificates database or any other database that depends on the owner certificate.

This is just a rough sketch of one possible way things could be implemented.

**Comment by leblowl** [comment]
It looks like the access controller only validates heads and not each entry. So instead of using an access controller, we can simply validate each entry ourselves. We can create a new validation function `validateCommunityMetadata` that, given an entry, validates the entry according the specs above (and calls Entry.verify) and returns true/false.

In order to validate an EventStore, it's fairly straightforward as discussed in #1893. However, communityMetadata is currently a key/value store. Since we don't support multiple communities yet, I'm not sure we benefit from using a key/value store in this case, but we can continue with that approach to reduce refactoring. 

For KeyValueStore databases, the interface does not include an iterator method, so we can create a subclass of KeyValueIndex (https://github.com/orbitdb/orbit-db-kvstore/blob/main/src/KeyValueIndex.js) and override the updateIndex method to filter log values before calling super.updateIndex. We can provide this modified Index class to the KeyValue store during instantiation.

Then we can create a new function, `getCommunityMetadata` that simply retrieves the community metadata for a given community ID.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/2073

**Comment by kingalg** [comment]
2.0.3-alpha.15

Done
