### ISSUE TITLE
certificates log should be a key/value store pubKey -> Certificate

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#1898]
This will provide a nice index in memory and only one cert should be related to each pubKey.

**Comment by holmesworcester** [comment]
note: do before #1899

**Comment by leblowl** [comment]
I'm going to suggest we hold off on this for now to reduce refactoring.

**Comment by leblowl** [comment]
I'm going to close this for now, not sure it's desirable and we can revisit encryption/certificates soon

**Comment by kingalg** [comment]
@holmesworcester should this stay closed and be moved to the Done column or do we want to re-opened it and keep in the backlog?
