### ISSUE TITLE
Add certificates store validation

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#1899]
Currently anyone can write to the certificates log. This allows anyone to forge certificates. certificates store should only be writable to by the owner and we should validate certs and verify they are signed by the owner.

With the additions of #1843, when certificates are replicated:
https://github.com/TryQuiet/quiet/blob/e019b86fdf18d533ace217c4aaf63c945a12d3ee/packages/backend/src/nest/storage/storage.service.ts#L361-L367

They are then sent to the client, where they are parsed and added to the Redux store:
https://github.com/TryQuiet/quiet/blob/e019b86fdf18d533ace217c4aaf63c945a12d3ee/packages/state-manager/src/sagas/users/users.slice.ts#L20-L30

parseCertificate doesn't check the signature.

Then certs are used for usernames via allUsers selector:
https://github.com/TryQuiet/quiet/blob/e019b86fdf18d533ace217c4aaf63c945a12d3ee/packages/state-manager/src/sagas/users/users.selectors.ts#L76

If we don't verify that a cert is signed by the owner, we cannot guarantee username uniqueness and we cannot guarantee the public key in the cert is connected to the username in the cert... assuming that we trust the owner to check uniqueness and verify CSR signatures.

**Comment by holmesworcester** [comment]
If a cert not signed by the community owner is in this log, will that change user behavior? Or will it always be rejected as invalid because it's not signed by the owner? We should still fix this, but I'd also like to know the impact.

**Comment by holmesworcester** [comment]
We should address #1891 first and then address this.

**Comment by leblowl** [comment]
We can assume some of the the infrastructure necessary for this task will be implemented in #1891. Specifically that there will exist functions `putOwnerOrbitDbIdentityId` and `getOwnerOrbitDbIdentityId` in `src/nest/storage/identity.ts`. We can mock these functions and use them to implement an access controller (`CertificatesAccessController`) that verifies that only the owner can append entries to the certificates store. We should verify that following OrbitDB's IPFSAccessController as an example: https://github.com/orbitdb/orbit-db-access-controllers/blob/3741eb318e9c7efea5af15a54110cf6de8ae1fe3/src/access-controllers/ipfs.js#L20

We should also verify:
- that the certificate is valid (parses correctly, formatted correctly, contains required fields, etc.)
- that the certificate is signed by the owner's key
- that the entry key matches the certificates public key

We will also need to create a function that migrates the certificates store to a new database, since we will be using a new access controller and the OrbitDB database + access controller is immutable.

We can call it `certificatesV2` or similar and create a function called `migrateCertificatesV2` that is called on initializing the OrbitDB databases which takes entries from certificates and adds them to certificatesV2.

**Comment by leblowl** [comment]
I think we should change the approach to this since it looks like the access controller only validates heads and not each entry. Instead of using the access controller, we can simply validate each entry ourselves. We can create a new validation function ~validateCertificate~ that, given an entry, validates the entry according the specs above (and calls Entry.verify) and returns true/false. Then we can create a new function, ~getCertificates~ that iterates over the certificates log entries, and filters the logs with ~validateCertificate~ such that it only returns valid entries. It should also filter and return only the latest certificate per public key. We can then use ~getCertificates~ to send valid certs to other parts of the application for processing. See also #1893. We can optimize this later.

**Comment by kingalg** [comment]
@leblowl any way I can check this doing manual checks?

**Comment by kingalg** [comment]
Desktop: quiet@2.0.3-alpha.15
Mobile: mobile@2.0.3-alpha.17, ios 344
