### ISSUE TITLE
Unregistered users improvements

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#1902]
Issues related to the unregistered users feature:
- [ ] #1891
- [ ] #1892
- [ ] #1893
- [ ] #1894
- [ ] #1895
- [ ] #1896
- [ ] #1897
- [ ] #1898
- [ ] #1899
- [ ] #1900
- [ ] #1901
- [ ] #1903
- [ ] #1910

**Comment by holmesworcester** [comment]
I think this belongs in sprint, since at least some of these are things we want to do before releasing.
