### ISSUE TITLE
Deep links doesn't work

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1920]
I suspect it has something to do with store not being ready while trying to dispatch deepLink action. It's probably a race condition which can be fixed in the react-native layer.

It was probably introduced while making changes for handling lifecycle changes on iOS.

**Comment by holmesworcester** [comment]
Noting from the morning update that this impacts joining a community.

**Comment by kingalg** [comment]
mobile@2.1.1-alpha.0 | iOS 350

Fixed
