### ISSUE TITLE
Invite settings screen looks strange with long link

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1932]
In Quiet 2.x the invite links are longer, so the invite screen looks weird. It confused our designer, e.g. and he thought it was a bug. 

One solution is to not let the link wrap.

![Image](https://github.com/TryQuiet/quiet/assets/213678/8d183efd-cc33-42cf-8e47-a76a779852a0)

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1936

**Comment by kingalg** [comment]
Version: 2.0.1-alpha.7
System: Linux, MacOS, Windows

Fixed.
![Uploading Screenshot 2023-10-19 at 13.23.53.png…]()
