### ISSUE TITLE
"Add members" not scrollable on smaller mobile devices

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1976]
Version: quiet@2.0.1-alpha.7
System: iOS, android (devices with smaller screens)

Our new joining link is quite long and on smaller mobiles takes most of the screen making it impossible to see buttons line "QR code" or "Share".

We either need to hide part of the link or make the whole "Add members" section possible to scroll.
On below screen you can see the whole screen available to the user on iphone SE.

![66C5B8F5-CD4F-4825-B811-F1352FCC37A9](https://github.com/TryQuiet/quiet/assets/68909168/edf579cc-e237-4c0e-8259-2231eccd05df)

**Comment by holmesworcester** [comment]
It should be limited to one line like on desktop

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1983

![image](https://github.com/TryQuiet/quiet/assets/111343884/11ff77f6-e9a9-4c33-9240-476ef6383312)

**Comment by kingalg** [comment]
mobile@2.0.3-alpha.0 (iOS 327)
System: iOS, android

Fixed.
