### ISSUE TITLE
Migrate to macOS notarytool by November 1

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1978]
We're using a macOS notarization approach that will be deprecated November 1. 

https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3

UPDATE: 
1. Confirm this is not also a problem in mobile
2. Address this on macOS, possibly by looking to see if a new version of electron-builder fixes this.

**Comment by siepra** [comment]
I was trying to use notarytool one day and didn't succeed (I don't remember why exactly). Anyways, we should switch to Fastlane, although I could use somebody's help with that @holmesworcester

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/2008
