### ISSUE TITLE
Notify users about backwards incompatibility on mobile

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1980]
We should create an update to notify users that they are on a deprecated release of Quiet and encourage them to upgrade from the website. Desktop apps should not autoupdate from 1.x to 2.x. We'll create our own community and probably a separate one for outside collaborators and users.

For iOS we'll disable the 1.x testflight release and give a note to users.

For Android users will probably see the 1.x release with the warning and we can include a note in the app description. 

We can include an email address to contact us with any questions! help@quiet.chat 

This should be released as soon as it's done. 

**UPDATE: This issue now covers only the behavior on mobile. See: https://github.com/TryQuiet/quiet/issues/1980#issuecomment-1795028313**

**Comment by holmesworcester** [comment]
@EmiM @vinkabuki @leblowl I've been trying to craft a message that makes sense to show before the upgrade, and I think it might make sense to show it after people upgrade instead, if that's possible. 

Assuming we do an automatic update from 1.x to 2.x (which is what will happen on Android at least) will people have access to their existing messages? Or will we have to reset all data from previous versions?  

Is it an option for someone to upgrade automatically and then see a message (like our Quiet "bot" messages when new users join) that tells them something like the following?

> Now you can join communities when the community owner is offline! This makes joining communities faster and more reliable! 🎉 However, it also makes existing communities stop working. 😥 We wanted to avoid this, but it wasn't practical.
> 
> Action steps:
>
> * Members: please leave this community and rejoin with a new invite from your community owner.
> * Owners: please leave, create a new communitty, and re-invite members. 
>
> Apologies for the annoyance! Questions? Email: help@quiet.chat

**Comment by EmiM** [comment]
Showing this after upgrade would be a bit complicated because community will not even launch without psk after releasing https://github.com/TryQuiet/quiet/issues/1897 - libp2p needs psk.

I'd stick to what we discussed before - to release a separate version with warning that Quiet will be backward incompatible since version X. Or we could even add a date of release.

**Comment by holmesworcester** [comment]
> Showing this after upgrade would be a bit complicated because community will not even launch without psk after releasing https://github.com/TryQuiet/quiet/issues/1897 - libp2p needs psk.

What do you mean "community will not even launch"? 

Do you mean the app will become unusable? 

Do you mean that messages will still be visible but you will not be able to send or receive messages? 

What will happen if they reinstall the newest version from tryquiet.org? 

What will happen if we do an autoupdate to the newest version?

What we want is:
1. Existing messages do not disappear from the app until the user is ready for that.
2. User can easily create a new community. (How will this work on Windows, where "Leave community" is still broken?)

Here's a warning we can show, but we need to make sure that messages will not be lost, and that users can leave the community and start a new one when they are ready.

![Image](https://github.com/TryQuiet/quiet/assets/213678/9982b397-d99d-4ac9-b54c-eb788efda9b8)

**Comment by siepra** [comment]
The next version will not be backward compatible - so the app will become unusable.
To prevent users from bad experience our idea was to disable auto updater with the same version featuring notification/warning, and to inform them to manually download a new one from try quiet.org.
As the user will not be able to enter the community in order to leave it, we should probably point to some other data directory starting with the new version (e.g. suffixed with the major number) @vinkabuki am I right?
Will installing the application cause removal of the data dir? If yes then we should probably advice users to do it before installing a new version

**Comment by holmesworcester** [comment]
On Android we won't be able to control when users upgrade I don't think, unless we do a new release. What should we do in that case?

How would users be able to delete the data directory?

How costly would it be to be backwards compatible in the sense that the community exists and messages are readable, even though connectivity won't work?

**Comment by siepra** [comment]
I did some research and my knowledge is there's no way to prevent auto-updates for users who have this option enabled on their side. However, we can try to:
1. Initially release breaking changes to open-beta track only. This way people will have to manually sign in to open-beta testing program to receive an update
2. Implement custom logic for detecting data compatibility. Inform the user and erase data programmatically if lack of backwards compatibility detected

User can always delete data directory by deleting app's data on the OS level. We can place an illustrated instruction somewhere.

I think it'd be very costly as it indicates making and maintaining a separate flow in the great part of backend just for the backwards compatibility purposes @EmiM am I right?

**Comment by EmiM** [comment]
Yes, Wiktor is right. We would have to implement alternative flow, test it thoroughly, check if regular flow did not break because of changes. It's just not worth it at this stage of the application.

**Comment by holmesworcester** [comment]
On desktop, this should work separately and we should create a new issue.

**Comment by siepra** [comment]
Emojis cause problems with line height. It's a known react-native issue, although there's no great solution for it yet.
https://github.com/facebook/react-native/issues/4457
https://github.com/facebook/react-native/issues/18559

I think there's no point to spending time on it right now so I suggest we either remove emojis for now, or don't care about it?

<img width="358" alt="Zrzut ekranu 2023-11-7 o 14 05 17" src="https://github.com/TryQuiet/quiet/assets/15381135/05dde7ea-1494-48d7-89ae-dc284bbfb365">

**Comment by siepra** [comment]
Also, what should happen after tapping on `Need help? help@quiet.chat`?

**Comment by holmesworcester** [comment]
We can remove the emojis. I was thinking the link should be a mailto: link or work like one. (Open the mail app with our address pre filled.)

If that doesn't work let's make a support section in the FAQ or wili and link to that.

**Comment by holmesworcester** [comment]
Both platforms is fine!

**Comment by siepra** [comment]
@kingalg Tested it in version 1.10.10 and claims it works fine

**Comment by kingalg** [comment]
I confirm that it is working.
