### ISSUE TITLE
Duplicate - Unregistered users mixed up

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1981]
Desktop: Version: 2.0.1-alpha.7
Mobile: mobile@2.0.1-alpha.7 (iOS 325)

This is rather complicated issue and also I'll try to describe it as clear as possible, don't hesitate to contact me if you need some additional explanation. 

I'm going to use names of specific systems but I was able to reproduce this on all systems in different combinations several times.

Legend:
Owner - Quiet user that created the community that the rest of the users want's to join
test1 - Windows user username that joined the community when the owner was online
Android - android user 
iOS - iOS user

1. Owner creates community.
2. Windows user join with username "test1" - joining is successful and username is registered.
3. Owner goed offline.
4. Windows user "test1" send invitation code to Android and iOS users.
5. Android tries to join with username "test1".
6. Android gets the popup with information that username is already taken and choose username "test2".
7. Android join community with username "test2" and tag "Unregistered".
8. iOS user tries to join with username "test2".
9. iOS join community with username "test2".

What should happen - both Android and iOS users are able to use the application with username "test2" and tag "Duplicate".
**What happen - on Windows and Android both users (Android and iOS) are able to use the application and have an username "test2" with tag "Duplicate", however - on iOS Android user has a name "test1" (that he tried to register with initially) and tag "Duplicated" and iOS user has username "test2" and tag "Unregistered".** 

Additional info: what happen when owner goes online? Usernames are still mixed up. Android user gets a popup informing that they need to change username - this popup doesn't work and makes app crush. Upon restart the app Android user can register new username.

If we are using desktop instead of mobile it's still bugged but in different way. Let's say that we used MacOS instead of iOS and Linux instead of Android"
Linux user gets an popup that his username will be registered once the owner is online (which is bad because of 2 reasons - Owner is already online and this user is consider by our system duplicated one so they username will not be registered). MacOS user gets username "test2" and no tag, Linux user has a tag "duplicate" and with next restart of the app is asked to choose different username.

**Comment by holmesworcester** [comment]
Asking users to change the username on restart is fine I think, if they change to a name that is taken and we don't catch this.

When we ask users to change a name are we checking their input against names we know are taken?

If users just restarted maybe they don't know what names are taken yet.

**Comment by kingalg** [comment]
@holmesworcester I agree with what you said. This part of the process is correct. There is still a matter of the main issue that I’ve described. I know that it’s quite complicated and I’ve tried to describe it the best I can but to be honest when I was explaining this to Kacper in the office there were diagrams and a lot of “step by step” descriptions to clarify everything. If I try to simplify it, the issue is mostly about the fact that different users in the same community see different usernames and tags for the same person. So there is a slight possibility of impersonation (not very probable but still - we can’t have things like this in our app).

**Comment by holmesworcester** [comment]
I don't doubt that you've found a bug but I'm trying to tease out what it is.

Rules:
1. Users shouldn't see the same user showing as registered with different names.
2. Users should always eventually see the same thing, when they're online with each other for a few minutes.

Are either of these rules broken? That's where we should focus.

**Comment by vinkabuki** [comment]
2 was broken

**Comment by kingalg** [comment]
2 is broken. 1 is not broken because it's **not registered** users that are showing with different names but still if one user is displayed with different usernames in the same community it's not good.

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/2002

**Comment by kingalg** [comment]
Desktop: Version: 2.0.3-alpha.0
Mobile: mobile@2.0.3-alpha.0 (iOS 327)

This issue is fixed. There is still matter of bugged popup that the user that needs to change their username once the owner is online gets. It's handled in different issue: https://github.com/TryQuiet/quiet/issues/2013
