### ISSUE TITLE
Replace ContentEditable with textarea

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#1984]
ContentEditable uses dangerouslySetInnerHTML underneath and it may cause js injection issues: https://github.com/TryQuiet/quiet/issues/744
Since we don't use ContentEditable features at the moment, we decided that using textarea is a acceptable solution.
Discussion for reference: https://github.com/TryQuiet/quiet/pull/1979

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1986

**Comment by kingalg** [comment]
quiet@2.0.3-alpha.0
System - all 

Done.
