### ISSUE TITLE
Invalid behaviour of pasting multiple files with the same file name

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#1987]
* Copy file with filename A from file explorer
* Paste it to message input- file preview appears
* Don't send the file
* Copy **different** file with same filename A
* Paste it to message input

Expected: second file/image preview appears next to the first preview
What happens: user can see only one preview, file data is replaced underneath to second file data. User can see that this happened only after sending the file to channel

**Comment by iranimij** [comment]
May I fix this issue?

**Comment by holmesworcester** [comment]
That would be awesome!

**Comment by iranimij** [comment]
Would you please assign it to me?

**Comment by iranimij** [comment]
Would you please assign it to me?

**Comment by holmesworcester** [comment]
I just invited you! Ping me when you accept and I'll assign you! Thanks again!

**Comment by iranimij** [comment]
I can not see your invitation

**Comment by holmesworcester** [comment]
Nevermind. Assigned to you!

**Comment by iranimij** [comment]
I tried to replicate the issue, but I couldn't and everything seems ok.

**Comment by holmesworcester** [comment]
@EmiM which platform did you see this on?

**Comment by iranimij** [comment]
Desktop, windows

**Comment by EmiM** [comment]
All desktops, I tagged the issue accordingly

**Comment by agiledev24** [comment]
Hi, @holmesworcester 
I grabbed the first issue and tried fixing it.
Please review!


![Image](https://github.com/TryQuiet/quiet/assets/80997421/5f1f8324-dcff-4098-a40e-0ae3c6e54a90)
![Image](https://github.com/TryQuiet/quiet/assets/80997421/95671102-d118-431f-a51f-f9ed3c0a725a)

**Comment by holmesworcester** [comment]
Thank you! @EmiM would you like to review?

**Comment by kingalg** [comment]
Version: 2.1.1

Thank you @agiledev24! The issue is fixed. 

https://github.com/TryQuiet/quiet/assets/68909168/700cead1-39ab-4246-85b3-7fff705672e3

<img width="410" alt="Screenshot 2024-03-08 at 14 57 47" src="https://github.com/TryQuiet/quiet/assets/68909168/f0df62b3-ee27-4596-bd83-f4f71067a118">
