### ISSUE TITLE
"Leave community" button in "Possible impersonation attack" popup not functional on windows

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2025]
Version: 2.0.3-alpha.0

On "Possible impersonation attack" popup we implemented "Leave community" option. However this will not work properly on Windows, so we need to decide what how to change it in order to reflect real options that users have. 

<img width="794" alt="Screenshot 2023-10-31 at 16 11 52" src="https://github.com/TryQuiet/quiet/assets/68909168/c05e7695-cda9-412f-b191-c07dad109ae3">

**Comment by holmesworcester** [comment]
The text is fine. Let's remove the button for now, on all platforms. This warning is clear and we'll fix the Windows issue at some point.

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/2037

**Comment by kingalg** [comment]
quiet@2.0.3-alpha.1

The button is no longer there.

<img width="656" alt="Screenshot 2023-11-08 at 13 01 00" src="https://github.com/TryQuiet/quiet/assets/68909168/797193a9-e2fa-43e4-8a72-3d6aa3dfff23">
