### ISSUE TITLE
Special update message to Quiet 1.x users re: backwards incompatibility

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2039]
When Quiet 2.x is released, we should do a final release of Quiet 1.x that has no changes, except that it shows a message reminding users that this release is not updated, that they should update Quiet by reinstalling from tryquiet.org, and that when they update their messages and community will not be carried over.

We can use the design for our "Software update" message, with the following text:

> **Update available**
>
> Quiet’s next release makes joining communities faster and more reliable by letting people join when the owner is offline! 🎉 However, these changes are not backwards compatible, so you must re-install Quiet from tryquiet.org and re-create or re-join your community. 😥 This version of Quiet will no longer receive any updates or security fixes, so please re-install soon. We apologize for the inconvenience.
>
> [Install Quiet 2.x]
> [Later]

This is not a normal autoupdate message. This message should appear on startup, forever.

The 1.x release should never update to 2.x (must use separate s3 buckets) and users should have to reinstall to get 2.x.

This release must happen *after* 2.x has been released.

**Comment by holmesworcester** [comment]
@EmiM @siepra any feedback on this? Can you see any problems with this plan overall?

**Comment by siepra** [comment]
@holmesworcester see the recordings posted in comments section of the PR and let me know if it looks fine

**Comment by siepra** [comment]
@holmesworcester Is it fine to leave the button pointing to the 'Downloads' section of https://tryquiet.org/ as I implemented it in the PR? This way we could just merge and release without being blocked by anything

**Comment by holmesworcester** [comment]
If we release it before 2x exists, they'll download the same version and get the same message, right? This seems broken?

As long as we wait until 2x is available to release then it's fine.

**Comment by holmesworcester** [comment]
Yes linking to the downloads section is fine.
