### ISSUE TITLE
Quiet desktop 1.x users should be able to install 2.x with no problems

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2040]
When a user running Quiet 1.x installs Quiet 2.x from the website, everything should work well, on Mac, Windows, and Linux.

* No data should be lost. (We should use a different DATA_DIR if possible)
* The application should still be called Quiet.
* It is not a required that they can run the old Quiet, as long as data is not lost.
* They should have a clean install of Quiet.

It's important to know what will happen on Mac and Windows. Please add notes here when we know.

**Comment by holmesworcester** [comment]
@EmiM @siepra any feedback on this? Can you see any problems with this plan overall?

**Comment by kingalg** [comment]
@holmesworcester are you aware that this will be true only for Linux? At least that is what I gather from the team.

**Comment by holmesworcester** [comment]
> @holmesworcester are you aware that this will be true only for Linux? At least that is what I gather from the team.

No, why? 

What happens on Mac?

**Comment by kingalg** [comment]
I may have simplified it too much. This is how it will work:
1. For Linux - there will be two separate Quiet. Old one with data_dir Quiet and new one with data_dir Quiet2
2. For MacOS and Windows - there can't be two applications with the same name, so new Quiet will replace the old one and will work with data_dir Quiet2. Data_dir Quiet that belongs to the old version will still exist.

Currently it's bugged on MacOs and Windows, @EmiM is working on this.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/2126

**Comment by holmesworcester** [comment]
The solution Kinga describes sounds good!

**Comment by EmiM** [comment]
Fix: https://github.com/TryQuiet/quiet/pull/2150

**Comment by kingalg** [comment]
2.0.3-alpha.152.0.3-alpha.15

Done
