### ISSUE TITLE
User should be able to export chats

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2077]
A user requested the ability to export all chats to flat text files for each channel, e.g. 

```
[alice 20:23]
Hi Bob!

[bob 20:24]
Sup Alice!
```

We should make this possible in the simplest possible way. We could add an "Export chats" item to settings, for example. Or have a command-line option, or even just a script that does this. The user is technical (and based on existing user requests I think it's reasonable to expect that users who want this initially will be somewhat technical or tolerant of technical steps) so we can do whatever is simplest.

**Comment by rajdip-b** [comment]
@holmesworcester Had a feqfew queries as I want to start contributing to Quiet for the first time (loved the project :D) 
- What format should the exported chats should be stored in?
- Mobile only / Desktop only / Both?
- Should we specify any limit on the number of chats we want to store? Lets say, by chat count or by a date range?

**Comment by holmesworcester** [comment]
@rajdip-b 

* The user who requested this feature suggested the text format and gave the above example. An export would give you a folder full of text files corresponding to each channel.
* IRC logs are typically in a slightly different format with one message per line. I'm sure that's okay too and might be better since it's more familiar.
* Desktop-only is best for this feature since it's a pro feature and iOS file management is a bit weird anyway.

**Comment by rajdip-b** [comment]
That's crystal!! I'll start with this ASAP.

**Comment by holmesworcester** [comment]
Great! Also I'll just emphasize that a script or a command line option would both be completely acceptable if you'd rather not mess with UI.

Also there is a "..." menu on each channel, and I think it would be acceptable for a user to export messages channel by channel. So we could add an 'Export messages' item to that menu and it could open a save dialog and let the user choose a filename.

I'm not sure which option is easiest so I'll leave that up to you!

**Comment by rajdip-b** [comment]
Okay! I'll frist try implementing the cli. I'm not sure where I should start from, I guess I'll get to it anyways!

**Comment by kingalg** [comment]
Version: 2.0.3-alpha.12
System - Linux, MacOS, Windows

Everything looks and working fine.

<img width="994" alt="Screenshot 2023-12-05 at 14 38 15" src="https://github.com/TryQuiet/quiet/assets/68909168/000696ea-2769-46a7-ad82-c31897157cf7">
.
<img width="986" alt="Screenshot 2023-12-05 at 14 39 32" src="https://github.com/TryQuiet/quiet/assets/68909168/93010cce-2d13-4983-b5cc-066a5d38b098">
.
<img width="508" alt="Screenshot 2023-12-05 at 14 39 52" src="https://github.com/TryQuiet/quiet/assets/68909168/ed2dcbdb-ecb7-482a-85cf-076e09793dc2">

**Comment by holmesworcester** [comment]
Thank you @rajdip-b!
