### ISSUE TITLE
Update popup with a typo and wrong position

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2149]
Version: 2.0.3-alpha.12
Systeem: Windows, MacOS, Linux

Issue1: Position of the logo and message in update popup is wrong - it should be in the middle but it's closer to the lover edge of the window.
Issue2: It says "availale" instead of "available". 

![image](https://github.com/TryQuiet/quiet/assets/68909168/ca6afc0b-1df5-4a93-8b75-08d3af4896a8)

**Comment by holmesworcester** [comment]
We should fix the typo before releasing.

Do we have a spellchecker in our linter? What do folks like as a general solution for this?

**Comment by kingalg** [comment]
Version: 2.0.3-alpha.14

Fixed.
