### ISSUE TITLE
It appears that it's possible to attempt to register the same username twice, even if we know it is already registered

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2156]
When I created a community, and then joined and tried to register with the owner's username. It first gave me an error, but then it allowed me to continue anyway and register with the owner's username.

Steps to reproduce on Linux:
1. Enter known duplicate username
2. Get error and note that button is inactive
3. Click a couple times and inactive button becomes active. 
4. Click now active button to continue

Expected: user should not be able to click through the warning by clicking the inactive button. User should have to change their username to one that is not known to exist already, in order to proceed. (In other words, the disabled button should actually be disabled.) 
 
Actual: user can click through the warning by clicking on the disabled button without changing their choice of username.

Note for QA: you should not be able to click inactive button on "change username" screen or in joining.

**Comment by holmesworcester** [comment]
It should continue showing the error.

**Comment by holmesworcester** [comment]
I mean the user should continue to see an error modal on each attempt.

**Comment by siepra** [comment]
For clarification - this is how it looks like before fixing


https://github.com/TryQuiet/quiet/assets/15381135/1c09081b-2fab-4995-ae3c-656511e99184
https://github.com/TryQuiet/quiet/assets/15381135/3e26b8f0-7816-4f7f-b450-94f7529073bb

**Comment by siepra** [comment]
These are results of the fix:


https://github.com/TryQuiet/quiet/assets/15381135/531c8741-bfba-4d40-9905-554c8ff7dee6


https://github.com/TryQuiet/quiet/assets/15381135/b25ee052-3ba9-402d-8eda-6248f2bd7efe

**Comment by kingalg** [comment]
desktop@2.0.1-alpha.0
This is definitely an improvement.

@holmesworcester we should consider graying out the button when it's not active. However what @siepra did here is in line with other fields that we are validating, so I still consider this issue as fixed. 

I think that "Continue" should be grayed out, but...
<img width="348" alt="Screenshot 2024-01-19 at 15 52 22" src="https://github.com/TryQuiet/quiet/assets/68909168/03bbccdd-a7d5-4767-9646-f06d1ab1caa8">
...it's in line with other fields that we are validating:
![image (5)](https://github.com/TryQuiet/quiet/assets/68909168/a613d421-dd08-4f22-9fd0-3a87c7e6a739)
