### ISSUE TITLE
Owner sees user as unregistered user even though the registration was successful

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#2169]
How to reproduce:
* Create community
* Turn off owner
* Turn on owner
* Join with new user
* Make sure that owner and new user are connected

Result: owner sees new user labeled as "unregistered"
Expected: if owner is connected to the new user, owner should not see the 'unregistered' label next to the username

Cause? 
Owner's frontend never receives updated list of certificates because it's stuck in certificates.store.ts `getCertificates` on `this.validateCertificate` in infinite loop waiting for `this.metadata`. `this.metadata` is being set only once when metadata is saved to db (so when Quiet is launched for the first time)

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/2171

**Comment by kingalg** [comment]
quiet@2.0.3-alpha.15

Fixed.
