### ISSUE TITLE
Jdenticon should be based on a public key and not username.

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2201]
Jdenticon should be based on a public key and not username.

Starting point - version 2.0.0 prod or 2.0.3-alpha.15

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/2207

**Comment by kingalg** [comment]
desktop@2.0.1-alpha.0
mobile@2.0.1-alpha.0 | iOS 346

Done

As you can see below - two different users with the same username (one of them is duplicated) have two different jdenticons:
<img width="328" alt="Screenshot 2024-01-19 at 15 46 01" src="https://github.com/TryQuiet/quiet/assets/68909168/3fab7f37-908d-43ed-915a-a1727e3f5e6a">
