### ISSUE TITLE
Add settings "three dots" for all users in channels - for exporting channels

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2204]
2.0.3-alpha.15

Only owner has access to three dots menu so only owner can export chats therefore only owner can export channels. 

Action: add "three dots" for all users in channels with an option of exporting channel messages.

<img width="570" alt="Screenshot 2024-01-09 at 17 16 19" src="https://github.com/TryQuiet/quiet/assets/68909168/58ced784-ae27-4ded-a78a-b592b5c879b6">

Remember that only owner should be able to delete channels

<img width="638" alt="Screenshot 2024-01-09 at 17 16 06" src="https://github.com/TryQuiet/quiet/assets/68909168/809c952a-79b9-4d4b-ac4f-42a13572229b">

**Comment by holmesworcester** [comment]
Note that the "delete" option should be hidden for non-owner.

**Comment by kingalg** [comment]
desktop@2.0.1-alpha.0

It's done, I was able to export chats as a user.
