### ISSUE TITLE
It shouldn't be possible to create a channel starting with dash. ("-")

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2215]
Desktop version: 2.0.3-alpha.15 (but according to Emilia it's an old bug)
mobile@2.0.3-alpha.17 (ios 344)

It shouldn't be possible to create a channel starting with dash or space but it is if another special character is used as first and space or dash as second.

If the user tries to use space or dash at the beginning they got correct error message:
<img width="644" alt="Screenshot 2024-01-12 at 14 58 34" src="https://github.com/TryQuiet/quiet/assets/68909168/5dcbf4ab-4113-47db-91a5-aea1610fe9bf">

However if they use any special character that is not allowed in channel name it's suddenly possible to create channel starting with a dash.

<img width="623" alt="Screenshot 2024-01-12 at 15 01 42" src="https://github.com/TryQuiet/quiet/assets/68909168/50822235-03af-4c49-bb9b-e0dd604a68a3">

<img width="431" alt="Screenshot 2024-01-12 at 14 57 17" src="https://github.com/TryQuiet/quiet/assets/68909168/b543c868-7e3a-4225-9d03-79e6ac366d3f">

**Comment by richardtorres314** [comment]
@kingalg I see this was moved to the backlog. Would it be possible for me to work on this? Thank you!

**Comment by holmesworcester** [comment]
@richardtorres314 please do! and generally it's okay to pick something up without our approval. Just ping one of us and we can assign it to you and move to "in progress"

**Comment by richardtorres314** [comment]
@holmesworcester Is this issue good to close? Thank you!

**Comment by holmesworcester** [comment]
Typically we wait until the issue is all the way through our QA process to close it, and @kingalg usually does this.

**Comment by kingalg** [comment]
@richardtorres314, thanks for taking care of this; I confirm that the user is no longer allowed to create a channel starting with a dash. We still need an error message there. Currently, it looks a little broken because the user doesn't get any feedback. It should probably be something like "Name cannot begin with whitespace or dashes," like in the screenshot below. I made a separate issue for that because I see that we are missing an error message also for special characters as well (#2322). If you are interested, you can pick this up, or someone from our team can handle this. 

https://github.com/TryQuiet/quiet/assets/68909168/f70219ff-e7ca-450c-a204-2d1691efb3e1
<img width="673" alt="Screenshot 2024-02-29 at 13 34 05" src="https://github.com/TryQuiet/quiet/assets/68909168/617f21bb-d5a9-489e-96f4-94baf2a6fd22">
