### ISSUE TITLE
Community name is hidden on "Create your community" screen

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2231]
Version: desktop@2.0.1-alpha.0
System: Windows, Linux, MacOS (problem does not occur on mobile versions)

Issue: Community name is hidden on "Create your community" screen. Users should be able to see name of the community they are creating. 

This bug is NOT present in any previous version (including production version 2.0.0).

When user want's to create their own community, community. name should be visible when they are typing. Below is correct version:
<img width="634" alt="Screenshot 2024-01-18 at 13 13 02" src="https://github.com/TryQuiet/quiet/assets/68909168/1c677940-6e90-4d71-bb3c-70157e344583">

Currently it looks like this:
<img width="632" alt="Screenshot 2024-01-18 at 13 15 52" src="https://github.com/TryQuiet/quiet/assets/68909168/53b076bc-372b-41c6-896b-ccff4b44d39e">

If there is space or dash in the name correct warning appears: 
<img width="645" alt="Screenshot 2024-01-18 at 13 16 14" src="https://github.com/TryQuiet/quiet/assets/68909168/9559941f-f851-4919-8384-a9ee97652f1f">

**Comment by siepra** [comment]
Please merge the fix into `/2.0.0` branch and then cherry-pick into `/develop`

**Comment by kingalg** [comment]
desktop@2.0.1-alpha.1
Fixed
