### ISSUE TITLE
Peer address of the peer that is sharing the invitee link is not included in the invite link

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2266]
desktop@2.1.1-alpha.0
mobile@2.1.1-alpha.0 | iOS 350
System: all

**Issue:** It can happen that the peer address of the peer that is sharing the invitee link is not included in the invite link. If this happens and none of the other users included in the invite link are online, new users cannot join the community. 

**Example:**
**This is the invite link generated by a peer:**
https://tryquiet.org/join#QmZJN1sofDCWkdG53Z8vmh3mzZGTSoSE9ThEszS7TSLpzY=bjjlqjw2yyi4yi3edyuotlbf4fs7h7wiamjtnzvbyass5beitnxhfcid&QmTqNNfZGLdhou9ZhJaEYyAU3brK6gzicXzxVhgQV9FDTm=6fpd6qyg7b2asrmhu5ywkzexypame5sltpiy5zpf7gjuazljsj7z3tad&QmShC1b3ZpNGtJ8JzbwMU9djqtovaMR6fou6AUdc3unh7U=6xerfdhia2noyuf6f6bwbkw4rlrtn4uxykzcpscctcumuijkdto4yxyd&k=0w8bXoV45v6giuCWv%2B2P0z7GNURbWjsdEfXyZ3Myu0U%3D&o=0329a60cf1590c253ffed0898aa8f4584a0c7c42a2f2daeda1608327695d30b644
**And this is his peer address:**
peer: QmTxxPfefm93WFbBYjPS9NeG3RT9YEr62hf9yJ6XmQJuwj

**Comment by EmiM** [comment]
I managed to replicate that on first try with only 5 peers in community (however I'm sure 4 is enough since we only add 3 peerId:onionAddress pairs to invitation link).
One of the peers doesn't have it's own pair in invitation link. 
It's probably because in redux `Connection` -> `peerStats` don't include its stats which causes peer address to land at the end of sorted peerList.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/2268

**Comment by EmiM** [comment]
Information for @kingalg: now local peer's (the one who invites) address should be first on the list of peers in invitation link.

**Comment by kingalg** [comment]
Version: 2.1.1-alpha.1
mobile@2.1.1-alpha.1 | iOS 351

**Fixed.** 

As @EmiM mentioned, the local peer's address is the first one on the list of peers. 
<img width="733" alt="Screenshot 2024-02-08 at 10 39 05" src="https://github.com/TryQuiet/quiet/assets/68909168/13b7ed71-30be-4e04-b702-90b74a51feca">
