### ISSUE TITLE
[DRAFT] Build a toy implementation of push notifications

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2269]
One wise suggestion was to build a minimal toy implementation of all the different parts of push notifications first.

This would use OrbitDB in the most minimal way to use a mocked Store & Forward Service and mocked Push Notification Service to receive push notifications. 

One way of articulating the goal is: 

1. Does it contain all the pieces, in their simplest possible form, to—when it works—convince us that our plan is sound?
2. Can an engineer outside the project look at a toy implementation and understand how our system works?

We can talk about the level of realism that would be the most helpful. For goal #2, ideally there would be minimal boilerplate. 

For example, we could build a maximally simplistic push notification service, store and forward service, and two clients in JS connected locally, with one OrbitDB for messages and one OrbitDB for community metadata.

Or we could build a single JS client (web or CLI) that uses functions to mock the different services, passing events between them.

We might consider building a maximally simple mock "Notification App Extension" in JS, to play its role of downloading, parsing, and validating messages and showing appropriate notifications based on the simplest possible user setting boolean (e.g. a boolean like isDirectMessage)

**Comment by siepra** [comment]
I like the idea of a minimal toy implementations in general, but for this specific case I don't think it fits the context. The greatest challenge is not to build the new ecosystem but rather to integrate it with already existing codebase (especially parts being affected by iOS lifecycle changes). Mocking services like app extension will probably only give us false impression of what we can do with them, as they won't be affected by OS's limitations, cutting resources etc. We can, of course, do it this way but it won't help much in my opinion.

**Comment by leblowl** [comment]
@holmesworcester are you okay with closing this? We aren't building a full toy, but we are building a very basic version of a vertical slice (invite link updates).

**Comment by holmesworcester** [comment]
Yes let's close!
