### ISSUE TITLE
[QUESTION] What does it mean to join the community?

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2282]
User receives the following data with the file downloaded from the server:

- Community metadata
- Peer address (to connect to)
- General channel

User injects this data into its local database and is being redirected to the channel list. Then it starts to try to connect to other peers.

**Comment by holmesworcester** [comment]
I would add "all peer addresses" just to be clear.

**Comment by leblowl** [comment]
When you say "general channel" are you talking about general channel messages?

**Comment by siepra** [comment]
> When you say "general channel" are you talking about general channel messages?

No, I'm talking about the general channel data structure, with it's id

**Comment by leblowl** [comment]
Can we consider this answered and close?

**Comment by holmesworcester** [comment]
Yes.
