### ISSUE TITLE
[QUESTION] Is resigning from using a server in scope?

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2285]
We should design the flow so that using a server is not obligatory. It's helpful to start with that assumption as making changes to the code later may be problematic (e.g. if we connected web socket endpoints in a rigid way).
There should be a configuration flag.

**Comment by holmesworcester** [comment]
> It's helpful to start with that assumption as making changes to the code later may be problematic

This sounds right to me.

**Comment by leblowl** [comment]
Can we consider this answered and close?

**Comment by holmesworcester** [comment]
Yes.
