### ISSUE TITLE
Greyed out registration message

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2293]
desktop@2.1.1-alpha.0

This is a regression. It was fixed in the previous version and resolved in issue: https://github.com/TryQuiet/quiet/issues/2172

Issue: When the user restarts the app, they see. a duplicated, gray out welcome message with their username.

<img width="789" alt="Screenshot 2024-02-09 at 15 42 01" src="https://github.com/TryQuiet/quiet/assets/68909168/c6f597b2-2bec-438c-af29-28b5c65b16f6">

**Comment by holmesworcester** [comment]
Let's make a test to catch this.

**Comment by kingalg** [comment]
Version: 1.2.1-alpha.9

@leblowl I still see a grayed-out message on mobile. So far, I haven't seen them on desktop. 

![324837BA-FA57-40B1-ABCC-4BB575047AB3](https://github.com/TryQuiet/quiet/assets/68909168/88833d35-fd54-4a96-a933-242fa58c8b29)

**Comment by holmesworcester** [comment]
Okay, let's fix this now then.

**Comment by kingalg** [comment]
Version: 2.1.2-alpha.11

@leblowl as you requested, this is the current situation: on iOS (I don't have a working Android) I still see a gray out message. What's more - I don't see a "real" registration message even when the user is registered. 

Have a look at below screenshots:
1. The first one is from an iOS user who joined the community. The registration message is grayed out, and there is no other registration message. 
2. The second is from the owner on iOS - you can see that the registration message for android user is missing and the user is registered (there is no "unregistered" label next to the username)
![864C5DB5-A23B-434F-8638-77A15B3E1A09](https://github.com/TryQuiet/quiet/assets/68909168/ab5e7af7-806c-4c26-ac8f-696ab3fc0853)
<img width="793" alt="Screenshot 2024-03-19 at 15 40 17" src="https://github.com/TryQuiet/quiet/assets/68909168/3d2b0cc5-1f4a-4f90-af64-f9a298b8a78d">


Note: None of this happens on desktop.

**Comment by kingalg** [comment]
Version: 2.1.2-alpha.12
Looks fine on desktop and iOS. I'll close this issue as soon as I can make sure that it's also working on Android (which is currently unavailable).

**Comment by kingalg** [comment]
Done on all systems.
