### ISSUE TITLE
Channel creation should show error message if channel cannot be created

### ISSUE THREAD

**Issue by richardtorres314** [TryQuiet/quiet#2299]
Currently, when a channel cannot be created because the channel name does not meet requirements (e.g. contains only special characters), the user does not receive an error message but is not able to create a channel (see below).

![Errorless Channel Creation](https://github.com/TryQuiet/quiet/assets/7980806/8fd7a4f5-b1e8-4e43-ae30-5a92ee7c132e)

The proposed fix is to add an error message in those cases.

**Comment by holmesworcester** [comment]
What would GitHub do in this case? 

Replacing special characters with hyphens (as we do with spaces) might make sense here.

**Comment by richardtorres314** [comment]
According to GitHub's naming convention:

* The repository name can only contain ASCII letters, digits, and the characters ., -, and _.
* A repository can start with any of the aforementioned characters (e.g. `-Test`)
* A repository can contain only a sequence of the aforementioned characters (e.g. `---`)
* Special characters are automatically converted to hyphens (e.g. `naïve` -> `na-ve`)

@holmesworcester I'll work on implementing the naming function accordingly and update the tests to reflect these cases. Let me know if any tweaking is required. Thank you!

**Comment by holmesworcester** [comment]
That sounds good and thank you!

**Comment by holmesworcester** [comment]
I'm adding this note on how to handle names in non-latin script for users (and possibly channel) without allowing homograph attacks. 

The idea is to have a list of tuples of "confusable" glyphs and let you use any of them, but block you from using one if another registered name is the same except for the confusable glyphs. 

https://unicode.org/reports/tr46/#Registries

Libraries like this one may help but I'm not sure yet: https://github.com/oozcitak/uts46

Here was the response I received to my question:

> look at IDNA2008 and UTS46. As a general rule, unicode is meant for display and not string comparison. Each protocol, that supports unicode tends to handle this differently... But usually they require conversion to "A-Labels" before comparing presented and reference identifiers. For example https://datatracker.ietf.org/doc/rfc9525/ & https://datatracker.ietf.org/doc/draft-ietf-lamps-rfc8398bis/. Part of the reason for UTS46 popularity is the common library support for it.

**Comment by kingalg** [comment]
Version: 2.2.0-alpha.0

It looks good. Well done, and thank you @richardtorres314 !
Special characters are exchanged for hyphens.
We validate for Latin characters and recognize similar-looking characters like [А]а and A (a) - Cyrillic and Latin. 

<img width="600" alt="Screenshot 2024-04-11 at 12 51 34" src="https://github.com/TryQuiet/quiet/assets/68909168/9b1a894e-efb5-453a-a465-5720d346d0b8">
