### ISSUE TITLE
Identicon inconsistent on profile edit page

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2304]
It looks like the identicon on the profile edit page differs from the one displayed next to messages in the channel. I think it should be generated with the user's public key in both cases.

**Comment by kingalg** [comment]
Version: 2.1.2-alpha.12
I'm not sure if this is the same or a separate issue, but user profiles look different on desktop than on mobile if they are not proportionate. Have a look, @leblowl 

This is the same user picture but screenshots are from desktop and mobile:
<img width="206" alt="Screenshot 2024-03-21 at 13 05 46" src="https://github.com/TryQuiet/quiet/assets/68909168/c70a0410-0da7-40d2-8b58-be8fb4105be9">
<img width="142" alt="Screenshot 2024-03-21 at 13 06 17" src="https://github.com/TryQuiet/quiet/assets/68909168/de8225fd-dd6f-408d-99a5-63831da9c1e5">

**Comment by leblowl** [comment]
Are you referring to the visual difference due to the border radius (corner rounding)? I think that can be a separate issue. Sorry this issue was pretty vague, but the inconsistency in this issue is referring to the actual image of the identicon which is the funny pattern it shows before adding a profile pic. There was a different pattern between the identicon in the left panel and the identicon in the profile panel (when editing).

**Comment by kingalg** [comment]
Thanks for explaining this! So those are separate issues. Screenshots are always useful in that kind of frontend issue and usually explain things quickly (although I might have added some description to mine, but yes, the new issue is more or less what you say).

**Comment by kingalg** [comment]
https://github.com/TryQuiet/quiet/issues/2395 - I prepared a new issue for but that I mentioned and closing this one.
