### ISSUE TITLE
License field in package.json shows ISC

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2309]
I think the license field in package.json should follow LICENSE.md.

**Comment by bhavyagor12** [comment]
@leblowl can i pick this up? 
to be clear are all package.jsons supposed to have?
```  "license": "GPL-3.0" ```
or a particular one?

**Comment by leblowl** [comment]
@holmesworcester any thoughts? This is referring to the `license` field in each package's package.json file: 

For example, the backend package says MIT: https://github.com/TryQuiet/quiet/blob/develop/packages/backend/package.json#L9

Here is the documentation for that field:
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license

And here are a list of license abbreviations:
https://spdx.org/licenses/

Example: `GPL-3.0` or `GPL-3.0-or-later`

**Comment by holmesworcester** [comment]
I think we should standardize on GPLv3 or later.

**Comment by leblowl** [comment]
@bhavyagor12 sounds like `GPL-3.0-or-later` and you can definitely do this if you like. Thanks!

**Comment by bhavyagor12** [comment]
@leblowl here is the PR for this, let me know if i have to make any changes ^
