### ISSUE TITLE
Refactor CREATE_NETWORK/LAUNCH_COMMUNITY

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2311]
It looks like we pass data to CREATE_NETWORK, just for the purposes of saving it to IndexDB, however it’s not used until calling LAUNCH_COMMUNITY. I think we can simplify things, where we pass things used by LAUNCH_COMMUNITY to it directly.

**Comment by kingalg** [comment]
Version: 2.2.0-alpha.2

Issue connected with refactoring changes. It's implemented and any potential bugs are reported in separate issues.
