### ISSUE TITLE
Joining from QR on iOS is failing

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#2324]
Version: 2.1.2-alpha - 362
System: iOS (it's possible that the same happens on Android, but I have not gotten a 2.1.2-alpha version for this system yet).

**Issue:** When the iOS app user tries to join the community from the QR code, most of the time, the application crashes - it closes itself after submitting the username, and upon reopening, the user will see the "Join Community" screen again.

**Steps to recreate:**
- try joining any community with a QR code from an iOS device

**Notes:**
- it doesn't happen every time, but most of the time - it was confirmed on two iPhones,
- it only happens with a QR code; joining with a link, both passed directly and used as a button from the website, are working fine,
- whether the user is joining with the owner online or offline doesn't affect this issue - it happens in both cases,
- this issue occurs for both, fresh Quiet users when they first try to join the community and for users who leave and try to join the community.

**Comment by holmesworcester** [comment]
@kingalg this is in production or it's blocking release?

**Comment by holmesworcester** [comment]
@siepra could this be related to the RN upgrade?

**Comment by kingalg** [comment]
@holmesworcester This is in the alpha version; it's not in production (at least I did not spot it there, there is always a small chance that I was just lucky because it doesn't happen every time, but it happens often enough for me to be fairly sure that it's a new issue). In my opinion, it does block the release because it makes the simplest way of joining on iOS almost unusable.

**Comment by holmesworcester** [comment]
This is weird because it should be the same link.

Maybe we didn't update the QR code invite link?

**Comment by kingalg** [comment]
I re-checked the previous version and joined with the QR code 4 times without any issues (it took some time, tor is slow today, but besides that, there was no crushing). So this is something new introduced with 2.1.2.

**Comment by holmesworcester** [comment]
Do we have a mobile e2e test for this? @siepra

**Comment by leblowl** [comment]
After looking into it, I think this is a duplicate of https://github.com/TryQuiet/quiet/issues/2352

It appears that if you open the app and then put it in the background, and then scan a QR code/click a Quiet invite link, then it will open the app again (which causes the Tor control port to be refreshed) and that updated port wasn't being used in the backend. I was able to reproduce this, however without logs, it's difficult to know for sure if we are talking about the same error, but we can test again in the latest pre-release.

PR: https://github.com/TryQuiet/quiet/pull/2360

And @holmesworcester no mobile tests do not test the joining path yet, only community creation

**Comment by kingalg** [comment]
@holmesworcester @leblowl 
This looks the same as #2352, and I can close both. Lucas caught the criteria for another issue—the app gets stuck on "Connecting to community members via Tor" if the user first opens the app, then puts it in the background and tries registering, for example, from QR core. I've created an issue for that: #2373 

I'm not 100% convinced if this and #2373 are the same issue. They may look different on the frontend now—in this case, the app turned off completely, and in #2373, it's forever stuck on one screen—but they are both starting to act up at the same moment—after the user tries to register a username.
