### ISSUE TITLE
QSS: Move community creation to backend

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2329]
We can add a couple new keys to IndexDB to mirror the frontend state: COMMUNITIES, CURRENT_COMMUNITY_ID

For existing Quiet users, we can migrate the existing community store data to IndexDB during launchCommunityFromStorage.

For new Quiet users, we can add a “name” field to InitCommunityPayload, createCommunity can then create a CA and create a Community object.

We can refactor launchCommunity to receive a Community object and create a new joinCommunity function that can also create a Community object and pass it to launchCommunity. We can rename LAUNCH_COMMUNITY to JOIN_COMMUNITY and connect it to the joinCommunity function.

When createCommunity/joinCommunity create a Community object, it should be saved in the DB and then returned to the frontend via an acknowledgement on CREATE_COMMUNITY/JOIN_COMMUNITY. The frontend can then save it to its state.

Now if we really want to make the backend the source of truth for the Community model, we need to also make sure the backend Community model gets updated whenever the frontend updates its model. There are a few places where this occurs.

OWNER_CERTIFICATE_ISSUED updates the ownerCertificate field. So on the backend before sending this event, we can update the Community model in IndexDB.

COMMUNITY_METADATA_STORED, LIBP2P_PSK_STORED and PEER_LIST are other events where we would do something similar.

Perhaps in a future iteration, we can emit a COMMUNITY_UPDATED event whenever the community is updated on the backend, instead of using events for individual pieces of data like LIBP2P_PSK_STORED and PEER_LIST.

**Comment by kingalg** [comment]
Version: 2.2.0-alpha.2

Issue connected with refactoring changes. It's implemented and any potential bugs are reported in separate issues.
