### ISSUE TITLE
Users can't use jpg's for profile photos

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2332]
Steps to reproduce on Ubuntu:

1. Click profile in bottom left
2. Click "Edit photo"
3. Try to select a .jpg 

Expected: it works
Actual: JPG isn't visible in file picker.

**Comment by kingalg** [comment]
Version: 2.2.0-alpha.0

Done.
System: jpg's can be added on Windows, Linux and MacOS and they are visible as avatars on all systems (including iOS and Android).
