### ISSUE TITLE
Fix mobile e2e tests

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2390]
Mobile e2e tests are failing on our test runner. 

Notes here: https://zbay.slack.com/archives/G01EHE6JHCM/p1711459496510139

**Comment by holmesworcester** [comment]
Possible duplication of #1876

**Comment by siepra** [comment]
I'm closing due to the fact that Detox tests are now generally failing on develop branch.
We also decided to move Detox tests to GitHub hosted runner (Apple Silicon)
