### ISSUE TITLE
Can't send messages after user disconnects and reconnects

### ISSUE THREAD

**Issue by islathehut** [TryQuiet/quiet#2412]
The issue is essentially that when you have multiple users connected at once and one disconnects and reconnects the other users lose their ability to send messages at all.

Screen recording of the bug: https://drive.google.com/file/d/18ip1r79alGDwuN8uPI3Lr24CmE-dVFR7/view?usp=drive_link

Steps to reproduce:
1. Login with three different clients on the same community
2. Verify that messages can be sent between them
3. Disconnect the owner
4. Attempt to send messages from the other two clients - this should work
5. Reconnect the owner
6. Attempt to send more messages from the other two clients - this should not work

**Comment by holmesworcester** [comment]
This should be fixed by #2419
