### ISSUE TITLE
Fix iOS ports issue on return from background

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2424]
When we go to background on iOS, we close Tor and get a new port. When we resume, libp2p hangs trying to connect to the old port that nothing is listening on and we don't receive any ECONNREFUSED errors. One way to resolve this is to close any existing connections when we go to background or when we resume.

Note:
We initially fixed this by having a timeout, but the timeout requires that we a) set it very short and risk that sometimes we are timing out too early b) set it to something conservative (2 mins?) which then means that we will wait 2 mins before even *trying* to connect when we return from background, meaning that iOS devices will almost never successfully connect on the p2p network.

**Comment by holmesworcester** [comment]
@leblowl can you fill this in?

**Comment by kingalg** [comment]
376

Fixed (it's syncing slow, but after some time it does sync)
