### ISSUE TITLE
Sending message before channel is ready

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2425]
I've noticed this only on mobile. It seems like it's possible to send a message before the channel is ready on the backend:

```
Could not send message. No 'gdd_sanrvlucq29c77v4' channel in saved public channels
```

And we don't have any retry functionality. Perhaps this is more easy to do now because we've just removed code and things are quicker, or perhaps a safeguard was removed accidentally. I'm not sure.The result is that a message is greyed out indefinitely and then messages sent after that are also greyed out even though they send properly.

The easiest fix might be to wait until the channel is ready by listening for a CHANNEL_REPLICATED event or similar.

**Comment by kingalg** [comment]
@leblowl, if I understand correctly, it's not something that I can check, so I need to believe your and reviewers' words that it's implemented correctly. Who did a review of mr for that?

**Comment by kingalg** [comment]
@leblowl ping

**Comment by kingalg** [comment]
mobile@2.2.0-alpha.7 | iOS 376

Fixed. Retry function added.
