### ISSUE TITLE
UI Theming and Style Refactoring on Desktop Client

### ISSUE THREAD

**Issue by mike-kiss** [TryQuiet/quiet#2445]
In order to prevent drift in the UI and to prepare for Dark Mode, some refactoring and consolidation is needed. This work should have very little impact on the UI - it mostly involves the following:
- Consolidating colors and removing hard-coded hex values throughout the UI code
- More closely following MUI theme conventions (e.g.: using the 'shadows' theme object)
- Using semantically named colors wherever appropriate (e.g.: using a background color instead of '#fff', using 'border01' for borders instead of 'lightGray')
- Eliminating unused colors and other theme clutter

Some consultation with design friends will be needed to make sure we are building out the theme in code according to what they envision. This work will likely want to happen iteratively in chunks rather than all at once.

**Comment by holmesworcester** [comment]
I think this was released?
