### ISSUE TITLE
Creating a channel is broken

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#2457]
Branch: develop

Steps to reproduce:
1. Create a community
2. Create a channel

Expected behaviour:
The app goes to the newly created channel screen

Actual behaviour:
The button spins infinitely on "create channel" screen

Detox tests caught that

**Comment by holmesworcester** [comment]
If this is happening in the release candidate we should move this issue to the current sprint.

**Comment by siepra** [comment]
I'm not sure if it affects release candidate. It's not deterministic and I don't know yet what the factor is

**Comment by siepra** [comment]
It turned out to be a problem with web socket connection mechanism adjustments for Detox testing purpose. It doesn't affect release candidate and it's going to be fixed on develop soon
