### ISSUE TITLE
Creating a community is broken

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#2464]
Branch: develop

Steps to reproduce:

1. Launch the app
2. Enter community name
3. Enter user name

Expected behaviour:
The app goes past the connection screen and displays newly created community's channel list

Actual behaviour:
The app gets stuck on connection screen

Detox tests caught that

**Comment by holmesworcester** [comment]
Does this happen every time? Let's fix it now and put it in current sprint if so!

**Comment by siepra** [comment]
It turned out to be a problem with web socket connection mechanism adjustments for Detox testing purpose. It doesn't affect release candidate and it's going to be fixed on develop soon
