### ISSUE TITLE
Backend starting before the frontend is ready, resulting in missed events

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2471]
Backend was starting before the frontend was ready on Android. This resulted in missing a CHANNEL_SUBSCRIBED event and thus not being able to send a message (having it greyed out indefinitely). It looks like Android connects with native code to the backend in order to get push notifications which causes the backend to start, then the actual frontend code connects and by then it's missed the CHANNEL_SUBSCRIBED event.

**Comment by kingalg** [comment]
mobile@2.2.0-alpha.6 

Fixed. I didn't observe behaviour associated with this issue in recent alphas.
