### ISSUE TITLE
Leaving and rejoining a community causes failures

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2476]
Steps to reproduce:

Leaving a community and rejoining multiple times causes predictable failures.

**Comment by holmesworcester** [comment]
Notes from Wiktor:
* If the failure is on mobile only, it may make sense to first look at how the mobile app stores redux state

**Comment by holmesworcester** [comment]
Note: wait until @leblowl merges his latest work before picking this up. Assigning to him until he merges.

**Comment by kingalg** [comment]
2.2.0-alpha.7 
mobile@2.2.0-alpha.7 | iOS 376

Fixed. Checked on all supported systems.
