### ISSUE TITLE
App can get stuck on 'Loading messages' when joining

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2496]
I think this can happen on any platform, but has happened recently on iOS and Android. The logs for Android show everything working correctly, but the certificates don't sync, even after 10 minutes. 2 peers were connected. I restarted the app and sent a message (restarting allowed me to access the general channel even though nobody was registered due to missing certs) and it took 20 minutes for the message to arrive at another peer. Certs still haven't arrived yet. Looks like slow network conditions. This doesn't happen often for me, but to investigate there are additional logs related to the gossipsub, libp2p, OrbitDB that we can enable.

**Comment by kingalg** [comment]
mobile@2.2.0-alpha.7 | iOS 376

Fixed (or at least I didn't encounter any problems with this in this and previous alpha - joining took a long time but it was completed and synced without need of restarting).
