### ISSUE TITLE
Stuck on splash screen on first start (fresh install)

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2511]
I got this error: `'WEBSOCKET', 'Waiting for crypto engine to initialize'`

Has only happened once.

**Comment by kingalg** [comment]
mobile@2.2.0-alpha.7 | iOS 376

Never happened to me and I assume that as you fixed multiple things around installation this issue is fixed. If I encouner it in the future, we can reopen this issue or create a new one.
