### ISSUE TITLE
Stuck on splash screen when leaving community

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2512]
Get's stuck closing OrbitDB every now and then. Could be related to https://github.com/TryQuiet/quiet/issues/2452

**Comment by kingalg** [comment]
@leblowl on which platform did it happen to you? I don't see this issue in this version (Version: 2.2.0-alpha.6) but I can check a few more times on a platform where you found it. I already confirmed that after 7 tries on android I didn't encounter this issue so I'll most probably be also closing #2452

**Comment by leblowl** [comment]
It should be fixed in 2.2.0-alpha.6. I'm not sure if this happened on iOS or Android.

**Comment by kingalg** [comment]
mobile@2.2.0-alpha.6 | iOS 375

I'm not seeing it anymore. Yesterday I spend all day mostly joining and leaving communities on all platforms and I there was no problems with leaving community at all. I consider it fixed.
