### ISSUE TITLE
Entire user profile area should be clickable, in bottom left

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2566]
Right now it's sort of fiddly to open your user profile because, in the bottom left of the sidebar, only the username and avatar is clickable. 

The whole area should be clickable, and the hover state should change to reflect this.

**Comment by okrayum** [comment]
Hello,
Jason here. 
I have a question in general. 
Do I need to be assigned an issue to work on it? If so may I please be assigned this issue?
Thanks!

**Comment by holmesworcester** [comment]
Apologies for the slow reply here!

@okrayum you're welcome to proceed on an issue without it being assigned (just leave a comment) but I'll also assign this to you!

**Comment by kingalg** [comment]
Thanks for your contribution @okrayum !

Version: 2.3.1-alpha.1
System: Linux, MacOS, Windows

Done.

**Comment by okrayum** [comment]
You're Welcome @kingalg .
