### ISSUE TITLE
Fix sidebar hover states

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2567]

**Comment by jgaylor** [comment]
Here are the missing sidebar interactions. [Figma](https://www.figma.com/design/0j7Nna9zWmfOSNmRmQK1Uh/Quiet-Design-Library?node-id=3797-16113&t=7637AQ8prqRN7zU8-4)



![Image](https://github.com/TryQuiet/quiet/assets/15039182/6d3f816e-0398-4ee3-a257-0525477da480)

**Comment by adrastaea** [comment]
This seems to be fixed with #2566

**Comment by kingalg** [comment]
It was already resolved and checked in this issue: https://github.com/TryQuiet/quiet/issues/2576
