### ISSUE TITLE
Fix color contrasts in new Quiet sidebar design

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2576]
Some colors didn't pass contrast checks for accessibility. 

Here’s the latest modes in Figma to fix the issue: https://www.figma.com/design/0j7Nna9zWmfOSNmRmQK1Uh/Quiet-Design-Library?node-id=5439-61669&t=mgtsk4nW4b5pZ3u4-1

**Comment by kingalg** [comment]
Version: 2.2.1-alpha.1
System: Linux, MacOS, Windows

Done.
