### ISSUE TITLE
Owner cannot send messages

### ISSUE THREAD

**Issue by Juul** [TryQuiet/quiet#2587]
Sending a message did nothing except for the typed message disappearing from the text input box. The message did not even appear in the chat box on the owner's own device after sending. This was tried both before and after the first other person joined the community and had the same result.

Re-starting the app did not fix the issue. Restarting the entire device did fix the issue.

Version: Android 2.2.0 release
System: Latest stable GrapheneOS without Google Play Services
Connectivity: Tried both wifi and LTE

**Comment by holmesworcester** [comment]
@Juul thank you for reporting this. We have not tested on a wide range of Android devices yet and it is possible Quiet is simply broken on your device. What device model do you have?

@kingalg can you work with this user to reproduce the issue?

**Comment by holmesworcester** [comment]
@kingalg graphene only supports Pixel, so this is happening on a Pixel, just not sure which one yet.

**Comment by Juul** [comment]
The phone for the original bug report was a Pixel 7a. The latest stable GrapheneOS that's running on this device is Android 14.

We managed to replicate the bug on a different device under different circumstances. The same bug occurred on a OnePlus 3T running LineageOS 17.1 (Android 10) and this time it occurred not for the owner but after the user opened the app and joined their first chat after installing Quiet. This time force quitting Quiet and re-starting did fix the issue so it seems likely that I somehow didn't manage to actually force quit Quiet properly on the GrapheneOS device.

Note that neither device had Google Play Services nor MicroG installed. I would assume that this bug can be replicated on any Android without Google Play Services / MicroG.

After restarting Quiet it has been working correctly since then on both devices.

**Comment by kingalg** [comment]
Thank you for all the details, @Jull, they are very helpful. Luckily Pixel 7a is one of our testing devices so I should be able to replicate this bug as soon as I install GrapheneOS.

**Comment by kingalg** [comment]
@Juul @holmesworcester 

I used Pixel7a with GraphenOS (android 14) and Quiet installed from APK downloaded from try quiet website.

As you can see on recordings below at first the Owner could send messages when they were the only User and could send and receive messages once another User joined.

After I restarted the app a few times I run into the bug you described. 


Whenever I try to send a message I'm getting this: 08-08 16:22:37.094  1279  2538 D CoreBackPreview: startBackNavigation currentTask=Task{4701633 #36 type=standard A=10147:com.quietmobile}, topRunningActivity=ActivityRecord{5139797 u0 com.quietmobile/.MainActivity t36}, callbackInfo=OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@664f72a, mPriority=0, mIsAnimationCallback=false}, currentFocus=Window{ea70638 u0 com.quietmobile/com.quietmobile.MainActivity} 

Full logs in the attachment. 
[logs080824.txt](https://github.com/user-attachments/files/16549710/logs080824.txt)
 

https://github.com/user-attachments/assets/bf139969-6f1f-4120-8db6-6787a867821e
https://github.com/user-attachments/assets/4a43fae6-6108-461f-bc0c-054ce55a5aee


Edit: this also happened when I installed Quiet from APK on my standard Android.

**Comment by holmesworcester** [comment]
Can you confirm that you can't reproduce it when installing from Google Play?

**Comment by kingalg** [comment]
I can't reproduce it when I'm installing from Google Play, but we had this issue with disappearing send message before. I'm going to check if I can find it somewhere in old issues.

**Comment by kingalg** [comment]
Version: 2.3.1-alpha.1
System: Android and installation from SDK

Fixed.
