### ISSUE TITLE
How come two latest version numbers? repo: 1.9.7, website: 2.2.0?

### ISSUE THREAD

**Issue by wwwhtml** [TryQuiet/quiet#2590]
How come two latest version numbers? 
repo: 1.9.7
website: 2.2.0

**Comment by holmesworcester** [comment]
Thanks for catching this! 

What repo link are you referring to? In the [readme](https://github.com/TryQuiet/quiet) I see an outdated link to an older release, but to 2.01 not 1.97. Updating that link now.

I also updated [PUBLISHING.md](https://github.com/TryQuiet/quiet/blob/develop/PUBLISHING.md) which was missing a reminder to update that "Downloads" link in the readme.  

@leblowl @ikoenigsknecht @adrastaea -- a reminder to anyone doing the releases that there are a few different places we need to make manual updates after the latest release.

**Comment by wwwhtml** [comment]
It is on the README file. The Getting Started section has a the link labeled “latest release” that still points to the 1.9.7 version. 


“Getting started

To try Quiet, download the [latest release](https://github.com/TryQuiet/quiet/releases/tag/quiet%401.9.7) for your platform (.dmg for macOS, .exe for Windows, etc.) and install it in the normal way. Then create a community and open the community's settings to invite members.”

Thank you for looking into it.

**Comment by holmesworcester** [comment]
Thanks. Fixing and adding this note to the PUBLISHING.md doc.

**Comment by holmesworcester** [comment]
I linked to the downloads page on the website to avoid future oversights.

**Comment by kingalg** [comment]
@holmesworcester this is closed for over a year and definitely looks like done to me. I'm moving it to "done".
