### ISSUE TITLE
Move Identity model to the backend

### ISSUE THREAD

**Issue by leblowl** [TryQuiet/quiet#2602]
Move Identity model storage to backend. Find all places on the frontend where Identity model is updated and move those to backend and emit an IDENTITY_UPDATED or similar event to notify the frontend if the frontend needs that information.

**Comment by kingalg** [comment]
As per my discussion with Taea, she confirms that this change was implemented in Version 2.3.2-alpha.6, which was checked by me, is working, and has been approved for release to production.
