### ISSUE TITLE
Persist Sigchains across Instances

### ISSUE THREAD

**Issue by adrastaea** [TryQuiet/quiet#2626]
## Description
The sigchains initialized by the SigChainManager should be able to be saved to persistent storage and loaded when the relevant community is launched. 
## Acceptance Criteria
1. Initialize with community creation/launch
1. Save to SIGCHAIN key in LevelDB when app closes and when chain is initialized
1. Load from LevelDB when launched
1. Tests created for verifying initialization, saving, and loading

**Comment by kingalg** [comment]
Applied in version - 2.3.3-alpha.1 - checked and released.
