### ISSUE TITLE
User can join community on mobile (on iOS)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#267]

**Comment by siepra** [comment]
Logic from RegisteringUsername container (desktop frontend) must be moved to nectar and shared on mobile

**Comment by siepra** [comment]
Needs to be done first https://github.com/ZbayApp/monorepo/issues/302

**Comment by siepra** [comment]
The first part (bringing functionality on Android) has been done in this PR https://github.com/ZbayApp/monorepo/pull/323

**Comment by siepra** [comment]
Blocked by #298

**Comment by holmesworcester** [comment]
Ignore this comment!
<img width="904" alt="image" src="https://user-images.githubusercontent.com/213678/177447638-29d6805c-5458-4f5e-b4ed-7a5d6cb51f6e.png">

**Comment by siepra** [comment]
Despite hitting call stack limit for verifyMessage method at initial sync, I was able to join the community. iOS app is not usable yet as it needs adjustments but I think we achieved the goal of this task

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/913
