### ISSUE TITLE
Users should not be able to submit an invalid username on mobile

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#270]
We should have the same validation rules for username and channel name on mobile as on desktop.

Ideally the validation code should be shared.

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/877

**Comment by siepra** [comment]
![Screenshot_2022-09-05-18-36-39-242_com zbaymobile storybook debug](https://user-images.githubusercontent.com/15381135/188492375-09a4727c-90e1-4cf4-ae4e-40d5c1594f4d.jpg)
![Screenshot_2022-09-05-18-36-55-578_com zbaymobile storybook debug](https://user-images.githubusercontent.com/15381135/188492378-2e5f9c23-1e9f-4e1d-b91e-88466d5e9d56.jpg)

**Comment by holmesworcester** [comment]
looks good

**Comment by kingalg** [comment]
v 0.8.4

Checked and working.
