### ISSUE TITLE
Connect to already running Tor process on mobile

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#296]
I think it's crucial for several reasons:
1. User may have already been using a Tor service (e.g. Orbot) - atm it'll collide with our application
2. OS is in charge of killing processes when running out of resources. It means we cannot guarantee our key processes running simultaneously all the time. We should think of them as a separate things that can connect to each other when needed, to preserve flexibility
3. Spawning new Tor process may collide with the one already running, crashing application at start time (reliability issue)

**Comment by EmiM** [comment]
I ran into (probably) related error while trying to retry registrating username. It's quite annoying

```
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE: Error: TOR: Connection already established
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at /data/user/0/com.zbaymobile/files/nodejs-project/lib/torManager/TorControl.js:30:28
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at new Promise (<anonymous>)
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at TorControl.<anonymous> (/data/user/0/com.zbaymobile/files/nodejs-project/lib/torManager/TorControl.js:28:26)
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at Generator.next (<anonymous>)
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at /data/user/0/com.zbaymobile/files/nodejs-project/lib/torManager/TorControl.js:8:71
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at new Promise (<anonymous>)
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at __awaiter (/data/user/0/com.zbaymobile/files/nodejs-project/lib/torManager/TorControl.js:4:12)
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at TorControl.connect (/data/user/0/com.zbaymobile/files/nodejs-project/lib/torManager/TorControl.js:27:16)
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at TorControl.<anonymous> (/data/user/0/com.zbaymobile/files/nodejs-project/lib/torManager/TorControl.js:62:24)
08-17 14:13:29.959 27190 27389 E NODEJS-MOBILE:     at Generator.next (<anonymous>)
08-17 14:13:29.964 27190 27381 E nodejs  : /data/user/0/com.zbaymobile/files/nodejs-project/lib/libp2p/connectionsManager.js:232
08-17 14:13:29.964 27190 27381 E nodejs  :             throw new Error();
```

**Comment by siepra** [comment]
We'll bind tor process to main application thread (instead of running it in background task) so I think all related problems should disappear. Although it'd be good to confirm that

**Comment by vinkabuki** [comment]
Didn't solve my problems so I suppose it didn't help

**Comment by siepra** [comment]
We need to gather more information about tor process

**Comment by holmesworcester** [comment]
I'm moving this to mobile backlog and we can return to it if we suspect it as a cause

**Comment by siepra** [comment]
I don't think this one is accurate anymore
