### ISSUE TITLE
Missing libnss3 dependency in ChromeOS, possibly other linux variants

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#306]
Steps to reproduce:

On default chrome linux setup on a Chromebook (and possibly other linux variants) run Quiet.

Expected: it runs

Actual: throws error for missing libnss3.so

`apt-get install libnss3` solves the problem and Quiet runs normally.

**Comment by vinkabuki** [comment]
It is common problem on linux distros, I've just encountered it when running Cypress CI, but I never had this on my local machine (Or I've configured it a long time ago and I don't remember)
