### ISSUE TITLE
Links should be linkified and clickable

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#320]
Let's just make links clickable. 

I created a security issue for adding warnings so that we'll add them later: #321  

But for initial dogfooding and testing links need to be clickable or we'll annoy ourselves so much!

**Comment by siepra** [comment]
<img width="620" alt="Zrzut ekranu 2022-07-15 o 11 36 13" src="https://user-images.githubusercontent.com/15381135/179197208-2829b48d-ea81-4045-9625-4a095d1cdf45.png">
<img width="620" alt="Zrzut ekranu 2022-07-15 o 11 36 19" src="https://user-images.githubusercontent.com/15381135/179197211-449f37e5-2776-45e2-b6e7-754ce1c34368.png">

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/717

**Comment by kingalg** [comment]
0.9.7-alpha.7

Done.
