### ISSUE TITLE
Didn't see others' messages

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#334]
Quiet started up and showed past messages, but my new messages were not visible to others and their new messages were not visible to me. 

Logs shared with @vinkabuki

**Comment by kingalg** [comment]
moved back as per discussion with @vinkabuki

**Comment by kingalg** [comment]
@holmesworcester do you still experience this issue? @vinkabuki do you remember if this is something that we fixed?

**Comment by holmesworcester** [comment]
This is probably fixed by now, yes.
