### ISSUE TITLE
User should be able to see whether Tor is connected

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#335]
Right now, if I'm completely offline, Quiet doesn't tell me that and I can send messages but no one will see them.

Quiet also does not tell me if there's an error connecting to Tor.

We could bring back the online status indicator light and show Tor connection status with a green, red, or yellow light. (Yellow = not connected to any peers?) 

Or we could simply show a red or green light to indicate connectedness to Tor.

**Comment by kingalg** [comment]
This is a duplicate with https://github.com/TryQuiet/quiet/issues/1673 As the other issue has more detailed description and Kacper is already working on it I'm closing this one as a duplicate.
