### ISSUE TITLE
Missing icons on Android devices

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#346]

**Comment by holmesworcester** [comment]
@siepra can you add a little detail here

**Comment by siepra** [comment]
Sometimes there're no icons loaded in android application (e.g. send message button or username created icon). It's happens randomly but it seems related to https://github.com/TryQuiet/quiet/issues/415 - I mean it's easier to reproduce in mature community

**Comment by holmesworcester** [comment]
Can't reproduce. Bartek says it's happening on fresh communities and Wiktor says it's happening on mature communities. Maybe it's a result of our async storage and perhaps it is fixed by introducing filesystem redux persist.

**Comment by Dinek007** [comment]
i tried to reproduce this bug in both small and large community (quiet-team), tried with application in background for a long time, tried with spamming messages, spamming images, scrolling a lot, reopening app many times, with phone big ram usage and cant reproduce this bug

**Comment by siepra** [comment]
I think it may have something to do with a fresh install (uninstall he app and then install it again). It happend to me on 22nd of September

**Comment by siepra** [comment]
I think this link can be helpful https://stackoverflow.com/questions/39385129/react-native-images-not-showing-in-android-device-but-shows-perfectly-in-emula

Maybe it's just a problem of debug version and we don't need to worry about it?

**Comment by siepra** [comment]
I'm closing it as it seems to be affecting only debug builds
