### ISSUE TITLE
User should be able to create a community on mobile

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#361]
Users should be able to create communities on mobile.

We're adding this now for the narrow purpose of simplifying testing on mobile, so it doesn't have to be perfect.  However, the user should be able to copy the invite code, otherwise they will have a community that is impossible for anyone else to join.

The #general channel should be created by default as on desktop. 

If creating channels is necessary for testing we should add that too. If it isn't, let's save it for future work. 

Designs are here: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-(and-prototype)?node-id=454%3A13322&t=HcWB26cI6HENgDUi-4

**Comment by holmesworcester** [comment]
@siepra @EmiM let's have a quick conversation before we do this about ways we could automate this or generally decrease the cost of manual testing without having to implement features

**Comment by holmesworcester** [comment]
We can merge and release this whenever the team is comfortable doing so.

**Comment by kingalg** [comment]
mobile@1.2.1-alpha.6 

I've successfully created several communities on iso and android and everything was working as expected.
