### ISSUE TITLE
Lazy loading messages on mobile

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#364]
It will be much easier than on frontend as React Natives' FlatList component provides methods for handling it

**Comment by holmesworcester** [comment]
If this gives us any trouble at all we should look for some shortcut, such as showing all messages or all messages up to some limit.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/825

**Comment by kingalg** [comment]
v 0.8.4

I don't see any issues with this.
