### ISSUE TITLE
community owner should be able to delete channels

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#400]
Right now no one can remove channels, so our workspace just gets more and more cluttered with meaningless or obsolete channels. 

The most important stuff:
1. The community owner should be able to remove channels, on desktop. 
2. Only the owner has this ability 
3. Deleting a channel should communicate to all other community member devices that the channel should be deleted.
4. On desktop and mobile, all member devices should stop loading and syncing this channel, so that it has no impact on performance anymore. (this is the most important thing because channel size is causing a performance problem)
5. Channel should disappear from UI
7. All requests to delete channels signed by non-owner should be ignored as invalid
9. We have a design for a "three dots" menu in the top right of the channel view. This can have a single item: "Delete channel".
11. The user should get a confirmation dialog "Delete #channel-name? This cannot be undone. [Yes / No]"
11. Deleting the general channel should erase all messages but create a new #general channel so we have a place to put "joined" messages e.g..

Additional requirements (non-urgent but important, so make issues for these if we don't do them now):

6. Deleted messages should be deleted from all devices, with the channel name. Tests confirm that no local data about the channel can remain or be synced with any user once the channel is deleted. 
8. Owner should be able to remove channels on mobile
9. We should show a special message similar to our "Channel created" message in #general that the channel has been deleted, e.g. "@holmes deleted #channel-name". If general is deleted this should appear in the new #general 

UPDATE: As discussed, I created separate issues for the access controller, for attachment file deletion, and for attachment IPFS block deletion: #1489, #1490, #1491

**Comment by holmesworcester** [comment]
If there's a way to split this up into parts that multiple people can work on, that would be ideal. Possible split:

1. backend deletion api stub
2. frontend screens using api
3. marking channel deleted, sending to others
4. hiding deleted channels in UI
5. true deletion of deleted channels
6. validating that deletion request is sent by owner

**Comment by siepra** [comment]
Here is how it looks like on mobile, with swiping gesture

https://user-images.githubusercontent.com/15381135/234301049-4b4eed3e-250b-4be1-9cd6-de0c47c26630.mp4

**Comment by holmesworcester** [comment]
This looks good! If the other version works better with e2e tests then let's use that instead but this is totally good.

**Comment by Kacper-RF** [comment]
Desktop version, for deletion general channel I had to add a modal with info, to prevent jumping channel list.
Also i had conversation with Bartek, and is possibility that we also will use that modal to block UI to prevent user to double click on channel deletion in case that is lot of files on channel 

https://user-images.githubusercontent.com/111343884/234493858-45ff8c25-d931-471c-8123-53fad389e5b1.mp4

**Comment by Kacper-RF** [comment]
Thanks for feedback !

1. Yes, sure that's better, i will do it in that way

2. You are right, I don't know at the moment, that i will can not deleting channel from channel list in sidebar UI while doing that all deletion stuff in sagas, but for sure I will change logic with blocking all users with this modal while general is recreated, I will try to find solution some for inactive general channel with lower opacity.

3. I talked with Bartek and if there are lot of big files in channel, that can be time consuming, so maybe solution is only blocking deletion button on this channel, to prevent double click and not showing any modals.

**Comment by vinkabuki** [comment]
1. IPFS uses content addressed data, which means that there is a risk that different files share some blocks.
     * We must add mechanism for keeping track how many files reference a given block and do not delete it if there is more than one reference
     * Before we do that, let's investigate it a little bit more, because there is a chance that ipfs itself can somehow deal with that.
2. Access controllers
     * Just figure out how to derive peerid from identityProvider identity.
     * Adding access controller to exisiting database results in orbitdb assumes it's new database.
3. Files are stored multiple times - this is not critical problem at this point.
     * We store it in DATA_DIR/temporary files and DATA_DIR/downloads, I think temporary files should be erased once file uploaded.

**Comment by holmesworcester** [comment]
This looks great! I want it to say "@kacper created #dev" as the first message in #dev too, but that's totally out of scope. If trivial it might be nice to to it now while we're here. If not trivial, we'll do it later.

**Comment by Kacper-RF** [comment]
yes, of course, i will add that change to my current PR with deletion fixes

**Comment by kingalg** [comment]
Version: 1.2.1-alpha.3

There are some problems that are addressed in other issues, most important one is: #1523 but in general this functionality is implemented and in most cases can be used as expected.
