### ISSUE TITLE
Enable Sentry and fix e2e test running on CI

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#408]
e2e test fails when on try to switch joinCommunityModal to createCommunityModal. It works locally, and there is no error message what is not working.

**Comment by siepra** [comment]
The problem lays in modals ordering (sentry warning modal causes the problem). 
Sentry is disabled at this moment - this serves as a workaround

**Comment by siepra** [comment]
Sentry should also be fixed as we found out it's not working correctly anyway
