### ISSUE TITLE
Write e2e test for lazy loading messages

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#412]
verify that:

- messages are forgotten on scroll down (or whenever makes sense)
- messages are forgotten on channel switch
- messages are loaded on scroll up
- channel switching is fast (this is why we have lazy loading)

**Comment by siepra** [comment]
Related PR https://github.com/ZbayApp/monorepo/pull/418

**Comment by siepra** [comment]
I completed the part with fixing scroll position which was making visual testing not reliable

**Comment by siepra** [comment]
Blocked by #379

**Comment by EmiM** [comment]
https://github.com/ZbayApp/monorepo/pull/498
