### ISSUE TITLE
e2e test for upgrading Quiet from an earlier version

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#422]
Problem: sometimes a new version of Quiet will appear to work correctly, but will break in some way when using existing data from previous versions of Quiet. 

We should write an e2e test that attempts to start Quiet with an existing community. 

Ideally this would be our 2 player e2e test, where both players are starting from a stored configuration created in a previous version of Quiet.

The way I'm picturing this is that we save some static DATA_DIR from a previous version (this can be as far back as we want) and use it with the new Quiet. Then we can clone this test so that we run it with multiple different old versions. 

Another approach would be to build from old versions, create/join community, upgrade to the new version, and make sure it works.

Also, a one player e2e test is probably enough to get us started. We don't necessarily need the 2 player test.

**Comment by holmesworcester** [comment]
@Kacper-RF do we have this test already? is this a duplicate?

**Comment by Kacper-RF** [comment]
Yes, we have that test for Linux OS.
