### ISSUE TITLE
User should be able to leave community

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#431]
Desktop: 
https://www.figma.com/file/qwkBkjAbewMd4Ze6UW1rk3/Communities?node-id=266%3A906&t=IRBIUqlUuQyJFIUY-4

Mobile: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-(and-prototype)?node-id=460%3A17126&t=i2gvPatZAwQfFJIq-4

There's some reconciling we haven't done yet between mobile and desktop, and all the other mobile settings aren't there yet, so on mobile just stick "Leave community" in this menu that slides up from the bottom when you click the "..." menu button in the top right. 

Confirmation prompt text below headline should be:

"Are you sure you want to delete [community-name] from this device?" (with community-name in bold)

Notes:
* It should delete all files and IDs associated with this community to the point where there is no suggestion that this machine was ever a member of the community.
* In the designs for the community owner it says "Delete community" but it should be "Leave community" for everyone.  
* Once they leave a community they should return to the join/create screen.

**Comment by siepra** [comment]
Those Figma designs are not consistent with our current Settings view, so I had to do it a little bit differently.

We can of course adjust the Settings view but it requires refactoring of the parent modal (e.g. it's impossible to use stories because it nests containers which makes the whole development process quite difficult).

Here is what it looks like right now:
![Screenshot from 2023-03-01 18-27-33](https://user-images.githubusercontent.com/15381135/222217208-a6f9b4fb-dbdc-43d1-8403-46428b37bbd4.png)
![Screenshot from 2023-03-01 18-27-22](https://user-images.githubusercontent.com/15381135/222217214-2b58d95d-d1ff-495b-9c13-2394bb918e3f.png)

**Comment by siepra** [comment]
https://github.com/TryQuiet/quiet/pull/1269

**Comment by holmesworcester** [comment]
Two issues here: 

1. The rocketship in the designs is the community icon, which we don't have yet. We should leave this out until we have community icons.
2. The "are you sure" confirmation needs to be a modal, I think, otherwise it will be weird. Can "leave community" be a link that opens a fullscreen modal? It doesn't have to "sit on top"; it can be its own thing that appears full screen. Closing the modal can take you back to the settings screen. 
3. Replace "Are you sure you want to delete ___ from your device?" with "Your account, messages, and all data for ____ will be deleted from this device. This cannot be undone."

**Comment by siepra** [comment]
Ok, will do!

**Comment by siepra** [comment]
This is how it looks like after changes

![Screenshot from 2023-03-06 16-42-44](https://user-images.githubusercontent.com/15381135/223158831-02a52593-20c7-4d3d-9ffc-00065e6c244a.png)
![Screenshot from 2023-03-06 16-42-37](https://user-images.githubusercontent.com/15381135/223158838-603878ae-326c-41e4-ac9f-de9969357872.png)

**Comment by holmesworcester** [comment]
The modal works great, I think! It'll be nice once we have thumbnail images but it's good for now.

![image](https://user-images.githubusercontent.com/213678/223222545-20815063-a3e3-4699-9827-50e12bc8e0cd.png)

One thing is that I think there's a difference from the design in the line height or vertical padding in the left sidebar that I think makes it look somewhat confusing or broken, because "leave community" is sort of orphaned on its own line out in space. 

In the design, on the other hand, it is somewhat grouped with the other sidebar items even though it is separate.

I think there might be other subtle differences in the sidebar tabs that make this look good in the design and not in the implementation. What do you think?

**Comment by holmesworcester** [comment]
Also, I think this might be the first issue where we are implementing a feature in both mobile and desktop at the same time. 

I'm curious what part of the code is shared vs. what part is duplicated between mobile and desktop. Is there some redux action for "leave community" that is the same in both mobile and desktop?

**Comment by siepra** [comment]
Is that better?

![Screenshot from 2023-03-07 11-51-56](https://user-images.githubusercontent.com/15381135/223401815-9f36770d-b95c-4e4c-b33d-2579a5bec2ea.png)

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.3

It's working and it looks as per design.

There is js error that some users cen get but we have a separate task for it (and user actually leave community even when getting this error) so I consider this task as done and we will handle the rest in specific github-issues.
