### ISSUE TITLE
Fix our use of certificates (investigate Macaroons)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#442]
Follow up on the recommendations here: https://github.com/electron/electron/issues/31042#issuecomment-939116967

Then return to the ticket, give an example of the certificate we create, and ask if there is anything else we should change to ensure that the certificate is compliant and will survive future boringssl upgrades.

**Update:**

A security expert friend (twitter.com/j4cob) strongly recommends that we use [Macaroons](https://en.wikipedia.org/wiki/Macaroons_(computer_science))  instead of x509 certificates.

**Comment by Dinek007** [comment]
https://github.com/ZbayApp/monorepo/pull/462

**Comment by holmesworcester** [comment]
@kowalski there's more follow up we want to do on this, right?

**Comment by kowalski** [comment]
> @kowalski there's more follow up we want to do on this, right?

I'm planning to write personal, shorter email to a person who helped us before. If he still doesn't respond we will look for other options.

**Comment by kingalg** [comment]
@holmesworcester @kowalski is this still a valid issue?
