### ISSUE TITLE
Ensure there are no UI Performance issues with large numbers of messages in community

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#46]
It's not clear what is the weakest point in ZbatDesktop, we have separate issue in nectar to optmize selectors

(update: selectors are improved, so we should focused on 1. not sending all IDs with every new message in backend 2. maybe lazy loading)

**Comment by holmesworcester** [comment]
We should build some test communities with large numbers of messages and ensure that the app is still responsive.
