### ISSUE TITLE
Splash screen Window dominates focus and can't be dragged

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#460]
When the user install Quiet during first few seconds (for Windows) or the whole time when spinner is visible (MacOS) moving Quiet window is impossible. It's also shows at the top of any other application. 

We already had very similar issue (https://github.com/ZbayApp/monorepo/issues/282 - it wasn't draggable for the whole process of installation and registration) but it was resolved in version 0.4.1-alpha.1. 

Solution:
- Window should be draggable (especially on Mac)
- Window should be closeable (closing it should quit Quiet)
- Window should not sit on top of other windows. If user switches to another window, our window should fall into background.

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/monorepo/pull/728

**Comment by kingalg** [comment]
v 0.10.0

Fixed.
