### ISSUE TITLE
Clicking in field on join community screen and then clicking "create community" causes validation error

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#476]
steps to reproduce:

1. start quiet fresh
2. click in "invite code" text entry field
3. click "create community"

expected: create community screen appears

actual: "required field" validation error given

**Comment by josephlacey** [comment]
@holmesworcester Submitted a PR for this.

Was also testing the Chromatic build access issue with this as well.  I may need to make some changes to the permissions on the my local access token.

**Comment by holmesworcester** [comment]
Excellent! 

Do you have all the access you need to do that? I just checked and it looks like you have the same level of access as @EmiM and @Kacper-RF.

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.5
Systems: all

Fixed.
