### ISSUE TITLE
Closing the app on splash screen doesn't close the app

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#478]
Close the app (x) on splash screen - app closes for a moment, then reappears

**Comment by holmesworcester** [comment]
One solution for this would be to design a splash screen that looks like a splash screen, and then remove the close button.

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/monorepo/pull/728

**Comment by kingalg** [comment]
0.9.7-alpha.7
