### ISSUE TITLE
User should be able to send images

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#493]
One of our potential early adopters says that they would use this as a fun/random chat for their team (in advance of being able to use it as a replacement for Element someday) but that they would need images for it to be minimally fun :) 

And we constantly need images in our own internal chat for posting screenshots e.g.

So let's add images to messages in Quiet!   

Design here: https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Upload-file

Notes: 

* User should be able to drag images and copy/paste them into the message entry field.
* We don't have to tackle the UI for uploading non-image files yet, though we could if we think it makes sense to. And it might feel weird or restrictive if you can't do this. 
* The designs imagine "uploading" an image, which doesn't really make sense in our case because at first the image will just be added locally. 
* We need to decide whether we compress images and decide about size limits for files, and what size files are downloaded automatically vs on-demand.
* We should err on the side of simplicity and ease-of-implementation in these decisions, as long as we can follow the basic UX in the designs. 

Missing in designs: 

* loading indicator and placeholder for the image itself for the user fetching it is missing.

**Comment by siepra** [comment]
Related issues:
https://github.com/ZbayApp/monorepo/issues/495
https://github.com/ZbayApp/monorepo/issues/496
https://github.com/ZbayApp/monorepo/issues/497

**Comment by holmesworcester** [comment]
![upload](https://user-images.githubusercontent.com/213678/167848795-54a84729-20f0-473a-afa6-7999be8d29dc.png)
![upload-1](https://user-images.githubusercontent.com/213678/167849224-40e92130-e734-400a-baaf-209438aec5cf.png)
![upload-3](https://user-images.githubusercontent.com/213678/167848972-0da22786-6ab2-43ea-9171-1cbc85d25acc.png)
![upload-2](https://user-images.githubusercontent.com/213678/167849001-750d99f1-5735-459e-b5e5-b3678a7359a0.png)
![upload-4](https://user-images.githubusercontent.com/213678/167849034-787f1d78-f5fb-43d4-af24-c6ea515db828.png)
![upload-5](https://user-images.githubusercontent.com/213678/167849047-e5c4692a-ac4c-4564-97e7-eb43d78d9fb5.png)
![upload-6](https://user-images.githubusercontent.com/213678/167849062-399de271-4a0d-41c4-94f3-3ba23401f6ad.png)
![upload-7](https://user-images.githubusercontent.com/213678/167849077-c544df19-4021-4b9f-8ff1-c3747590b27f.png)
![view image](https://user-images.githubusercontent.com/213678/167849119-bb056485-8494-43e3-b955-2cb4f3b914f7.png)
![upload-8](https://user-images.githubusercontent.com/213678/167849140-549743ad-b38f-4e5c-a909-9e02e844bade.png)

**Comment by holmesworcester** [comment]
[Upload file (2).zip](https://github.com/ZbayApp/monorepo/files/8669903/Upload.file.2.zip)

This is the figma export file @Dinek007
