### ISSUE TITLE
User should be able to see her online status

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#506]
We should use the "status at top of sidebar" designs from Zbay for this. Note that this status section changes position on macOS, to make room for the "traffic light" icons in the top right.  

Here's what icon and text we should use for each state.

State, icon, text:
- internet disconnected, red circle, "Offline"
- Tor is bootstrapping, spinner, "Starting Tor"
- no peers, orange, "0 peers" 
- ">0 peers" at least one peer and time-consuming replication, spinner, "n peers"
- ">0 peers" at least one peer and no replication or non-time-consuming replication, green cirlce, "n peers"

We had a design for making this status indicator clickable and expandable but we won't do that for now since this information should be sufficient. 

As with #502 tests should confirm that this information is faithful to what's actually happening including in the "internet unplugged" scenario.

Ideally when connecting it would proceed fluidly from "spinner" to "green"

**Comment by vinkabuki** [comment]
Tor is bootstrapping, spinner, "Starting Tor" - ATM we have 'general spinner' when tor is bootstrapping, so no one will ever see this. We can remove 'general spinner', it's better that users sees what's happening instead of just spinner

**Comment by holmesworcester** [comment]
Closing in favor of #1504
