### ISSUE TITLE
Volume on notifications is too high.

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#507]
Right now the volume on Quiet notifications is way too high.

I think we can use this volume method and reduce to 0.4 and it will sound right. https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

Try it out and see if it feels right. It should be audible but not annoyingly loud. 

Also, can you add this sound as the default? 

It can be called "Librarian shhh"

[notification-sshh-loud.zip](https://github.com/TryQuiet/quiet/files/9200518/notification-sshh-loud.zip)

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/759
