### ISSUE TITLE
Make a better screenshot

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#515]
We need a screenshot for the homepage but we can make a better one than this once we change the font size for emoji-only messages and add images and image uploading. 

![image](https://user-images.githubusercontent.com/213678/169164985-c1ced511-c49d-4500-b301-24bb8113ffb2.png)

**Comment by kingalg** [comment]
@holmesworcester tryquiet has nice pictures now, so I believe that this is no longer relevant. Do you agree with closing it?

**Comment by holmesworcester** [comment]
Yep. Closing.
