### ISSUE TITLE
User should be able to send files that are not images

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#532]
Designs: https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=300%3A12826

Files before sending should display as previews, like images, using this design, with a hover that shows the filename: https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=151%3A13432

In this ticket, assume that everything is downloaded automatically and pinned forever. Separate issues will let users control what is downloaded automatically and when things can be pinned forever.  

Acceptance criteria (these can become their own issues, sorted by priority):

Essential features:

1. User should be able to send a file to the channel that is not an image, and others should autodownload it and be able to see the file and the filename. User should be able to preview files in the send message field, hover to see filenames, and remove files before they are sent. 
2. User should be able to see when a file is downloading, and when it is complete. 
3. User should be able to "save" downloaded files. Saving should ensure that there is a properly named file in the user's OS default downloads folder or our own default download folder and it should open the file manager to show the file in its containing folder.  

Less essential, but important:

4. All users should be able to see the size of a file.
6. User should be able to see a file as "queued for download". This should happen when the file is not completed, but when there are no available peers with pieces of the file. Downloading should continue and state should update to downloading as soon as a peer comes online with the file.
7. User should be able to cancel a download by clicking cancel. This will stop downloading the file and remove the file.
8. User should be able to restart a canceled download

**Comment by holmesworcester** [comment]
Latest design is here: https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=300%3A13775

**Comment by siepra** [comment]
Show downloaded file in local file system


https://user-images.githubusercontent.com/15381135/177346662-8e11445a-fa13-473c-8275-d83961935504.mov

**Comment by siepra** [comment]
Upload large file


https://user-images.githubusercontent.com/15381135/177347210-c57b5d37-2bb6-4028-a207-bac8e5dcd27e.mov

**Comment by siepra** [comment]
Downloading large file

https://user-images.githubusercontent.com/15381135/177347422-44d57dda-fddc-4e3c-bef9-d488f37c6dea.mov

**Comment by siepra** [comment]
All states of the component

https://user-images.githubusercontent.com/15381135/177348857-03cf7c78-36ae-4cc0-bcce-ac86bdbca893.mov
