### ISSUE TITLE
Autodownload images and files based on size limit

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#533]
Obviously not all files should be synced by all users all the time regardless of size. But we have the luxury of letting users send large files because Quiet is p2p, so we should use that here.

Proposal:

0. Size limit is 20MB
1. Treat large images as files. Images over our size limit should be displayed to the sender and recipient as files and not displayed as images. Ideally this is true of the preview step too while sending, though that's not important. There should be no file size limit for images.
2. Files above the size limit should not autodownload.
3. Misreported size should not trigger autodownload. That is, if a malicious sender misreports the size of a file, we should abort the download as soon as the discrepancy is detected, before the download takes any significant space on disk. I should not be able to send everyone a 1GB file by saying it is 1KB in the message metadata. (This can be treated as its own separate issue.)
8. User should be notified of completed downloads. Show a notification as we would for any message. Clicking notification shows file in file manager (and makes it clear that this will happen i.e. "Click to show file") 

Designs: 

https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=300%3A12826

Future work: let users set limit for autodownloading in settings.

**Comment by holmesworcester** [comment]
Update: let's do this without a settings screen first and with just a hardcoded limit of 25MB.

**Comment by siepra** [comment]
@holmesworcester Should all kind of files below some certain size download automatically? Or does this issue refer to the images only?

**Comment by holmesworcester** [comment]
> @holmesworcester Should all kind of files below some certain size download automatically? Or does this issue refer to the images only?

All files below the size limit should be downloaded automatically, so that they are likely to be available to all users even if the original sender is offline.

**Comment by kingalg** [comment]
0.9.7-alpha.7

0, 1, 2, 4 - tested by me and working 
3 - tested automatically by @siepra and working
