### ISSUE TITLE
User should be able to jump to conversation with ctrl/cmd-t or ctrl/cmd-k

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#544]
In Slack and Discord the user can use a shortcut key to begin typing the name of the channel or conversation and navigate there using the mouse or keyboard.  

We need some search field and autocomplete dropdown for this. 

Related to #543

**Comment by holmesworcester** [comment]
Designs are here: https://www.figma.com/file/FHbtDnmYUHj9mOPzVIWaQg/Keyboard-shortcuts?node-id=7%3A2510

**Comment by holmesworcester** [comment]
@pdurbin -- here is an export of the Figma file for the time being. Apologies about those links not being public.

[Keyboard shortcuts.zip](https://github.com/TryQuiet/quiet/files/10203862/Keyboard.shortcuts.zip)

**Comment by pdurbin** [comment]
@holmesworcester no worries! Thanks for sharing these! I'll post the main one below for easy reference.

Overall, the design looks great. However, I don't see any mention of unread messages which is a major reason I use cmd-k. You might want to consider incorporating unread messages in the design, above recent channels (like Slack does).

![_](https://user-images.githubusercontent.com/21006/206950761-0f845d2e-06a8-49aa-9715-105f00719eb9.png)

**Comment by holmesworcester** [comment]
Thanks! Should we wait until we are ready to do both, or is simply being able to switch valuable in itself? (Waiting would mean maybe an extra week or two.)

**Comment by holmesworcester** [comment]
@pdurbin I created a separate ticket for that other behavior. https://github.com/TryQuiet/quiet/issues/1101

Did I miss anything?

I did not include out the unread count that Slack displays on DMs with new messages, because we don't have DMs yet.

**Comment by pdurbin** [comment]
@holmesworcester nope! Looks great! Thanks!

**Comment by kingalg** [comment]
@siepra Is it the same issue I have in #1322  ? If yes, it's not fixed in Version: 1.1.0-alpha.3

**Comment by holmesworcester** [comment]
This is done and anything remaining is being tracked elsewhere I think. Closing!
