### ISSUE TITLE
X Connection error on linux (Quiet crashed)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#546]
`Gdk-Message: 11:57:48.362: quiet: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.`

Lost the Window but Quiet was still running.

**Comment by kingalg** [comment]
@holmesworcester do you still experience this?

**Comment by holmesworcester** [comment]
I haven't seen it in a long time. Let's close this.
