### ISSUE TITLE
notification settings are not real (direct messages, mentions, and keywords don't exist)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#564]

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/713

**Comment by kingalg** [comment]
v 0.9.7-alpha.7

Changed on all systems
<img width="371" alt="Screenshot 2022-08-09 at 12 29 54" src="https://user-images.githubusercontent.com/68909168/183626977-61cdd152-19d8-4274-bee7-8a57cf85e95f.png">
