### ISSUE TITLE
Failure in Chromatic tests should block merging until approval, if practical

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#589]
See https://github.com/TryQuiet/monorepo/issues/577 for discussion. 

Someone should have to approve Chromatic tests for a PR to be merged, if Chromatic requires approval (i.e. if there's a visual change).

**Comment by leblowl** [comment]
None of the checks block merging right now. I think that's fine. I trust whoever has write access to the repo to be responsible for what they merge. Do you have a strong feeling on this? If not, I'd vote to close it.

**Comment by holmesworcester** [comment]
We can close this particular one, but we did have a regression or two recently so that indicates that we need to invest more in making some tests fast enough and reliable enough to block merging.

**Comment by kingalg** [comment]
@holmesworcester I'm moving it to the "Done" column. I'll archive it with the next version, just in case you still want to make some other issue based on your previous note.
