### ISSUE TITLE
User should be able to add a custom profile image

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#615]
Being able to have custom profile images will make things way more comfortable and fun, and it will make the the conversation view in Quiet look a lot better too.

Requirements:
1. Users should be able to add a profile image
2. Users should be able to change their profile image
4. Both registered and unregistered users should be able to add and change their profile image
3. No one should be able to update the profile image for another user (we should check that profile image changes are signed with the user's message-signing key)
4. Profile images should be visible on desktop and mobile

Nice-to-have (break out into separate issues if not done in this round of work:)

1. Mobile user should be able to add profile image
2. Desktop (and mobile) users should be able to crop profile images

When we release this we have to prioritize #614 so that people can't register the name Quiet, set their profile image to the Quiet logo, and spoof system messages.

**Comment by holmesworcester** [comment]
We'll use whatever libraries are convenient for cropping, so we just need where this displays, and how it appears in onboarding. (What's the best way to encourage using a profile photo?) 

Do Discord and Slack make it easy to pick an avatar from a list, if you don't want to add a photo?

**Comment by jgaylor** [comment]
[Figma](https://www.figma.com/file/BnANosC1KGMUvm8oU2Dr0i/Custom-profile-image?type=design&node-id=13%3A37&t=JFXK1Y663Oj9RwIh-1) and [Loom](https://www.loom.com/share/1088f957a2884fc0b74fbb09b9a54578)

**Comment by holmesworcester** [comment]
This is great. And we'll use whatever the library offers for cropping, e.g.

**Comment by kingalg** [comment]
desktop@2.1.1-alpha.0

It's working. I feel it's more like a draft of a feature than a real feature, and changing things listed in https://github.com/TryQuiet/quiet/issues/2251 would certainly help. But there is no reason to keep this issue open as its requirements have been fulfilled.

**Comment by Danie10** [comment]
I see a profile image could be added on the desktop app, but I could not find a way to add it on the Android mobile app? Am I missing something as the issue was marked completed?

**Comment by kingalg** [comment]
Hi @Danie10, mobile was a nice-to-have for this issue, and we decided to split it and make another issue. If you are interested, you can track this for mobile in https://github.com/TryQuiet/quiet/issues/2065. You are not missing anything by not seeing an option to add a profile picture in your Android app. Feel free to let me know if you have any additional questions or spot something that looks out of order!

**Comment by Danie10** [comment]
Hi @kingalg thanks I'll look at that issue. All good basically and my only other question about admin's ability to remove users, is at https://github.com/TryQuiet/quiet/issues/41.
