### ISSUE TITLE
Change "+" icon for attachments to paperclip icon

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#624]
See Figma designs for send/receive files for the paperclip icon

**Comment by siepra** [comment]
<img width="819" alt="Zrzut ekranu 2022-07-8 o 12 14 56" src="https://user-images.githubusercontent.com/15381135/177973300-4ab1a2d1-9d92-4102-a476-d92b6b30b61f.png">
<img width="819" alt="Zrzut ekranu 2022-07-8 o 12 15 01" src="https://user-images.githubusercontent.com/15381135/177973318-771093d7-1735-4461-835f-4dc710892638.png">

**Comment by kingalg** [comment]
v 0.9.7-alpha.3

Changed in all systems.
