### ISSUE TITLE
We should block switching between "create" and "join" after user submits data

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#628]
Links in `You can [create a new community] instead` and `You can [join a community] instead` should be blocked after user clicks "submits" button. Right now it's possible to create 2 hidden services.

**Comment by holmesworcester** [comment]
@EmiM what's the result if this happens?

**Comment by EmiM** [comment]
I think that UI changed since then and it's not possible to even reproduce that. @kingalg could you confirm?

**Comment by holmesworcester** [comment]
Confirmed that this is no longer possible on desktop.
