### ISSUE TITLE
App crashed after replicating new channel

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#630]
Owner created channel, user replicated and crashed with those:
![image (8)](https://user-images.githubusercontent.com/30016150/174723579-8476d9b2-de40-461c-a251-7833464056db.png)
![image (7)](https://user-images.githubusercontent.com/30016150/174723583-b95ca594-5713-44e6-8955-ff1b69e32a44.png)

**Comment by holmesworcester** [comment]
Would this have been caught by our e2e tests? 

Can a state-manager level test catch this?

**Comment by EmiM** [comment]
I don't think so, I have trouble reproducing it.

**Comment by EmiM** [comment]
Found a repeatable path for reproducing it.
Community must have at least one channel with the number of messages that trigger lazy loading (let's say "general" in this example):
* User A scrolls all the way up on "general" channel
* User B creates a new channel

That's it

**Comment by kingalg** [comment]
v 0.9.7-alpha.3 

I couldn't replicate it in a way that Emilia described (and with a few others checks) so I consider this fixed.
