### ISSUE TITLE
Run spambots on fargate

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#644]

**Comment by holmesworcester** [comment]
When this is done, the tests we want to run are:

1. 1000 users join. Log how many peers each user connects with. Send 1 message/second from *one* user, for 100 messages. Measure latency. 
3. 1000 users join, then do 0.005 messages/second from 1000 users up to 100 or 1000 messages.

**Comment by holmesworcester** [comment]
Summary so far: works fine with 100 users, provided we disable state manager or send a small number of messages.
