### ISSUE TITLE
Emoji picker fails sometimes

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#647]
There's a strange bug affecting the emoji picker. 

Steps to reproduce:

1. Resize the window to a small size
2. Open emoji picker by clicking on emoji in message field
3. Click on an emoji in the second or third row of emojis.

Expected: emoji is entered into field.

Actual: emoji picker closes but emoji is not entered.

I didn't have much trouble reproducing this but it wouldn't happen all the time. Fiddling with the window size seems to help it happen, but that might have been a coincidence. Reproduced on Mac and Linux.

**Comment by kingalg** [comment]
v 0.9.7-alpha.3

It's working on all systems now.
