### ISSUE TITLE
Confirm that only owner can trigger "user has joined"  message

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#650]
Just creating an issue for this to track it. Can non-owners trigger the "user has joined community" message, other than by joining?

Can the owner spoof the message by sending a message that is not a valid new user registration? (I don't think this presents a problem but it shouldn't be possible.)

**Comment by kingalg** [comment]
@holmesworcester how is this issue working with our new registration flow?

**Comment by holmesworcester** [comment]
Good catch! 

This notification will have to be based on something that happens when a user joins, so we won't be able to have any such strictness.

I think we can close this.
