### ISSUE TITLE
Prepare components for file sending

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#659]
Files before sending should display as previews, like images, using this design, with a hover that shows the filename: https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=151%3A13432

Downloading file should display like this:
https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=300%3A13775

Received files should display like this: https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=151%3A14184

**Comment by siepra** [comment]
Parent issue https://github.com/TryQuiet/monorepo/issues/532

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/661

**Comment by siepra** [comment]
![Uploading Zrzut ekranu 2022-06-29 o 09.08.43.png…]()

**Comment by siepra** [comment]
<img width="502" alt="Zrzut ekranu 2022-06-29 o 09 08 43" src="https://user-images.githubusercontent.com/15381135/176376621-58c9705a-b892-401a-a67c-b05e59f53443.png">

**Comment by kingalg** [comment]
@siepra What about "Cancel download" from designs? Is it not implemented yet or did we decided to skip it?

**Comment by kingalg** [comment]
0.9.7-alpha.7

Done.
