### ISSUE TITLE
Invite code prompt text is wrong, incomplete

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#664]
Right now the invite code says "Use this link to add members to quiet-team", but it isn't a link. Also there's no indication that the code will not work if the owner is not online. There should be, so that this expectation is clear. Also the community name should be capitalized for consistency. 

Text:

"To add members to Quiet-team, send them this invite code via a secure channel, e.g. Signal. You must be online the first time they join." 

Quiet-team should be bold.

**Comment by siepra** [comment]
<img width="884" alt="Zrzut ekranu 2022-07-14 o 14 16 04" src="https://user-images.githubusercontent.com/15381135/178980225-77349bd0-3b9f-47e7-8344-830b2600cfef.png">

**Comment by kingalg** [comment]
v 0.9.7-alpha.3

1. community name is bold - **done**
2. new text informing that the code will not work if the owner is not online - **done**
3. community name is capitalised - **not done**

Please do point 3 as well. 

<img width="634" alt="Screenshot 2022-08-04 at 15 50 43" src="https://user-images.githubusercontent.com/68909168/182863780-c4bcca4f-1d13-4505-ab09-a93e94c5fb20.png">

**Comment by holmesworcester** [comment]
This is very minor but let's fix

**Comment by siepra** [comment]
Done.
<img width="818" alt="Zrzut ekranu 2022-08-9 o 15 43 36" src="https://user-images.githubusercontent.com/15381135/183664819-da4431ec-d16b-40ba-b584-d64412100f53.png">

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/796

**Comment by holmesworcester** [comment]
looks good

**Comment by kingalg** [comment]
0.10.0

It's all correct now.

<img width="560" alt="Screenshot 2022-08-15 at 14 45 32" src="https://user-images.githubusercontent.com/68909168/184637408-479c1294-a41b-42d1-aaa1-e5fb3ffc5664.png">
