### ISSUE TITLE
User can cancel pending download

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#677]

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/704

**Comment by siepra** [comment]
Preview of UX for cancelling download

https://user-images.githubusercontent.com/15381135/178009900-3e690020-930e-497a-8fcb-99e35a21b174.mov

**Comment by siepra** [comment]
blocked by https://github.com/TryQuiet/monorepo/issues/706

**Comment by kingalg** [comment]
v 0.9.7-alpha.3

The user can cancel download if:
1. File is above 20 MB.
2. The user choose to download the file.
3. File already started to download but the process is not yet finished. 

Additionally - cancelling is working every time even if it's repeatedly performed on the same file (by starting download and cancelling it several times).

This is not description is not in the task but I believe that it is what you were planning @holmesworcester Let me know if there is anything I understood incorrectly. If I got it right this issue can be closed.
