### ISSUE TITLE
Compare actual and reported file size on the receiver side (filter out malicious files)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#679]
This is for the case where a file's reported size does not match its actual size.

**Comment by siepra** [comment]
@holmesworcester There's a need for additional design (file component state - malicious file warning)

**Comment by holmesworcester** [comment]
Design here: https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=300%3A13775#221295796

![image](https://user-images.githubusercontent.com/213678/176919474-0b5e0379-fa9e-46ec-890b-703de62f505f.png)

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/709

**Comment by kingalg** [comment]
0.9.7-alpha.7

Tested automatically by @siepra
