### ISSUE TITLE
Image does not display right away to sender, user must switch channel.

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#691]
Steps:

1. In latest alpha, send an image

Expected: image displays 
Actual: spinner placeholder displays, until user switches channel and switches back.

It might make sense to show a placeholder spinner while image is in the "ipfs writing" state, since that will determine whether it is sent as a file or as an image, given #680 

But the most important thing is that we fix this bug so that sent images display properly.

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/694

**Comment by kingalg** [comment]
v 0.9.7-alpha.3

Didn't happened to me in this version.
