### ISSUE TITLE
Infinite notifications if downloaded a file/image on not-active channel

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#692]

**Comment by siepra** [comment]
Uploading Nagranie z ekranu 2022-07-6 o 15.11.45.mov…

**Comment by siepra** [comment]
https://user-images.githubusercontent.com/15381135/177558411-aed351de-415c-462b-92b7-286cc815a63a.mov

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/695

**Comment by kingalg** [comment]
v 0.9.7-alpha.3

Fixed. Checked on all systems and only one notification received in each case.
