### ISSUE TITLE
Sending files should store duplicate in Quiet "uploads" folder

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#698]
Related to and probably a solution to #697.

We have a dilemma: 

1. store a duplicate of each sent file in a location Quiet controls (disadvantage: more storage, potentially blocking the send of a large file.) 
2. don't store a duplicate and rely on the original file location. Disadvantage: user can "break" a sent image in Quiet by deleting it or moving it.

#2 is a worse crime, because people are used to cloud apps where images are uploaded, so #2 will create more unexpected behavior. 

If #1 is a problem due to storage limits for large files, we could at some point not save a duplicate for files that would be too big to duplicate given available disk space, or for files over a certain size. We could make this a preference for the user too. But right now let's just duplicate since that's safest.

**Comment by siepra** [comment]
And for the feature to be fully complete we have not only to copy the file but also replace the path in message's media object with the one just created - and save those changes to redux store

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/739
