### ISSUE TITLE
New message indicator bugged on Windows

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#705]
v 0.9.5 
System - Windows
Last confirmed working version - v 0.8.3-alpha.0

New message indicator appears for the senders own messages and doesn't disappear once the user click on the button.

Steps to recreate:
1. Open quiet on Windows
2. Open any other channel than general (on general it's working correctly) - there should be enough messages to scroll through them.
3. Type and send anything.

What should happen - new message should show up on the sender screen, quiet should automatically scroll to this message. No "new message" indicator should appear as this is not a message from different user. 
What happens - quiet doesn't automatically scroll to the bottom, instead of this "new message" indicator appears. When the user click on this button nothing happens - indicator stays there and quiet doesn't scroll to the bottom.

**Comment by holmesworcester** [comment]
Can Cypress tests catch this?

**Comment by kingalg** [comment]
@EmiM asked me if I can reproduce this in newest version (0.10.0) and after several checks I couldn't. As in 0.8.3 I could reproduce it every time without failing I believe that this time it was fixed when some different changes were implemented. We decided to close this one.
