### ISSUE TITLE
Sending large file caused error

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#731]
Sent an ubuntu .iso and got a javascript error.

**Comment by holmesworcester** [comment]
@EmiM both of the following solutions are acceptable:

* limit the file size to 1GB or whatever is safe
* figure out how to send more than 1GB

Either solution is fine, whichever is less work.

This comment might be helpful. You can add to IPFS directly from the file system. 

https://github.com/embarklabs/embark/issues/774#issuecomment-441327734

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/748

**Comment by EmiM** [comment]
Note: the problem occured with files ~2GB.
We should be aware that it takes some time to write it to IPFS, eg. 
* ~5 minutes for 2.6GB file
* ~14 minutes for 3.6GB file

**Comment by kingalg** [comment]
0.9.7-alpha.7

No errors in my tests for big files.
