### ISSUE TITLE
Peers don't make outgoing connections to peers who joined after them.

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#735]
This came up in performance testing.

Steps to reproduce:

1. Start a community
2. Invite Alice
3. Then invite Bob

Expected: Alice will sync Bob's peer information and then use this to be aware of Bob's onion address and make outgoing connections to Bob when she comes online.

Actual: Alice may sync Bob's address information but she does not use it to connect to Bob in the future. She will only make outgoing connections to the community owner.

**Comment by holmesworcester** [comment]
@vinkabuki this is an accurate representation of the problem you saw, correct?

**Comment by vinkabuki** [comment]
Probably she'll get info about Bob eventually through peerDiscovery, but it will be lost after restart afaik

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/794
