### ISSUE TITLE
Dragging local folders, images from website etc. will broke the app and show JS error, it works only with images and files saved on local machine.  

### ISSUE THREAD

**Issue by Dinek007** [TryQuiet/quiet#745]
Dragging local folders, images from website etc. will broke the app and show JS error. 

![image](https://user-images.githubusercontent.com/61462655/181363084-2cc8b428-9e8f-4238-b692-bec18f090b34.png)

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/746

**Comment by kingalg** [comment]
0.9.7-alpha.7

It no longer throughs an error.
