### ISSUE TITLE
Old messages make channel display as "unread"

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#747]
Steps:

1. Start fresh quiet in existing community

Expected: once I click on a channel, it should not highlight to indicate "unread messages here" until i actually receive a newly sent message from another user, i.e. a message sent *after* I came online.
 
Actual: old messages trigger "unread" highlighting on the channel name in the channel list, as soon as they arrive, even if they were sent ages ago.

We have a filter we use to stop old messages from triggering notifications. We should use that here too.

**Comment by holmesworcester** [comment]
Notes from @siepra 

We handle the logic for that in markUnreadChannels.saga.ts. For push notifications we check message's creation date against user's last connection time (so no notification will come for the message sent while user was inactive). I'm not sure if that's ok for channel statuses though. I think I want to see the information that people were chatting in the channel while I was away. Ideally we could use the information about last seen message and keep marking channel as unread if there are newer messages present

So in this case we'd want to extend PublicChannelStatus (publicChannels.types.ts, publicChannels.slice.ts) with lastSeenMessage prop.

**Comment by holmesworcester** [comment]
The logic here should be:

Messages timestamped before a channel was last clicked should not cause a channel to highlight.

This has a downside where it will be easy to lose messages with earlier timestamps. It would also be easy to send a message that would not be seen by e.g. a moderator. 

We should figure out the UX for "new old messages." Added in #779

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/806

**Comment by kingalg** [comment]
v 0.8.4

Fixed.
