### ISSUE TITLE
User should be able to link desktop and mobile devices

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#749]
If I'm using Quiet on my phone and desktop, I want to be able to receive messages for the same account on both. Also, if I have multiple communities on Desktop, I might want those to automatically be added to mobile or vice versa. I might want to sync certain settings between desktop and mobile. 

Finally, it might be helpful for us from a development perspective to not have to worry about settings and account creation on either desktop or mobile, so that users have to start the process of creating accounts on one platform and then the other platform only includes linking functionality. From a development perspective having mobile be "no account creation / link only" might make things easier since it's easier to develop complex features on desktop.

We want communities to have as many online devices as possible for syncing and availability, so I think we don't want or don't care much about the ability to have different accounts on desktop and mobile. When devices are linked, all communities should be synced between both devices. We also probably want this to be ongoing, so that if you create or join a community on one device, your other device will sync it as soon as both devices are online at the same time. 

Requirements:

* Users would be able to start on either desktop or mobile, or potentially both, and then, whenever they want to, link their devices together so that all accounts from one device appear on the other. Ideally a change in one account would be brought to the others as soon as they were both online. 
* Messages sent from any device should 
* In all cases, linking would be done with a QR code and camera. 
* Users should be able to unlink a device that was lost or stolen. 

Questions: 

* when you delete an account does it delete in both places? 
* can users unlink a device from any device and keep using the others, and link more devices? Or are some devices unable to link new accounts? Given that account recovery is hard in a p2p context, it might be best for any device to have the ability to link new devices.

**Designs:** 

https://www.figma.com/file/3RcrYKRTiFY87TpFSqZyj4/Device-linking?node-id=7%3A2510

**Approach:**

We're likely to use this library: https://github.com/local-first-web/auth

**Comment by siepra** [comment]
We handle all the logic in backend and state-manager packages so desktop and mobile serves only as user interfaces. It means that we can develop a complex feature and test it on desktop (as it's a faster way indeed) but then mobile implementation is easy.

The only parts that requires more engagement for mobile is when we touch native services like file management, accessing hardware components etc.

The first thought that comes to my mind is that user should create a mesh of devices with one of them serving as a kind of 'server' which distributes certificates keys and manages access rights for all the other devices. It's kind of user-specific internal network. It's an inspiration from Mathematical Mesh talk from HOPE.

**Comment by holmesworcester** [comment]
One proposal for this is in: #1187

**Comment by holmesworcester** [comment]
Another requirement: Quiet should prompt users to link a second device when they join, to increase the number of devices online and the reliability of the network.

**Comment by holmesworcester** [comment]
#1187 is a better description of the issue. Closing this as a duplicate.
