### ISSUE TITLE
update CI workflow so that it builds android

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#762]
* restore secrets from previous repository (including iOS ones)
* set up build actions
* Android should build

**Not** required: iOS CI working.

If we get stuck on this, building APK locally is also an option if that works.

**Comment by holmesworcester** [comment]
Do we need to get this working for Android and iOS or is just Android enough?

**Comment by siepra** [comment]
CI works https://github.com/TryQuiet/quiet/runs/7947497878?check_suite_focus=true
