### ISSUE TITLE
Channel view has a title bar with channel name and back button

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#767]
Design here: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile?node-id=454%3A13533

Note that the channel name (unlike the DM, in the design) should have a "#" in front of it.

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/829

**Comment by siepra** [comment]
![Screenshot_2022-08-18-13-40-40-019_com zbaymobile](https://user-images.githubusercontent.com/15381135/185388188-80920f72-248f-434d-a569-0656af2d1a07.jpg)
