### ISSUE TITLE
Channel list has a title bar with community name and thumbnail

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#768]
Design: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile?node-id=500%3A22581

Acceptance criteria:

1. Channel "thumbnail" displays as first letters with light blue background
2. Channel name displays
3. Long channel names are truncated if necessary

Not required now:
* Channel switcher arrows icon
* Hamburger menu

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/829

**Comment by siepra** [comment]
![Screenshot_2022-08-18-15-10-15-439_com zbaymobile](https://user-images.githubusercontent.com/15381135/185403656-f72f9bbf-6720-4e0e-ae48-ba04d56019a6.jpg)

**Comment by kingalg** [comment]
v 0.8.4

Channel "thumbnail" displays as first letters with light blue background - done
Channel name displays - done
Long channel names are truncated if necessary - done
