### ISSUE TITLE
User should see time/date of last sent message in channel item

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#769]
Design (quickly look at whole spec for context): https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile?node-id=454%3A13092

Acceptance criteria:
1. Time of last sent data displays if today
2. "Yesterday" displays if yesterday
3. Date displays if before yesterday

**Comment by kingalg** [comment]
v 0.8.4

@siepra it's not fully working. Todays date is correct, most dates in the past are as well, however I can't see "yesterday". Messages from previous day are showing just with an hour stamp like if they were send today. See example below.

![Screenshot_20221206_094732_com zbaymobile](https://user-images.githubusercontent.com/68909168/205937149-c9abc4cf-acee-444f-bb65-ffba99761c3a.jpg)

**Comment by kingalg** [comment]
So if this bug is tracked I'm closing this issue. Bug will be handled in https://github.com/TryQuiet/quiet/issues/1022
