### ISSUE TITLE
Enable 'strict' option in tsconfig

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#77]

**Comment by holmesworcester** [comment]
are we ready for this? let's do it if so!

**Comment by EmiM** [comment]
I am switching to 'strict' package by package to avoid huge PR and resolving tons of conflicts:
* Identity: https://github.com/TryQuiet/quiet/pull/1485
* Backend:
* State-manager:
* Desktop:
* Mobile:
* E2E tests:

**Comment by EmiM** [comment]
I forgot about integration-tests package but I think we can do it later, separately.

**Comment by kingalg** [comment]
Version: 1.3.1-alpha.0

Looks fine - I didn't encounter any issue on tested apps (all system).
