### ISSUE TITLE
Channel list should be sorted by most recent message

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#771]
Design: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile?node-id=457%3A20691

Acceptance criteria:

Channels should be sorted by most recent message. That is, the channel with the most recent message should be on the top.

Note that threads with unread messages won’t always be at the top.

**Comment by holmesworcester** [comment]
Moving to "next sprint" because this feature feels conspicuously missing right now and affects my ability to see the app as real

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/914

**Comment by kingalg** [comment]
v 0.8.4
It's working as described.
