### ISSUE TITLE
Download seems to freeze and not make progress

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#787]
Version: 0.9.7-alpha.6

1. I thought that we can download only one big file at a time and the rest is put in a queue (correct me if I'm wrong). I managed to create a situation when it looks like two big files are downloading at the same time. I did it by combination of cancelling download and restarting the app. For the first time I've repeatedly cancelled and download the file. At the moment of restart it was cancelled. Second file at the moment of restart was downloading. 

<img width="1151" alt="Screenshot 2022-08-05 at 11 25 37" src="https://user-images.githubusercontent.com/68909168/183047436-959326f5-ef6f-4e2c-ae98-72d73794fe2c.png">

2. As you can see on screens below non of the files is actually downloading (for 15 minutes there was no change in state of download. 3. 

<img width="770" alt="Screenshot 2022-08-05 at 11 28 18" src="https://user-images.githubusercontent.com/68909168/183048033-a3ddea1a-3ff1-4b73-b021-717117af5612.png">

<img width="773" alt="Screenshot 2022-08-05 at 11 28 38" src="https://user-images.githubusercontent.com/68909168/183048092-bf4d2337-1c7e-4e08-a5d0-28cc521a6ccd.png">

**Comment by siepra** [comment]
1. You can simultaneously download as many files as you want. There's no bug here. Your internet transfer is limited though, so downloading a big file will slow down other downloads

**Comment by siepra** [comment]
2. It can depend on various things, mostly internet connection, tor and network state. Those downloads, I'm certain about it, are pending but sometimes even with the small files they can hang for a bit because they have no data to replicate from at the moment

**Comment by holmesworcester** [comment]
I can confirm what wiktor says that simultaneous downloads are ok.

However, both downloads making zero progress for 15 minutes is suspicious. Kinga, can you find a series of steps that reproduce this? i.e.

1. Sender is online and connected, and can send messages to receiver/downloader.
2. File makes no progress for 15 minutes

I'm going to rename this issue to focus on that.

**Comment by Dinek007** [comment]
I was trying to reproduce this bug but it seemed to work
I have 2 thoughts

1. As Wiktor said it depends on various things like internet connection, etc So in the case of a Kinga's bug, files may have been downloading at such a low speed, that progress was not visible (for example 3kb/s)

2. I think Kinga missed a feature with downloading speed, which can be very helpful in this situation (screenshot below),
so I propose to ask @kingalg to reproduce the bug once again with checking the download speed

![image](https://user-images.githubusercontent.com/61462655/183122115-c74587f4-488d-4871-8359-85f65f0bfd15.png)

**Comment by holmesworcester** [comment]
This sounds right to me. Let's consider this closed until we have proof it's not working.

**Comment by siepra** [comment]
The problem was broken auto downloading files logic. To reproduce the problem one needed to restart the application with unfinished pending download of a file exceeding auto download limit size.
Fix included in https://github.com/TryQuiet/quiet/pull/793

**Comment by vinkabuki** [comment]
Moving back, it doesn't work for me consistently.

**Comment by siepra** [comment]
I cannot reproduce

https://user-images.githubusercontent.com/15381135/184105319-6a2fc624-743d-4bc6-bb0e-28cc669d3a61.mov

<img width="1270" alt="Zrzut ekranu 2022-08-11 o 11 34 36" src="https://user-images.githubusercontent.com/15381135/184105363-275ea42e-cc08-4021-a337-d4133b3012cc.png">

**Comment by vinkabuki** [comment]
can't reproduce
