### ISSUE TITLE
Typo mistakes in Notifications

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#797]
v 0.9.7-alpha.3

Typo:

Add dot at the end of the sentence "You’ll be notified for every new message"

<img width="461" alt="Screenshot 2022-08-09 at 16 37 44" src="https://user-images.githubusercontent.com/68909168/183677383-2f3ea839-110a-4d9d-8893-86785f271a8c.png">

**Comment by siepra** [comment]
@josephlacey is this really ready for review? Could you link a PR?

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.24

Fixed.
