### ISSUE TITLE
Update mobile node binary

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#802]
We think the best way to solve https://github.com/TryQuiet/quiet/issues/298 is to update node version to >16.0.0
Issue opened in related project https://github.com/nodejs-mobile/nodejs-mobile-react-native/issues/28

**Comment by siepra** [comment]
orbit-db's package.json says:
`
{
  "name": "orbit-db",
  "version": "0.28.6",
  "description": "Distributed p2p database on IPFS",
  "author": "Haad",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/orbitdb/orbit-db"
  },
  "engines": {
    "node": ">=16.0.0"
  },
  "files": [`

**Comment by holmesworcester** [comment]
@siepra the latest on this is that we now think the problem is elsewhere, correct?

**Comment by siepra** [comment]
I think we're unblocked with this one but the question is if we want to touch it as at this moment everything seems to work perfectly.
Note that we no longer use **nodejs-mobile-react-native** and we host node binary in our own repo

**Comment by holmesworcester** [comment]
Moving out of blocked.

**Comment by holmesworcester** [comment]
@siepra this is done now, right?

**Comment by holmesworcester** [comment]
@siepra ping? I think this is done so I'm moving to waiting for review.

**Comment by siepra** [comment]
Yes, this should be closed by now
