### ISSUE TITLE
Display channels list screen immediately (white screen on startup)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#811]
We may want to display some loading screen informing the user that we're connecting to peers (as we do in desktop). At this moment the app feels broken if it takes time to replicate initial data

**Comment by holmesworcester** [comment]
@siepra can you add more detail here so I can figure out where this fits.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/835/files

**Comment by kingalg** [comment]
v 0.8.4

It's working for me.
