### ISSUE TITLE
Correct information on init screen (for better debugging)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#812]
Change 'Tor initialization in progress' to 'Connecting Tor'
Change 'Data is being retrieved from a distributed database' to 'Starting backend'

Change first check text to 'tor connected'

Change second check to indicate web socket connection instead of starting nodejs process **(this is the most important thing)**

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/822
