### ISSUE TITLE
File downloading should retry on start if app has been closed with file status 'queued'

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#815]
* Queued file is not being automatically downloaded after restarting the app
* Sometimes you can see NaN as transfer speed

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/808

Note: NaN appeared when delay between downloaded chunks of file equaled 0.

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.4
System: all

We don't have status "queued" anymore but beside that detail it's working as expected - the user can start downloading, turn off the app, turn it on and files that were downloading before automatically continue.
