### ISSUE TITLE
Display spinner if there're no messages in current channel (channels list screen)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#816]
When there's no latest message in channel, we should display some placeholder text instead of empty space on mobile's channel list

**Comment by holmesworcester** [comment]
This needs more detail.

**Comment by holmesworcester** [comment]
this can be the same "channel created" message we see on desktop and should share the same logic if possible

**Comment by Dinek007** [comment]
> 

sure

**Comment by holmesworcester** [comment]
this looks good!

**Comment by holmesworcester** [comment]
Okay, I misunderstood this and my comments were about the channel view not the channel list.

Does it look good to say "loading messages..." in the text area? 

Question: does the data become available all at once? Or do messages appear channel by channel, randomly? 

Maybe something subtle like "..." in the placeholder text is the best for now.

**Comment by siepra** [comment]
This is how it looks when selector doesn't provide last channel message (it appears pretty often on my device)
![Screenshot_2022-09-01-08-50-01-261_com zbaymobile debug](https://user-images.githubusercontent.com/15381135/187852838-ad7291ac-c865-42d2-9c7f-fcaae3a9deab.jpg)

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/863

**Comment by siepra** [comment]
I'm closing it and moving to "done" column as we changed the app behavior in this place and we have other similar tasks ready for QA
