### ISSUE TITLE
Display join & channel creation info messages the same way we do on desktop

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#817]

**Comment by holmesworcester** [comment]
@siepra can you add more detail here?

**Comment by siepra** [comment]
example
![image](https://user-images.githubusercontent.com/15381135/187669928-b2bc091c-4afb-4a8b-9d20-1fc2d75a9ba3.png)

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/878

**Comment by siepra** [comment]
![Screenshot_2022-09-06-11-03-33-300_com zbaymobile debug](https://user-images.githubusercontent.com/15381135/188594335-b6dfa58d-bb29-4182-b58e-518200e49f92.jpg)

**Comment by kingalg** [comment]
v 0.8.4

Correctly implemented.
