### ISSUE TITLE
User should be able to receive images (out of scope: gifs)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#818]
Sending and receiving images and files could be a big problem for our stack. For example, if we aren't able to run in the background and someone sends an image, there isn't any place the image is being uploaded to, and there's no natural notion of "completed upload" because peers are just downloading blocks as they can, and perhaps all peers are other mobile apps that will have the same problem. There could also be speed an performance problems that are specific to sending or downloading files and we want to uncover these. 

The only real way to know this stuff works is to use it regularly and test it in realistic situations, so we should implement a minimal version of receiving files to convince ourselves that it works. 

We decided that, since the backend is already attempting to download files, the simplest way to test this feature daily is to implement receiving and displaying images. 

**Update: we'll consider gifs out of scope for this due to performance issues. We can hide them for now. Related ticket #905**

**Comment by holmesworcester** [comment]
One more note on this: our goal here is to give ourselves casual awareness in day-to-day use of how well image loading is working, when it is working, and when it is broken. Anything that achieves this counts as success.

Also, performance does not need to be perfect or even good. We have an issue for addressing framerate and we can tackle this in another task as long as this change won't make the app unusable.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/898

**Comment by EmiM** [comment]
Things not implemented in this iteration:
* "Show in folder" functionality
* Showing gifs on messages list (it's displayed on click though). Gifs produce some serious performance issues

**Comment by EmiM** [comment]
We may also want to optimize FlatList

**Comment by EmiM** [comment]
I turned off downloading large file/image functionality because right now app is not usable when file is being downloaded (too many rerenders).

**Comment by kingalg** [comment]
v 0.8.4

Images can be received on mobile. Quality is good.
