### ISSUE TITLE
Switching to storybook erases app data (redux persist)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#828]
When developers try to work with storybook they erase app data.

One possible solution is to add a prefix for application in the debug version of the application. This will let us have two independent instances of the mobile app on this phone. 

This will let us have the debug version and the release version on the main phone.

**Comment by holmesworcester** [comment]
@siepra can you add more detail on this? when does this happen and what does it mean for us?

**Comment by holmesworcester** [comment]
@siepra is this still blocked? isn't it what we are working on now?

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/864
