### ISSUE TITLE
Users should know why username registration is taking so long and that it's still working

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#837]
It might take us some time to address #649 so we should make it clear to users what's happening and why it's taking so long. 

Proposed text; Underneath the spinner on the button we can show:

"Joining community..."

Beneath that we can show an alert/info box that says. 

"⚠ This step can take a minute or more, and the community owner must be online. [Learn more](https://github.com/TryQuiet/quiet/wiki/Quiet-FAQ#why-is-joining-a-community-so-slow-sometimes)"

**Comment by pdurbin** [comment]
Related:

- #52

(But this #837 issue has a catchier title.) 😄

**Comment by holmesworcester** [comment]
duplicate of #1280
