### ISSUE TITLE
Play Store release installs, but crashes after connecting to Tor

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#844]
```Error: dlopen failed: cannot locate symbol "napi_get_global" referenced by "/data/data/com.zbaymobile/files/nodejs-project/node_modules/orbit-db-keystore/node_modules/leveldown/prebuilds/android-arm64/node.napi.armv8.node"...```

**Comment by siepra** [comment]
Our project depends on two major versions of leveldown - 5 and 6. Any possible fix should probably be applied to both of them
`node_modules/leveldown` - leveldown 6
'node_modules/orbit-db-keystore/node_modules/leveldown` - leveldown 5

**Comment by siepra** [comment]
Solving this problem may also work for https://github.com/TryQuiet/quiet/issues/298

**Comment by siepra** [comment]
prebuildify is responsible for downloading prebuilt binaries on buildtime https://github.com/prebuild/prebuildify

**Comment by holmesworcester** [comment]
Have we assessed releasing an APK as a solution? What does that path look like?

**Comment by siepra** [comment]
Google Play doesn't allow uploading .apk files since August 2021 https://android-developers.googleblog.com/2021/06/the-future-of-android-app-bundles-is.html

**Comment by siepra** [comment]
Android app bundle (.aab) separates nested nodejs project (@quiet/backend) along with it's dependencies and native assets (binaries built against nodejs-mobile)

bundletool (https://github.com/google/bundletool) allows to build .apks file which contains `base-master.apk` - a home for `assets` directory

It gives a clue that leveldown's native binaries are  being shipped to the device but they exist in different location that the one pointed in `leveldown.js`

*all .apks and .apk files can be unpacked just as zip archives

**Comment by siepra** [comment]
It looks like project-level nested `leveldown` has `build/Release` folder containing native binary but `orbit-db-keystore` uses it's own copy of `leveldown`

**Comment by siepra** [comment]
`orbit-db-keystore` and `orbit-db-storage-adapter` are using `leveldown` major 5 which puts it in their own `node_modules`. Binary built against nodejs-mobile are being stored within main project's `node_modules/leveldown`.

Until orbit-db upgrades `level` we have to patch `node-gyp-build` paths for those orbit-db packages

**Comment by kingalg** [comment]
v 0.8.4

Fixed - I can download and open Quiet from Google Play.
