### ISSUE TITLE
Notification sound still too loud

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#846]
We should bump the notification volume down more until it matches the volume of Slack. 

And let's switch back to the old default sound, not the "Sshh" sound

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/1020

**Comment by kingalg** [comment]
v 0.12.1 

For me sound level is fine now. Default sound is now "Pow" which is also correct as per issue description.
