### ISSUE TITLE
Add factory-girl to tests

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#85]

**Comment by holmesworcester** [comment]
@Kacper-RF is this helpful for creating communities with lots of data?

**Comment by Kacper-RF** [comment]
@holmesworcester 
 For a type of test like unit test or integration test it is very helpful and we use it.
But for E2E test i think not really, i'm thinking more of an approach of copying owner dataDir with a large community into a CI workflow and using it there, but i am not sure if it will work
