### ISSUE TITLE
Sync data and display push notifications when main application thread is dead

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#853]
We should use WorkManager for periodically running tor and backend, syncing data and displaying notifications for incoming messages when the main application thread is dead

https://developer.android.com/topic/libraries/architecture/workmanager/basics

**Comment by siepra** [comment]
Firstly we need to handle notifications when the app is in bg

**Comment by holmesworcester** [comment]
This seems to be working now, correct?
