### ISSUE TITLE
Display notifications for incoming messages in non-active channels (react-native only)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#857]

**Comment by holmesworcester** [comment]
This seems like it should be part of our iOS milestone, no? I'm moving it there. LMK if you want to move it back to blocked.

**Comment by siepra** [comment]
I think we should have a separate ticket for achieving the same goal on iOS (it requires some native code). I'll explain the implementation details in next comment

**Comment by siepra** [comment]
NotificationModule exposes `notify` method to React Native. It should be called from within state-manager, with `RICH_NOTIFICATION_CHANNEL` (state-manager/src/constants.ts) passed as first argument and json parsed `ChannelMessage` object as a second argument)

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/876
