### ISSUE TITLE
Error when choosing username

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#861]
Steps to reproduce:

1. Start app
2. Paste community code
3. Choose username

Expected: it works
Actual: in a suspiciously short time (4 seconds?) I see "address not found" or "connecting to registrar failed"

Note: emilia is experiencing this too and after many attempts it works. Question: why does it fail so often? Why does it not auto retry.

**Comment by EmiM** [comment]
Fixed UI on mobile (user doesn't have to spam the button to retry registration): https://github.com/TryQuiet/quiet/pull/874

**Comment by kingalg** [comment]
v 0.8.4
I've registered 5 times on mobile and didn't encounter described issue at all. I will have this in mind but as for now it looks like the issue is resolved.
