### ISSUE TITLE
User could not install on linux (missing dependency)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#868]
`error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

Installing openssl didn't address the problem. We found other users with similar issues on Ubuntu 22.04 with other apps, so this may be an error with Ubuntu. User was on Pop!_OS which is Debian based in line with Ubuntu 22.04.

I think the first step here is to confirm that our AppImage works on Ubuntu 22.04 without any issues, and we should set up an e2e test for Ubuntu 22.x that confirms it runs without errors. 

Then it might be worth giving linux users more options, e.g. building .deb and .rpm.

**Comment by spirillen** [comment]
May I ask where you have found any docs for installing on nix...

**Comment by holmesworcester** [comment]
I'm not sure I understand the question, but download links are here: https://github.com/TryQuiet/quiet/releases/tag/quiet%400.10.0

Use the AppImage. (More info on AppImages here: https://appimage.org/)

**Comment by pdurbin** [comment]
Just popping in to say "Quiet-0.10.0.AppImage" doesn't scream, "Download me if you're on Linux". I linked to the git repo in a Slack channel and this was a response:

"Quiet looks interesting.
I don't see a Linux download nor for mobile devices
https://github.com/TryQuiet/quiet/releases/tag/quiet%400.10.0 "

**Comment by holmesworcester** [comment]
We have a friendlier download link now, for AppImage at least. Closing.
