### ISSUE TITLE
Change android app name and icon (zbay to quiet)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#879]

**Comment by siepra** [comment]
![IMG_20220906_133246](https://user-images.githubusercontent.com/15381135/188625504-0f390729-ccd9-4792-991e-228ec3a611d3.jpg)
![Screenshot_2022-09-06-13-32-52-985_com zbaymobile debug](https://user-images.githubusercontent.com/15381135/188625507-f1e7994e-f8a8-46af-a284-a688f0077158.jpg)

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/880

**Comment by kingalg** [comment]
v 0.8.4

Done.
