### ISSUE TITLE
Last seen messages on channels list always has three dots at the end

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#889]
Only the messages that exceeds particular amount of characters should be truncated and followed by three dots

**Comment by holmesworcester** [comment]
This isn't exactly true. A single character message will have no dots at the end. But many longer messages do and that's a bug.

**Comment by josephlacey** [comment]
@holmesworcester And here's the other bug I've submitted a small PR against.  The counting function for the ellipse was checking characters and not words.

**Comment by kingalg** [comment]
1.2.0

Fixed.
