### ISSUE TITLE
Low framerate on channel view / message list

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#891]
Steps to reproduce:

1. Join existing community
2. Navigate to channel view and scroll a channel.

Notes: 
* Framerate is perfect on channel list screen
* Transition is fairly fast/smooth
* All channels have a framerate problem, even ones with no messages
* It makes scrolling confusing 
* Possibly due to nested components
* Possibly due to known issue with InvertedFlatlist https://github.com/facebook/react-native/issues/30034
* Possible due to SVG thumbnails? https://stackoverflow.com/questions/54080415/rendering-network-svg-images-causes-performance-issues-on-android-react-nativei

**Comment by holmesworcester** [comment]
This issue and workaround might be relevant: https://github.com/facebook/react-native/issues/30034#issuecomment-1064299258

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1041

**Comment by kingalg** [comment]
v 0.8.4

I've checked quality on several devices and it looks good.
