### ISSUE TITLE
Typo in registration screen: "user name" should be "username"

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#892]
Steps:

1. Start fresh
2. Register username
3. Put a space or capital letter in username to trigger "will be registered as" message

"User name" should be "username"

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/993

**Comment by kingalg** [comment]
V 0.12.1 

Fixed

![image (2)](https://user-images.githubusercontent.com/68909168/204787998-4e0fb8c3-c346-4e57-b901-5e0c4e922abe.png)
