### ISSUE TITLE
All channels are initially marked as unread

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#894]
On mobile it's annoying because user receives notification for each channel at initial app start. Also it's hard to track incoming messages in channels if you haven't opened them manually at least once

**Comment by vinkabuki** [comment]
https://github.com/TryQuiet/quiet/pull/930

**Comment by kingalg** [comment]
v 0.8.4

How it's working now looks quite nice (although in this issue there is not a lot of details about how it should work).
