### ISSUE TITLE
App shows tor connected and allows username registration when there is no network connection

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#904]
It should work same as on desktop, wait for tor initialization before allowing user to try to join community

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/928

**Comment by kingalg** [comment]
v 0.8.4
When I turn off Internet and try to open Quiet it's stuck on "Starting Quiet" which is what we intended to show in this case.
