### ISSUE TITLE
Animated GIFs should display without being slow

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#905]
Right now when we display animated GIFs they are slow. I went looking for information about this and there seem to be some different options:

1. Convert animated gifs to mp4 so they will be smaller and display natively with hardware acceleration. See: https://www.puruvj.dev/blog/gif-to-mp4-ffmpeg-fluent-web &  https://github.com/tanersener/ffmpeg-kit 
2. Letting users click to play a GIF and displaying only an image preview. (https://stackoverflow.com/questions/48978958/a-more-efficient-way-to-render-animated-gifs-in-react-native)
3. Adding these tools for displaying GIF and WebP on Android https://reactnative.dev/docs/0.62/image#gif-and-webp-support-on-android

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1066
