### ISSUE TITLE
App becomes laggy if you stay in one channel on Android 13

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#918]
On a Pixel 6 the app becomes too laggy for regular use. Sometimes the app gets so laggy that text entry becomes impractical. There is a 10 or 20 second delay between typing and the text appearing. 

Steps to reproduce:
0. Run Quiet on Android 13
1. Send a few messages in general channel, without switching to other channels.

Expected: I can still type with no lags

Actual: app is too laggy to type text and send a message.

UPDATE: I just realized that by navigating out of a channel and navigating back in I can solve the problem. This is consistent with what @siepra was seeing in the logs; it's a UI problem e.g. with lazy loading. 

[logs-adb-app-slow.txt](https://github.com/TryQuiet/quiet/files/9566332/logs-adb-app-slow.txt)

**Comment by EmiM** [comment]
I tested the problem with our community and Quiet version **0.5.3-alpha.13**.
I experienced the problem on both big channel (lots of messages) and almost empty channel (in this case #new-york-plans so around 5 messages)

**Comment by EmiM** [comment]
It happened for me once on version **0.5.4-alpha.0**. @holmesworcester can you check if this is still happening to you?

**Comment by holmesworcester** [comment]
It's still happening

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1041

**Comment by kingalg** [comment]
v 0.8.4

Fixed.
