### ISSUE TITLE
Delay between loading channel list and loading any messages

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#919]
Marek experienced a long delay between loading the channel list and loading any messages. He said it felt like the app was downloading all messages before showing any messages.

@joshgay experienced this issue too, and the behavior was that notifications for new messages were displaying *and* the latest message was visible in the preview in the channel list item, so it was present in the app state.

Steps to reproduce:
1. Join our community
2. Wait for channel list to show message previews
3. Click on channel

Expected: some messages are visible immediately, e.g. at least the one in the preview, or at least there is a loading indicator.

Actual: no messages are visible, and there is no loading indicator.

A loading indicator is fine if loading takes less than 10 seconds. If it's longer than that we should fix the issue so that at least some messages appear right away, which is a better fix anyway.

**Comment by holmesworcester** [comment]
I experienced a blank area (with no spinner showing messages were loading) when clicking into specific channels, after joining. We should show messages as we receive them, and show a spinner.

**Comment by siepra** [comment]
TODO:
1. Test if images previews displays properly after moving elements in nested component instead of the container itself
2. Update test snapshots

**Comment by kingalg** [comment]
v 0.8.4 
Done.
