### ISSUE TITLE
Update privacy policy on google play

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#925]
Google Play forces us to provide legitimate privacy policy for our app. Otherwise it won't be production available

**Comment by holmesworcester** [comment]
Do we have any telemetry in the app right now? If not the privacy policy should be very straightforward.

**Comment by holmesworcester** [comment]
Privacy Policy

Quiet does not collect or store any of your data, or provide it to third parties in any way. Instead, Quiet uses Tor to send and receive data between the devices you invite to your Quiet community. You can learn more about Tor at torproject.org and you can learn more about how Quiet uses Tor at tryquiet.org.

**Comment by holmesworcester** [comment]
Can you update the privacy policy @siepra ?

**Comment by siepra** [comment]
Privacy policy must be hosted on a website and the url of that website has to be set under "Privacy policy" of the "App content" section on Google Play.

![image](https://user-images.githubusercontent.com/15381135/197576687-898d0756-c415-4dfa-9515-c918ce5c08fa.png)

@holmesworcester

**Comment by holmesworcester** [comment]
Updated
