### ISSUE TITLE
Quiet should connect to peers faster

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#929]
This issue is creating apparent unreliability on desktop and mobile. We understand it, but it's potentially masking other issues, and we know how to mitigate it, so let's do that.

Mitigations:

1. Increase the limit on simultaneous connection attempts. Can we 10x the current number and still be okay? 

2. Be more strategic about who we connect to. We could use a mix of "last seen" and "random order" or "last seen" and "most recently joined". The registrar API could give new users its list of last seen peers so that they start with some awareness of this.  

Any other proposals? 

Whatever we try, we should check against our test with 250 users to make sure it doesn't create problems.

**Comment by holmesworcester** [comment]
Prioritizing this because it's interfering with testing and dogfooding.

**Comment by vinkabuki** [comment]
1. we can't, I think 10 is the safe limit which is still a lot.
2. we'll use mix of lastSeen + mostUptime and registrar api returning itself on the first position, then lastSeen

We can't reuse our existing test directly for that.

**Comment by siepra** [comment]
Included in desktop release 0.12.1-alpha.0
