### ISSUE TITLE
Missing message on mobile

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#940]
I have a message on desktop that is persistently not visible on mobile. I don't know the steps to reproduce, but it might make sense to fuzz/spam both desktop and mobile and see if we can get them in different states.

![image](https://user-images.githubusercontent.com/213678/191812852-5c55dbcf-bfd1-4d26-9f04-5dfe68f797f0.png)

![image](https://user-images.githubusercontent.com/213678/191812943-f587819e-577e-4bc1-8e7e-611a5b6fe574.png)

**Comment by Dinek007** [comment]
> @Dinek007 this is a duplicate of #942, right?

not 100% sure, but probably yes

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/964
