### ISSUE TITLE
Problem on app start `Unable to instantiate fragment com.swmansion.rnscreens.Screen`

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#943]
https://stackoverflow.com/questions/57709742/unable-to-instantiate-fragment-com-swmansion-rnscreens-screen

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/944

**Comment by holmesworcester** [comment]
Is this in the latest release? if not, can we do a new release with this change?
