### ISSUE TITLE
Change app icon for debug version

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#945]
Using both Quiets (dev and downloaded from store) on mobile is very confusing because they have the same app icon.
Each time I have to check version name to make sure if I'm using dev or non-dev Quiet.
Having even slightly different icons would help a lot.

**Comment by EmiM** [comment]
Added description.

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/1051
