### ISSUE TITLE
Some images are still not visible on mobile

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#947]
On my device (pixel 6) in the "#fun" channel in our own community, some images have not yet loaded. 

The images are visible in my desktop client, and they were sent both my me and others, so I know they are stored by my desktop client.

However they aren't displaying in the mobile app. Instead I see a spinner. Why?

**Comment by holmesworcester** [comment]
![image](https://user-images.githubusercontent.com/213678/198036248-d70fe290-28bf-418b-a001-28656ca5fbe4.png)

**Comment by siepra** [comment]
@Dinek007 in this commit you detached `checkForMissingFiles` saga from `addInitializedCommunity` action which resulted in NOT checking for missing files on every community startup.

`askForMessages` method from `storage.ts` is only being called in specific cases eg. if data had been replicated before connected to websocket so placing it there is probably ok but it's not enough.

This is causing problems with re-checking messages and downloading images and I think it affects both mobile and desktop.

This is the commit I'm talking about
https://github.com/TryQuiet/quiet/commit/587344e80574ca5e8e161ca7d4eb2136af765b70

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/1074

**Comment by siepra** [comment]
I think the PR you linked refers to some other ticket

**Comment by kingalg** [comment]
v 0.8.5

Working.
