### ISSUE TITLE
Can't open channels from channel list

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#952]
Version: 0.5.4-alpha-0 

Steps to reproduce:

1. Start Quiet 
2. Receive notifications for new messages
3. Click notification
4. Return to phone home screen or switch to other app
5. Click notification (they don't disappear when I click on them, which is another issue)

Expected: I should land in the channel the notification was for.

Actual: I land on the channel list screen *and* I cannot click the channels to view messages. 

Note: I think these are the steps to reproduce, but I can't confirm because after force quit, Quiet is just crashing on startup.

**Comment by holmesworcester** [comment]
@Dinek007 i assigned this to you since you've been working on notifications.

**Comment by holmesworcester** [comment]
Can't reproduce in 0.5.4-alpha.3. Assuming this is fixed.

**Comment by holmesworcester** [comment]
Just saw this again. Reopening.

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/988

**Comment by kingalg** [comment]
0.8.4
Fixed.
