### ISSUE TITLE
App crashes on startup after force quit

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#953]
Version: 0.5.4-alpha-0 

(This bug did not happen in previous version)

Steps to reproduce:

1. Force quiet Quiet
2. Restart

Expected: app starts
Actual: crash on startup

This happened multiple times, though after I wanted a few minutes it stopped happening.

**Comment by siepra** [comment]
@holmesworcester is this still an issue in **0.5.4-alpha.3**?

**Comment by holmesworcester** [comment]
Can't reproduce in 0.5.4-alpha.3, and was very easy to reproduce in earlier versions.

**Comment by kingalg** [comment]
v 0.8.4

I can't reproduced it (tried on 2 mobile phones).
