### ISSUE TITLE
Sender can impersonate any user when sending to a mobile user, in the notification

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#957]
Currently we are not verifying that signatures are correct before displaying a notification.

How this happened (I think): when we implemented notifications on mobile we did it via the backend, and signature verification is not happening in the backend. 

This should have been tracked and it's good that we caught this.

A fix for this probably requires moving signature verification and other pki.js stuff out of webview and into backend.

**Comment by holmesworcester** [comment]
@Dinek007 can you confirm that this is fixed, and link to the PR here and move to "done", if so?

**Comment by Dinek007** [comment]
yes! https://github.com/TryQuiet/quiet/pull/964
