### ISSUE TITLE
Latest message visible on channels list but not on channel view

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#960]
Quiet 0.5.4-alpha.0

I can see the preview of the newest message on the channels list but the message is not visible in the channel's view.

**Update**: newest message is not being verified, that's why it's visible on channel's list. The fact that I couldn't see it in channel may be related to https://github.com/TryQuiet/quiet/issues/956

| <img src="https://user-images.githubusercontent.com/6099829/194850592-189cfc52-c61c-47e4-89f4-cfc644fdedb8.png" width="250"/> | <img src="https://user-images.githubusercontent.com/6099829/194850589-d46b1927-17c4-4424-b835-aaf7872af956.png" width="250"/> |

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/962 <- here is a test.

**Comment by holmesworcester** [comment]
@Dinek007 this is fixed, right? I'm not seeing this issue anymore.

**Comment by kingalg** [comment]
v 0.8.4

Fixed.
