### ISSUE TITLE
Backend is run multiple times

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#965]
Right now on mobile I see many notifications that backend is running, so it seems that many backends are running. We should make sure that the backend is not running more than once. (Or at least, that we only have one "foreground service" backend running at a time, and that "worker" backends don't run indefinitely.)

**Comment by vinkabuki** [comment]
It may also be the false alarm, I see there is some protection against this, but I am not sure if it do its job

**Comment by holmesworcester** [comment]
I don't see this behavior anymore
