### ISSUE TITLE
Message is truncated in notification

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#967]
In nearly every app I'm able to see the entire message in my notifications bar. But in Quiet the notification is truncated so I can't read almost any of it. 

(I think we may be using the same truncation that we use to display the message preview in the channel list?)

We should display the whole message, up to whatever the character limit is. It looks like individual phones decide how much to display depending on screen size and other factors. https://stackoverflow.com/questions/53870080/actual-android-push-message-character-limit

See also: https://material.io/design/platform-guidance/android-notifications.html#templates

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/988

**Comment by kingalg** [comment]
v 0.8.4

Fixed. We now rely on whatever device/system decide that character limit is.
