### ISSUE TITLE
Refactor storage

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/quiet#969]
nothing to add here :)

**Comment by holmesworcester** [comment]
what's the priority on this? @vinkabuki

**Comment by vinkabuki** [comment]
@holmesworcester not that urgent, but would be nice to do it eventually.

**Comment by leblowl** [comment]
I think we've at least partially done this. There is always more to refactor. I'm going to close this for now and I suggest that we open new issues with more specific refactoring goals.
