### ISSUE TITLE
Stuck in "Initializing community" for some time after wake from sleep

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#984]
This just started happening in the latest release, I think. 11.3-alpha-16. 

When I open my laptop and Quiet was already running, I see "Initializing community. This may take a few minutes." And the text entry field is blocked, i.e. the mouse cursor changes to convey that I can't click there. When I restart Quiet, everything works as it normally would and I'm able to enter a new message soon after startup.

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/1008

**Comment by kingalg** [comment]
v 0.12.1 - fixed

I was checking this for two days in all systems and didn't encounter this issue neither with freshly installed Quiets or teams Quiet that has a lot of messages and long history.
