### ISSUE TITLE
Autostart worker running nodejs backend after restarting the phone

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#985]
See user story 4 from https://github.com/TryQuiet/quiet/issues/916

**Comment by holmesworcester** [comment]
I might be wrong about this, but it looks like what we need is what they're calling "persistent" work, here: https://developer.android.com/guide/background

**Comment by siepra** [comment]
Let's wait with it for a few days as I want to try how well **0.5.4-apha.3** works and I have only one device to work on

**Comment by siepra** [comment]
Here is a PR with the code I've tried so far https://github.com/TryQuiet/quiet/pull/989

This is what I've tried:
1. Use broadcast receiver to queue worker
2. Use broadcast receiver to start activity

Here's what happens in various scenarios:
1. The app is launched, device reboots - quiet starts (tor/backend logs are present but never connects to other peers)
2. Users swipes out the app, device reboots - quiet starts (worker starts but no tor/backend logs are present)
3. User force stops the app, device reboots - quiet won't start
4. User revokes autostart permission, device reboots - quiet won't start

Those are the topics I was trying to follow during development:
1. https://stackoverflow.com/questions/40418815/activity-dont-starts-at-boot-completed - this guy's problem is he doesn't receive intent (we do)
2. https://stackoverflow.com/questions/1056570/how-to-auto-start-an-android-application - the first answer I haven't tried yet, the second answer is what I did, the third answer has some wisdom and I generally agree, the fourth answer is probably deprecated but I'll try it as well

**Comment by siepra** [comment]
Temporarily blocked by https://github.com/TryQuiet/quiet/issues/761

**Comment by siepra** [comment]
Waiting for Bartek's refactor of backend codebase

**Comment by siepra** [comment]
@kingalg What you should check here is if after device reboot, the app starts automatically (without user interaction) and is capable of receiving messages. It may take a few minutes to spin up

**Comment by kingalg** [comment]
v 0.8.4

For some users it may require change of Settings (I needed to do this on my Android device) but from our app perspective it's working.
