### ISSUE TITLE
libcrypto.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joshgay** [TryQuiet/quiet#990]
When upgrading ubuntu I encountered an error running the AppImage of Quiet. 

Error message: 
./Quiet-0.10.0.AppImage 
/tmp/.mount_Quiet-JByOPL/quiet: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

OS info: 
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS

The following fixed my error: 

wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

**Comment by holmesworcester** [comment]
This solved the problem, so it had something to do with this missing or older dependency. https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di

Default Ubuntu installs should "just work" and we should have an e2e test that covers the latest ubuntu version.

**Comment by holmesworcester** [comment]
The link included in joshgay's comments is broken now, but there are instructions at the link above ^

**Comment by siepra** [comment]
Blocked by https://github.com/TryQuiet/quiet/issues/1256

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/1255
