### ISSUE TITLE
New message indicator displays on channels with no new messages

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#996]
I connected after a few days of not being online and many channels showed the new message indicator despite not having any messages since, for example, July. It is extremely unlikely that there were any messages I've missed since July, and this is the second time in a few days that this has happened. 

This is a regression, I think.

My hypothesis is that this happened when we changed the way message senders are verified, because I think that's the only thing that has changed on desktop lately, but I might be wrong.

**Comment by holmesworcester** [comment]
Bartek notes that this might affect the version that required a database upgrade.

**Comment by holmesworcester** [comment]
emilia also had this happen once, but only after upgrade.

**Comment by Dinek007** [comment]
yes, it happened because of broken transform, https://github.com/TryQuiet/quiet/pull/1020 should fix this

**Comment by kingalg** [comment]
0.12.1 - fixed
