### ISSUE TITLE
Fix CI for deploying android build

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#997]
Also make CI deploy to internal track instead of production

**Comment by siepra** [comment]
There's a problem with packaging backend assets on "Setup environment" step
`lerna notice cli v0.6.0
lerna info versioning independent
lerna info ci enabled
lerna info PackCommand.execute Packaged @quiet/backend to /tmp/69add6be-9fa2-4b12-9c9a-e597b387fec1/quiet-backend-0.14.0-alpha.1.tgz
lerna info PackCommand.execute Packaged @quiet/identity to /tmp/5b6cc370-8261-4bc2-9234-468e27816027/quiet-identity-0.13.0-alpha.1.tgz
lerna info PackCommand.execute Packaged @quiet/logger to /tmp/9df74b2d-919c-4b46-a1ae-6ea720f6535c/quiet-logger-0.13.0-alpha.1.tgz
lerna info PackCommand.execute Packaged @quiet/state-manager to /tmp/28a38cac-d4b1-4227-8bb9-97767296ba48/quiet-state-manager-0.14.0-alpha.1.tgz
lerna info PackCommand.installDependencies Installing dependencies in /tmp/b64f43c934cb965bd496434e48ede69c
lerna info PackCommand.createZipFile Running zip [
lerna info PackCommand.createZipFile   '-FSr',
lerna info PackCommand.createZipFile   '/home/runner/work/quiet/quiet/packages/mobile/nodejs-assets/nodejs-project/backend.zip',
lerna info PackCommand.createZipFile   '.'
lerna info PackCommand.createZipFile ] { cwd: '/tmp/b64f43c934cb965bd496434e48ede69c/package' }
lerna ERR! Error: Command failed with exit code 15: zip -FSr /home/runner/work/quiet/quiet/packages/mobile/nodejs-assets/nodejs-project/backend.zip .
lerna ERR! zip I/O error: No such file or directory
lerna ERR! zip error: Could not create output file (/home/runner/work/quiet/quiet/packages/mobile/nodejs-assets/nodejs-project/backend.zip)
lerna ERR!     at makeError (/opt/hostedtoolcache/node/16.14.2/x64/lib/node_modules/rf-lerna/node_modules/execa/lib/error.js:60:11)
lerna ERR!     at handlePromise (/opt/hostedtoolcache/node/16.14.2/x64/lib/node_modules/rf-lerna/node_modules/execa/index.js:118:26)
lerna ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lerna ERR! lerna Command failed with exit code 15: zip -FSr /home/runner/work/quiet/quiet/packages/mobile/nodejs-assets/nodejs-project/backend.zip .
lerna ERR! lerna zip I/O error: No such file or directory
lerna ERR! lerna zip error: Could not create output file (/home/runner/work/quiet/quiet/packages/mobile/nodejs-assets/nodejs-project/backend.zip)
cp: cannot stat '../libp2p.patch': No such file or directory
cp: cannot stat '../orbit-db-keystore.patch': No such file or directory
cp: cannot stat '../orbit-db-storage-adapter.patch': No such file or directory`

**Comment by kowalski** [comment]
My take on it:
add `mkdir -p packages/mobile/nodejs-assets/nodejs-project` in `package.json` of mobile package in `provide-backend-assets` target
