### ISSUE TITLE
Run Tor tests 2x daily, in search of a workaround that works

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#999]
We should run the workarounds suggested by the Tor project in #979 and #959 2x daily to see if they provide any relief in situations when Tor is being very slow to connect.

**Comment by holmesworcester** [comment]
We're unblocked now. Let's wrap this up!

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1136

**Comment by EmiM** [comment]
Results are being gathered here: https://s3.console.aws.amazon.com/s3/buckets/tor-connection-data?region=us-east-1&tab=objects#
List of scheduled tasks: https://us-east-1.console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/tor-connection-test-ECSCluster-8CyYgr3FVyzw/scheduledTasks

Right now we run the following configurations:
* default (just regular request repeated when previous request fails)
* NumEntryGuards set to 3
* newnym signal before each request
* No Vanguards
